### ISSUE TITLE
Path implementation

### ISSUE THREAD

**Issue by ferenczAndras** [servocoder/RichFilemanager#1]
I was using the old version of the file Manager and I found this repo. I want to update my files to this, but i have a problem. 
My folder system is like the following:

admin/
index.php
/assets/ filemanager.js etc.
/components/ filemanager.php
/userfiles/ - the userfiles folder

and always shows thath the path is invalid. how to resolve this problem?

**Comment by servocoder** [comment]
Did the old version work well with the files structure you have exposed?
Share your config file for old version and specify what version of the filemanager you used before trying to update.

Check also your browser console for any errors.

**Comment by ferenczAndras** [comment]
The error was, the fact that at init the js the "path" as: mysite/admin wich wasn't in the userfiles folder. Afer changing the fileRoot option in config file to : "/" was loaded, and it works properly

**Comment by servocoder** [comment]
Great! Please report of any issues you face.

**Comment by servocoder** [comment]
Btw, looking through your GitHub profile I can suppose you are Java oriented developer. Could you help with any of non-supported connectors?

**Comment by ferenczAndras** [comment]
According to the third comment, in this issue at the original repostory, https://github.com/simogeo/Filemanager/issues/491 I would like it to help, a lot :) I will go through the connectors and see what can be improved :)

**Comment by servocoder** [comment]
Nice to hear :)
I have just moved API to the wiki and made it up-to-date, so you can check it while working with connectors. Thanks for the willing to help.

**Comment by simogeo** [comment]
> According to the third comment, in this issue at the original repostory, simogeo/Filemanager#491 I would like it to help, a lot :) I will go through the connectors and see what can be improved :)

excellent !
