### ISSUE TITLE
The recommend file icons size

### ISSUE THREAD

**Issue by billzt** [servocoder/RichFilemanager#10]
Some useful file types (such as `iso`) miss their icons in `images/fileicons`. I want to know the recommend file icons size (px). Then I would add some icons (and also make pull request)

**Comment by simogeo** [comment]
They are 128x128px. See https://github.com/servocoder/RichFilemanager/blob/master/images/fileicons/xlsx.png

**Comment by servocoder** [comment]
@billzt, Try to find icons in the similar style, if you want to add some new.
@simogeo, Do you know the name or location of the current icons set for gridview? Perhaps there are more icons in the original set, and we are able to get some from it.

**Comment by simogeo** [comment]
Bugs are fixed, indeed.

Originally, icons are form : http://gotecnologias.com/images/icons/finefiles/
