### ISSUE TITLE
Feature request: multiple files download

### ISSUE THREAD

**Issue by billzt** [servocoder/RichFilemanager#11]
I suggest whether multiple files download is possible: add checkbox beside the files, choose them, and then click to download

**Comment by servocoder** [comment]
Multiple selection for batch download is an interesting idea. I have been considered it some time ago. It could be utilized for other batch actions like move, delete, etc. But there are also some difficulties I can see. What if some of selected files are protected or not exists anymore. That will cause to only "allowed" files are downloaded (moved/deleted...). It would be a good practice to notify user about files that are failed during an action, but I don't like the idea to show up a lot of popups for each file or a huge popup with all files listed. What do you think?

I will think over this idea and you can share your thoughts as well.

**Comment by servocoder** [comment]
@blitz selectable items and multiple actions (move, devele and upload) are now implemented at ["selectable" branch](https://github.com/servocoder/RichFilemanager/tree/selectable). You could download and check it now. Let me know if it works for you. Any feed back is appreciated.

**Comment by servocoder** [comment]
Released in v2.1.0
