### ISSUE TITLE
User folders + global folder

### ISSUE THREAD

**Issue by natedigzz** [servocoder/RichFilemanager#113]
I recently inherited a project that utilizes this file manager.  (currently using the depreciated version) I plan to upgrade in the next week or two. I need to ensure that my predecessor has not added any custom features of his own before i proceed with that. Anyways...

The file-manager is set up and user folders are set up and working.  I have a global folder in which I want every user to have read-only access to.  

any advice/help/direction is much appreciated! Thanks in advance.

**Comment by servocoder** [comment]
Simply set appropriate permissions (read-only) for the global folder in your file system.

**Comment by natedigzz** [comment]
The user folders are located at
/Uploads/Tenants/{username}

The global folder is located elsewhere. 
/commonfiles


Something like this. The global folder is two levels up from the setrootfolder.  How do i get the global folder to load and display in the filemanager for every user?

**Comment by natedigzz** [comment]
Since the userfolders are handled in the user.config file how do i get it to also load a folder other than the root directory.

**Comment by servocoder** [comment]
Not possible for user to navigate outside his particular root storage folder, it's a security restriction.
However, you may create symlink inside each user folder to the global folder.

**Comment by natedigzz** [comment]
Is there documentation on that?

**Comment by servocoder** [comment]
Check this article: https://github.com/servocoder/RichFilemanager/wiki/Specify-user-folder%2C-configuration-cases

**Comment by natedigzz** [comment]
alright thank you very much sir. Ill see what I can do. I really appreciate the response.
