### ISSUE TITLE
Why your demo site can not upload code file like xxx.java

### ISSUE THREAD

**Issue by ganyao114** [servocoder/RichFilemanager#115]
1.how to support code file?
2.how to support python server?

**Comment by servocoder** [comment]
1. See [configuration options](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options), `upload`.`restriction` section. For the PHP connector the list of allowed extensions is also duplicated in the config.php file.

2. You have to use [python connector](https://github.com/servocoder/RichFilemanager/tree/master/connectors/python). However the current python connector is completely outdated and should be rewritten to implement [RichFilemanager API](https://github.com/servocoder/RichFilemanager/wiki/API). I will appreciate if you are able to update/rewrite python connector.

**Comment by ganyao114** [comment]
How to dynamicly generate a private zone for each user who visit my site.I want refer to the ashx code to rewrite a python connector, but i can not find a par about path in the init function.

**Comment by servocoder** [comment]
You can refer to ASHX connector, but it doesn't support all features. You'd better rely on PHP connector.

See [Specify user folder](https://github.com/servocoder/RichFilemanager/wiki/Specify-user-folder%2C-configuration-cases) wiki article to get answer on your request. Don't hesitate to explore Wiki.

**Comment by ganyao114** [comment]
thank you,i should learn php first,sorry to disturb you.

**Comment by servocoder** [comment]
Sure, feel free to ask if you will not find answers for you questions in the wiki.
