### ISSUE TITLE
Problems with setting viewer.previewUrl

### ISSUE THREAD

**Issue by justingit** [servocoder/RichFilemanager#116]
I'm trying to use RichFilemanager with CKEditor. I still cannot get RichFilemanager to return the URL of the image I've selected, no matter what I try. Instead, I continue to get the Connector URL. 

In my setup, files are to be uploaded in a folder outside of RichFilemanager: 

Absolute Server Path: 
/home/myaccount/public_html/file_uploads

URL:
http://example.com/file_uploads

RichFileManager is set up at: 

Absolute Server Path: 
/home/myaccount/public_html/RichFilemanager-2.2.2

URL:
http://example.com/RichFilemanager-2.2.2

I am under the impression that **viewer.previewUrl** in **config.filemanager.config.json** will be used if set to a URL of the parent folder, and **viewer.absolutePath** is set to, **true**:

    "viewer": {
        "absolutePath": true,
        "previewUrl": "http://example.com/file_uploads/",

I have set up, **RichFilemanager-2.2.2/connectors/php/config.php** with the following: 

        "serverRoot" => false,
        "fileRoot" => "/home/myaccount/public_html/file_uploads/",

Selecting a file will still generate a URL like this, 

     http://example.com/RichFilemanager-2.2.2/connectors/php/filemanager.php?mode=readfile&path=file.jpg&time=1488412519863

What am I doing incorrect?

**Comment by servocoder** [comment]
Your setup is completely correct.
There was a bug that prevents to use absolute path, even when "previewUrl" is set explicitly in combination with your server-side options. I have fixed it at the [DEV branch](https://github.com/servocoder/RichFilemanager/tree/dev). Check it and post the feedback, please. I will include the bugfix in the next release if it works for you.

**Comment by justingit** [comment]
As always, I appreciate your reply. I'll try out the dev. branch and report my findings,

**Comment by justingit** [comment]
The changes made in the dev branch make the app behave in a correct way. 

One question: why is there a ?time= query string added to the URL of the image?

**Comment by servocoder** [comment]
It is used to disable image caching while preview, however it's useless upon selection. I've been going to remove it for a long time. Seems the time has come )

**Comment by servocoder** [comment]
Fixed, check it, please.

**Comment by justingit** [comment]
> Fixed, check it, please.

**Comment by servocoder** [comment]
Fixed in v2.3.0
