### ISSUE TITLE
Not Allowed to Download Folders

### ISSUE THREAD

**Issue by Buscher7173** [servocoder/RichFilemanager#117]
I'm getting the "You are not allowed to process this action." error when trying to download folders. My filemanager.config.default and filemanager.config.json files both contain these rules:

`    "security": {
        "allowFolderDownload": true,
        "allowChangeExtensions": false,
        "allowNoExtension": false,
        "normalizeFilename": true
    }`

allowFolderDownload is set to true

I've tinkered with it as much as I know how and can't seem to figure it out.

Thanks, in advance and I apologize if this is just user error.

**Comment by servocoder** [comment]
Check "allowFolderDownload" option in the [config.php](https://github.com/servocoder/RichFilemanager/blob/master/connectors/php/config.php) file. Some options are duplicated in both configuration files. I know it 's confusing and not so explicit, but I hope to change this soon.

**Comment by Buscher7173** [comment]
Thanks for the quick reply!

I added the change to the connectors/php/config.php file:

`
"allowFolderDownload" => true
`

in the security section, and now when I try to download a folder it just appears to do nothing, single files download fine, but for folders there's no error and no download.

Thanks in advance.

**Comment by servocoder** [comment]
Looks like server-side error. Check the console of your browser for the errors. Also check your web-server (apache/nginx) log files for the errors.

**Comment by Buscher7173** [comment]
Solved! Thanks for all your help!

php zip wasn't installed

`
sudo apt-get install php7.0-zip

sudo service apache2 restart
`

once i did that it worked like a dream

**Comment by servocoder** [comment]
Great! Thanks for feedback.
