### ISSUE TITLE
codeHighlight did not work

### ISSUE THREAD

**Issue by ganyao114** [servocoder/RichFilemanager#118]
I have added “java” to the “editable” elements in the config file and set "codeHighlight": true, but codeHighlight did not work.

**Comment by servocoder** [comment]
Do the same in the [config.php](https://github.com/servocoder/RichFilemanager/blob/master/connectors/php/config.php) file, `security`.`editRestrictions` section. Some options are duplicated in both configuration files. I know it 's confusing and not so explicit, but I hope to change this soon.

**Comment by ganyao114** [comment]
did not work
response of init
{
    "data": {
        "id": "/",
        "type": "initiate",
        "attributes": {
            "config": {
                "options": {
                    "culture": "zh-cn",
                    'overrideClientConfig':False
                },
                "security": {
                    "allowFolderDownload": True,
                    'editRestrictions': [
                        "txt",
                        "csv",
                        "md",
                        "c",
                        "h",
                        "cpp",
                        "xml",
                        "json",
                        "smali",
                        "java"
                    ]
                },
                "upload": {
                    "chunkSize": 10000000,
                }
            }
        }
    }
}

and config file
[filemanager.config.json.txt](https://github.com/servocoder/RichFilemanager/files/813189/filemanager.config.json.txt)

**Comment by servocoder** [comment]
I will consider the case in detail in the coming days.

**Comment by ganyao114** [comment]
I read the code in function instantiateCodeMirror,seems that you did not impl the higntlight of the java file.

**Comment by servocoder** [comment]
I have checked it. The editor for "java" files works once you add "java" extentension to the config files, but there is no code highlighting. Is that what you mean?

In this case it really can be fixed by including appropriate CodeMirror scripts. Let me know.

**Comment by servocoder** [comment]
Fixed in v2.3.0
