### ISSUE TITLE
Fresh install from sources doesn't work

### ISSUE THREAD

**Issue by PepeLopez** [servocoder/RichFilemanager#119]
Tried to install latest version (obviously v2.2.2), knockout.js throws error and aborts. See attached image:

![grafik](https://cloud.githubusercontent.com/assets/2588312/23550813/4c4856a0-0013-11e7-8a72-74f0cd534673.png)

**Comment by servocoder** [comment]
I will check it

**Comment by simogeo** [comment]
Just installed 2.2.2 with no issue regarding knockout.js !

**Comment by PepeLopez** [comment]
@simogeo Did you install it from sources (== not git)?
I just downloaded the zip (via wget), unzipped it (via unzip) and renamed 2 files as mentioned in the instructions. Then opening the page, and that error appears.

I dunno what to do at this point :(

**Comment by simogeo** [comment]
@PepeLopez : exactly what I did myself .... I use php connector and apache server

**Comment by servocoder** [comment]
@PepeLopez What is your browser?
Try in different browsers and also try to reinstall it.

**Comment by PepeLopez** [comment]
@servocoder FF and Chrome (actual) on Win7 x64. Both with same JS error (Chrome is more detailed, so that's why I posted Chromes error).

**Comment by PepeLopez** [comment]
Ok, nevermind, I found the problem: 
Too restrictive PHP settings.
Absolutely my fault, I'm sorry! Please close this issue as bogus :(
