### ISSUE TITLE
File edit codeHighlight doesn't work

### ISSUE THREAD

**Issue by andriisalamatin** [servocoder/RichFilemanager#12]
Steps to reproduce:
1. enable config.edit.codeHighlight in config
2. add "html" to config.edit.editExt
3. Try to edit any HTML file
Error message: ReferenceError: loadJS is not defined

**Comment by servocoder** [comment]
Fixed: load CodeMirror scripts + scrollbar calculation while editing long text.
Check it out and let me know is it good for you, please.
Thank you for the report.

**Comment by andriisalamatin** [comment]
Fixed, thanks a lot.
