### ISSUE TITLE
Configs and VCS / Composer

### ISSUE THREAD

**Issue by Michal-sk** [servocoder/RichFilemanager#121]
I have seen all the issues regarding the dup configs. But my question is more related regarding the configs with deployments / vcs.

What is the best practice here, i don't commit my vendor folder but that is where the configs are stored. Is there any setting i can set in the connector that makes the connector change where the clientcode looks for the config that i overlooked?

**Comment by Michal-sk** [comment]
For now i have added the exceptions in my gitignore
```
# Allow
!vendor/servocoder/richfilemanager/config/filemanager.config.json
!vendor/servocoder/richfilemanager/config/filemanager.init.js
```

**Comment by servocoder** [comment]
There no such possibility at the moment.
