### ISSUE TITLE
timeout when downloading large files

### ISSUE THREAD

**Issue by klepsydra-robotics** [servocoder/RichFilemanager#129]
Dear all,

we are evaluating the Rich File Manager for our application, where we need to download a folder with a large number of heavy images. We have noticed that the compressing takes quite long and it always gets cancelled when we reach 50 seconds.

I am wondering if this is a timeout thing? and if so, is possible to increase such a value?

Thanks,

Pablo.

**Comment by servocoder** [comment]
RichFilemanager doesn't set any execution time limits. Check the value of `max_execution_time` parameter in your `php.ini` file.

**Comment by klepsydra-robotics** [comment]
Thanks for the prompt reply.
Your suggestion, combined with the php timeout in NGINX increased fixed the problem.
Now all works fine.

Thanks again for your help.
