### ISSUE TITLE
Naming concept

### ISSUE THREAD

**Issue by ferenczAndras** [servocoder/RichFilemanager#13]
Hy.
I have a question/suggestion.
Why the filemanager not allows to use names like: my-image.jpg?
It creates a myimage.jpg
Thanks.

**Comment by simogeo** [comment]
INdeed ! +1

**Comment by servocoder** [comment]
Hmm, can't reproduce it.
@ferenczAndras, @simogeo
Do you utilize the last version?
Could you attach your config file, please?

**Comment by ferenczAndras** [comment]
`{
    "_comment": "",
    "options": {
        "culture": "en",
        "lang": "php",
        "theme": "default",
        "defaultViewMode": "grid",
        "localizeGUI": true,
        "showFullPath": false,
        "showTitleAttr": false,
        "browseOnly": false,
        "showConfirmation": true,
        "showThumbs": true,
        "searchBox": true,
        "listFiles": true,
        "fileSorting": "NAME_ASC",
        "folderPosition": "bottom",
        "quickSelect": false,
        "charsLatinOnly": true,
        "splitterWidth": 200,
        "splitterMinWidth": 200,
        "dateFormat": "d M Y H:i",
        "serverRoot": true,
        "fileRoot": "/",
        "fileConnector": false,
        "fileRootSizeLimit": false,
        "baseUrl": false,
        "capabilities": ["select", "upload", "download", "rename", "move", "replace", "delete"],
        "logger": false,
        "plugins": []
    },
    "security": {
        "allowFolderDownload": false,
        "allowChangeExtensions": false,
        "allowNoExtension": false,
        "normalizeFilename": true,
        "uploadPolicy": "DISALLOW_ALL",
        "uploadRestrictions": [
            "jpg",
            "jpe",
            "jpeg",
            "gif",
            "png",
            "svg",
            "txt",
            "pdf",
            "odp",
            "ods",
            "odt",
            "rtf",
            "doc",
            "docx",
            "xls",
            "xlsx",
            "ppt",
            "pptx",
            "csv",
            "ogv",
            "avi",
            "mkv",
            "mp4",
            "webm",
            "m4v",
            "ogg",
            "mp3",
            "wav",
            "zip",
            "rar"
        ]
    },
    "exclude": {
        "unallowed_files": [
            ".htaccess",
            "web.config"
        ],
        "unallowed_dirs": [
            "_thumbs",
            ".CDN_ACCESS_LOGS",
            "cloudservers"
        ],
        "unallowed_files_REGEXP": "/^\\./",
        "unallowed_dirs_REGEXP": "/^\\./"
    },
    "upload": {
        "multiple": true,
        "paramName": "files",
        "chunkSize": false,
        "numberOfFiles": 10,
        "fileSizeLimit": 50000000,
        "overwrite": false,
        "imagesOnly": false
    },
    "images": {
        "imagesExt": [
            "jpg",
            "jpe",
            "jpeg",
            "gif",
            "png",
            "svg"
        ],
        "main": {
            "autoOrient": true,
            "maxWidth": 8000,
            "maxHeight": 8000
        },
        "thumbnail": {
            "enabled": true,
            "cache": true,
            "dir": "_thumbs/",
            "crop": true,
            "maxWidth": 64,
            "maxHeight": 64
        }
    },
    "videos": {
        "showVideoPlayer": true,
        "videosExt": [
            "ogv",
            "mp4",
            "webm",
            "m4v"
        ],
        "videosPlayerWidth": 400,
        "videosPlayerHeight": 222
    },
    "audios": {
        "showAudioPlayer": true,
        "audiosExt": [
            "ogg",
            "mp3",
            "wav"
        ]
    },
    "pdfs": {
        "showPdfReader": true,
        "pdfsExt": [
            "pdf",
            "odt",
            "odp",
            "ods"
        ],
        "pdfsReaderWidth": "640",
        "pdfsReaderHeight": "480"
    },
    "docs": {
        "showGoogleViewer": true,
        "docsExt": [
            "doc",
            "docx",
            "xls",
            "xlsx",
            "ppt",
            "pptx"
        ],
        "docsReaderWidth": "640",
        "docsReaderHeight": "480"
    },
    "edit": {
        "enabled": true,
        "lineNumbers": true,
        "lineWrapping": true,
        "codeHighlight": false,
        "theme": "elegant",
        "editExt": [
            "txt",
            "csv"
        ]
    },
    "customScrollbar": {
    	"enabled": true,
    	"theme": "inset-2-dark",
    	"button": true
    },
    "extras": {
        "extra_js": [],
        "extra_js_async": true
    },
    "icons": {
        "path": "./../framework/assets/filemanager/images/fileicons/",
        "directory": "_Open.png",
        "default": "default.png"
    },
    "url": "https://github.com/servocoder/RichFilemanager",
    "version": "1.0.4"
}`

Here is mine.

**Comment by simogeo** [comment]
@servocoder : I said +1 without testing it .... because should be obvious to me the RFM should behave as asked ...  but as I understand now, it probably works already (also visible in the online demo)

@ferenczAndras : do you use any framework  - with dynamic routing / url rewriting ?

**Comment by ferenczAndras** [comment]
@simogeo no. It is a framework created by me. https://github.com/ferenczAndras/tree
It seems that i forgot to update something.. I will check soon, and come back if is ok or not.

**Comment by servocoder** [comment]
Let us know of the result, please.

**Comment by ferenczAndras** [comment]
Done. Had to change a value in config file :)
