### ISSUE TITLE
[PHP] How do I pass the parameters to the connector?

### ISSUE THREAD

**Issue by karidoe** [servocoder/RichFilemanager#132]
Hello guys,

I wanted to pass parameters from calling the /index.html?foo=bar and I want it to be usable in the connector.

How do I pass the parameters to the filemanager.php ?

**Comment by servocoder** [comment]
There is no way to directly pass custom parameters from query string to the connector. You can see `api`. `requestParams` option in the [JSON configuration file](https://github.com/servocoder/RichFilemanager/blob/master/config/filemanager.config.default.json), it was initially intended to define custom request parameters that being passed to connector, but it is not implemented so far. If this can help to solve your issue I can implement it in the coming days.

Actually I thought of replacing `requestParams` option with `getParams` and `postParams` OR define another `requestMethod` parameter which will take "GET" and "POST" values. Does this make sense for you?

**Comment by karidoe** [comment]
Thank you for the very fast response!, I've customized some parts of code to make it works now - what I did was changing the file index.html to index.php and mess it up by adding some custom scripts, prepare everything for further usage and keep it in a `$_SESSION` to be make them available on the php connector.

I totally agreed with you to replace something else rather than the `requestParams` for the sake of parameter passing because there're tons of things need to be done dynamically in the real world.

One more thing please, Could it be possible to have an options to prevent users from creating sub-folders?

**Comment by servocoder** [comment]
Could you detail your case: why do you have to pass query parameters to the connector? Understanding of the use case may help to find a better solution.

> Could it be possible to have an options to prevent users from creating sub-folders?

No, the definition of sub-folder is very fuzzy and will differ for various combinations of configuration options. You have to modify connector for your specific case.

**Comment by karidoe** [comment]
> Could you detail your case: why do you have to pass query parameters to the connector? Understanding of the use case may help to find a better solution.

Nothing much, I just want to pass parameters like requesting the `rfm/index.html?foo=bar` and  and then,, the `$_GET['foo']` is ready to be used in the connector.

**Comment by Saso222** [comment]
Hey,

I'm having this need too. 

I want to pass authentication parameters (such as token) to the PHP connector, that is allocated in another server (a file server with much higher disk and so), so I can't pass them via $_SESSION.

Do you have any solution for this?

Best,
Ignacio

**Comment by servocoder** [comment]
Read the following post, try the mentioned branch and let me know if it works for you:

https://github.com/servocoder/RichFilemanager/issues/175#issuecomment-309230747

**Comment by Saso222** [comment]
Indeed it does. Thank you very much for the hard work.

**Comment by servocoder** [comment]
Released in v2.5.1
