### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by samcov** [servocoder/RichFilemanager#133]
The drag and drop feature appears to limit this feature to staying within the container, i.e. you can only drag and drop on one side of the splitter.

Is this by design, and is there a config option to allow the items to be appended to the body to allow the files to escape their folder.

FYI: I'm not asking this to be able to drag and drop between views, but to do this to drop files on a div outside of the file manager.

Thank you!

**Comment by servocoder** [comment]
Actually it's not a bad idea to extend drag'n'drop container to allow dragging items to the tree panel. I have to check capabilities. 

> FYI: I'm not asking this to be able to drag and drop between views, but to do this to drop files on a div outside of the file manager.

What exact "div outside of the file manager" do you mean? Screenshots are welcome.

**Comment by samcov** [comment]
I didn't want to add more, but you're right, it makes a lot of sense to drag to the tree pane. IMO, I think you have to add the appendTo body to escape the panel when you use relative positioning, but I'm not 100% sure.

When I say div, I'm referring to the app that this is a part of, a little bit of the thought is shown in the picture, but if you append to the body, I'll be able to drop anywhere. My goal is to use cloud files so that users never have to copy them locally, just refer to the link unless they need to edit.
![untitled](https://cloud.githubusercontent.com/assets/1551314/24264185/d33e21a4-0fbc-11e7-8f41-3376493c2e06.jpg)

**Comment by servocoder** [comment]
> When I say div, I'm referring to the app that this is a part of, a little bit of the thought is shown in the picture, but if you append to the body, I'll be able to drop anywhere.

Seems you use RFM in a way as it appears at the demo page - spreading to full page size. It's ok, however the most cases are tend to include RFM via iframe. In this case it will not be possible to use any "div" outside iframe to drag'n'drop. But even if you use full page installation it will be a bad practice to attach drag'n'drop to the "body". Taking this into accong I can try attach it to the element with class ".fm-splitter", to cover both (left and right) panels, but not more.

> My goal is to use cloud files so that users never have to copy them locally, just refer to the link unless they need to edit.

Perhaps you would like implement your own plugin for PHP connector? You can explore how the AWS S3 plugin is implemented, which also handles files located at the S3 cloud.

**Comment by samcov** [comment]
My goal was for it to look like it was part of the same page, but in fact, **it is inside an iframe**.

However, if you make it so that we can drop to and from the tree, I'll take what I can get then solve my problem another way.

The way I did it in the previous version was to add an additional menu item to each file which allowed them to add it to my app.

**Comment by servocoder** [comment]
Implemented in v2.3.1

**Comment by samcov** [comment]
Great work, thanks!

**Comment by servocoder** [comment]
I have tested it, but if you face any related issues let me know, please.

**Comment by samcov** [comment]
Will do.
