### ISSUE TITLE
XMLHttpRequest cannot load 

### ISSUE THREAD

**Issue by ferenczAndras** [servocoder/RichFilemanager#14]
This was working on localhost. Now i want to publish the site, and i really need the file manager, but i am getting the following error:

```
jquery-1.11.3.min.js:5 XMLHttpRequest cannot load http://www.site.com/framework//assets/filemanager/scripts/filemanager.config.default.json?_=1469301847633. 

Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.send
 @ jquery-1.11.3.min.js:5ajax 
@ jquery-1.11.3.min.js:5loadConfigFile 
@ filemanager.js:52(anonymous function) 
@ filemanager.js:70(anonymous function)
 @ filemanager.js:2856

filemanager.js:63 Uncaught TypeError: Cannot set property 'globals' of nullloadConfigFile
 @ filemanager.js:63(anonymous function) 
@ filemanager.js:70(anonymous function) 
@ filemanager.js:2856
```

**Comment by servocoder** [comment]
It relates on your server settings or permissions solely.
I have the latest version deployed on http://fm.16mb.com/ and it works fine.
What framework do you utilize?
One guess is that your "http://www.site.com/framework/assets" folder is protected (system permissions)

**Comment by ferenczAndras** [comment]
@servocoder  it is my own framework https://github.com/ferenczAndras/tree

**Comment by servocoder** [comment]
You have to discover the problem by yourself, it obviously doesn't apply to the filemanager directly

**Comment by servocoder** [comment]
Hello! Have you solved your problem?
