### ISSUE TITLE
Unable to perform initial request to server.

### ISSUE THREAD

**Issue by Blase133** [servocoder/RichFilemanager#144]
Hi,

I get the following message when I try to access $_SESSIONS or $_GET for user specific folders.

Unable to perform initial request to server.

I run it on a local Windows with XAMPP, PHP 5.6

Any support is highly appreciated.

**Comment by servocoder** [comment]
Seems you have some issues with your server setup. Can't give any advice for you. Sorry.

**Comment by servocoder** [comment]
Read the following wiki articles, if you haven;ot done yet:

https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup
https://github.com/servocoder/RichFilemanager/wiki/Specify-user-folder%2C-configuration-cases
