### ISSUE TITLE
PDF and DOC viewer not working at all. Help is needed

### ISSUE THREAD

**Issue by RRangioni** [servocoder/RichFilemanager#145]
OS: Linux CentOS 6.5

Fileroot for Documents:  \fileroot 

Changed the config for this following the documentation on it.
"viewer": {
        "absolutePath": true,
        "previewUrl": "/fileroot/",

The Upload and Download are working fine, but the embedded viewer is not working for PDF and Office documents.

**Comment by servocoder** [comment]
Check the description of `previewUrl` parameter in [this wiki article](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options), you have to specify absolute URL value. Also check ["Handle preview URL"](https://github.com/servocoder/RichFilemanager/wiki/Handle-preview-URL) wiki article.

**Comment by RRangioni** [comment]
Changed absolutePath to false and now PDF is working nice. Perfect.
But for the DOCX and XLSX, still no preview. What am i doing wrong ?

**Comment by servocoder** [comment]
It may fail if office files are too big.
Also, if you have specified "fileRoot" and "serverRoot" options in the `config.php` file, then you have to specify correct `previewUrl` as it's descrebed in the latter wiki article, that I provided in the previous post.

**Comment by RRangioni** [comment]
doc or docx files are <1MB in size, so i must have made a mistake in the configuration somewhere. 
in config.php:
        "serverRoot" => false,
        "fileRoot" => "/fileroot/",

in filemanager.config.json:
    "viewer": {
        "absolutePath": false,
        "previewUrl": "/fileroot/",

did i forget something?

**Comment by servocoder** [comment]
Have you read the articles that I reffered?

Again: `previewUrl` parameter expects ABSOLUTE URL that refers to access storage folder of user files, not a relative path as in your example. For example, lets suppose than you have `image.png` file located in a "root" folder of user files storage, and you can access it directly by URL `http://yourdomain.com/userfiles/image.png`. In this case you have to set `previewUrl` option to `http://yourdomain.com/userfiles/`.

**Comment by RRangioni** [comment]
@ServoCoder: i read the articles and set, in my opinion, the correct values. Everything is now working perfectly in the viewer, except for the Office files. Before the change, nothing worked at all.
I really don't know what else i can do to get it working. 
The /fileroot is the correct path, it's the first folder on a new mounted disk.

**Comment by servocoder** [comment]
Image and PDF preview are work because they use connector-based path instead of direct path, as it is desribed at "Handle preview URL" wiki atricle. Preview of office files wouldn't work in this way, it works only with direct pathes. Once you set correct `previewUrl`, as I described above, office files preview should work.

**Comment by RRangioni** [comment]
@servocoder. You lost me in here. I am not a diehard developer like you, and in this case.....i don't see the problem i'm in  :-)   Would you be so kind to help me. What must i change in my configuration in order to get it running for all files?

**Comment by servocoder** [comment]
Hmm... One question: whether the folder you have specified (`/fileroot/`) is web accessible? In other words, is that possible to reach files located in this folder directly via HTTP protocol? Like `http://domain.com/fileroot/image.png`

**Comment by RRangioni** [comment]
@servocoder: No it's not. It's outside the webroot.

**Comment by servocoder** [comment]
That is the problem.
To preview office files they have to be accessible via HTTP protocol and have direct access. The only way for your case is to create symlink to `/fileroot/` inside webroot. After that set `previewUrl` as absolute URL that refer refers to your symlink.

**Comment by RRangioni** [comment]
That's my point from the beginning. For security reasons, i don't want the files to be accessible directly from within the webroot. It should and would be necessary to route them through the connector like PDF.
With this symlink, we create access from with the webroot to a storage outside the web-accessible files. 

I moved all files to /fileroot ( new mount on extra storage ) and used the connector for viewing files. All files are working fine with the exception of Office Files. If you can create previews through the connector, it would be a great enhancement for this product.  :-)

I don't know if this is possible at all. 

R.A.

**Comment by servocoder** [comment]
It's not possible with the current previewer. Follow updates, perhaps some better way will be found in the future.
