### ISSUE TITLE
btn-copy-url not working

### ISSUE THREAD

**Issue by Summer88** [servocoder/RichFilemanager#147]
Really a nice project, just one issue:  the data-clipboard-text seems correct byt btn-copy-url click trigger a current url copy not the one in data-clipboard-text.

```
	<div class="fm-preview-title">
							<h1 data-bind="text: rdo().attributes.name, attr: {title: rdo().id}"></h1>
							<div class="fm-preview-title-controls">
								<a href="#" class="btn-copy-url" data-bind="attr: {title: $root.lg().copy_to_clipboard, 'data-clipboard-text': viewer.pureUrl()}"></a>
```
this is the result
`
<a href="#" class="btn-copy-url zeroclipboard-is-hover" data-bind="attr: {title: $root.lg().copy_to_clipboard, 'data-clipboard-text': viewer.pureUrl()}" title="Copy URL to Clipboard" data-clipboard-text="http://127.0.0.1/f/upload/test/my.pdf"></a>`

but copied url is:

> http://127.0.0.1/f/#

what am I missing?

Thanks, BR

**Comment by servocoder** [comment]
I have just checked at the [demo site](http://fm.devale.pro), it seems work well. I can't reproduce the issue. Let me know if you are able to reproduce the issue at the demo page and, if so, provide more info, please.
