### ISSUE TITLE
Multiple file upload and selection

### ISSUE THREAD

**Issue by haruncpi** [servocoder/RichFilemanager#15]
Need multiple file upload system and also multiple file selection facilities. I have faced a problem when I am making a gallery application using this file manager because I had to upload 1file and select one. This is a really bad idea for upload a lot of images in a gallery album. It will be very useful if it has multiple file upload & selection system.

**Comment by servocoder** [comment]
Could you explain what do you need more precise? The filemanager provides multiple file upload and you are able to select multiple files to upload at your files system. Or do you need some other selection system? What is the way you are using fm? It would be great if you can share a link to the system you are making.

**Comment by haruncpi** [comment]
Here is a setting name  multiple file upload but I can't select multiple files to upload and after upload files or from uploaded files I can't select multiple file to insert in my editor, for this issue (multiple files selection for editor ) i didn't find any settings.

**Comment by servocoder** [comment]
Does multiple selection work for you at http://fm.16mb.com/ ?
It is enabled by default. If you won't manage with it, then I assume it can depends on your system.

**Comment by haruncpi** [comment]
Multiple image selection is not working at http://fm.16mb.com/. 
I want to select multiple images at a time and insert into tinyMce callback. Please look at my screenshot.
![filemanager](https://cloud.githubusercontent.com/assets/11594794/17274582/d76457d8-5709-11e6-98f2-5bdf8945b7cd.png)

**Comment by servocoder** [comment]
I got it now.
I'm working on multiple selection for main actions now (move, delete, etc.)
After that I can try to implement the same thing for tinyMce and other WYSIWYG editors.
But it will take some time, I have a lack of time for filemanager currently.

**Comment by javicaballero** [comment]
Hi servocoder! Any news about this feature?

**Comment by servocoder** [comment]
I'm close to next major release 2.0 of the RichFilemanager. After it's done I'm going to implement multiple feature. It will support batch move and delete actions, but I also will pay attention to multiple select.

**Comment by servocoder** [comment]
@haruncpi, @javicaballero selectable items and multiple actions (move, devele and upload) are now implemented at ["selectable" branch](https://github.com/servocoder/RichFilemanager/tree/selectable). Multiple inserting to WYSIWYG editor are not implemented yet, but you could download and check the current version to see if the multiple selection works as you expected. Any feedback is appreciated.

**Comment by servocoder** [comment]
Ok, at the moment RichFilemanager has all tools to select multiple images and pass them to WYSIWYG editor, but I haven't found a way that editors provide an ability to accept multiple images per one selection. I will implement this feature if you find and share a way of multiple images insert to WYSIWYG editor (should be specific for each editor) step by step, with code snippets preferably.

**Comment by servocoder** [comment]
Selectable items and multiple actions released in v2.1.0
Closed due to there were no suggestions on how to insert multiple images to WYSIWYG editor(s).
