### ISSUE TITLE
Copy without flash (zeroclipboard)

### ISSUE THREAD

**Issue by fabriceci** [servocoder/RichFilemanager#150]
I suggest as Flash is dying, to replace the plugin by a new one not using Flash.

Here is a plugin that seems to do the job : [https://github.com/zenorocha/clipboard.js](https://github.com/zenorocha/clipboard.js).

There is also solution in JS : [http://stackoverflow.com/questions/39020650/click-to-copy-text-javascript](http://stackoverflow.com/questions/39020650/click-to-copy-text-javascript)

**Comment by servocoder** [comment]
Good idea, I will take a look. Any help, like PR's, is appreciated, as usual.

**Comment by servocoder** [comment]
Incuded into 2.5.0 release, check [release notes]
