### ISSUE TITLE
C# MVC - Unable to perform initial request to server.

### ISSUE THREAD

**Issue by IglooGary** [servocoder/RichFilemanager#155]
I wonder if someone could please give me a little help, I am getting the error Unable to perform initial request to server.

I realise I may have not set something in the config, but I am struggling to determin what.

I am using the latest version of RichFileManager in association with TinyMCE 4.5.6.

When I click the Insert/Edit Image Source icon, this triggers FileManager with the following:

`var cmsUrl = '/Scripts/FileManager/Index.html?&field_name=' + fieldName + '&langCode=en';

if (type == 'image') {
    cmsUrl = cmsUrl + "&type=images";
}`

This in turn hits the FileManagerController.cs Index ActionResult with the mode parameter as "initiate" and path is null, as the switch does not contain a case "initiate" it returns the default of Content("") to which I get the error.

My web.config has the following app keys:

`<appSettings>
    <add key="Filemanager_RootPath" value="/Scripts/filemanager/" />
    <add key="Filemanager_IconDirectory" value="/Scripts/filemanager/images/fileicons/" />
</appSettings>`

Any help would be much appreciated :-)

**Comment by servocoder** [comment]
MVC connector is outdated, there no maintainer to update and support it at the moment. Would you like to update it?

**Comment by IglooGary** [comment]
I'm happy to help/contribute, just don't know if I have the initial configuration set correctly.

**Comment by servocoder** [comment]
Great! I'm not aware of configuration of MVC connector. You could refer to `config.php` file of PHP connector (as example). To tell the truth I think it will be much easier to write MVC connector from scratch, because there were a lot of modification after last update of MVC connector.

**Comment by servocoder** [comment]
Check this Wiki article for API interface: https://github.com/servocoder/RichFilemanager/wiki/API

**Comment by servocoder** [comment]
Let me know if you are going to re-implement MVC connector, otherwise I will close this issue.

**Comment by IglooGary** [comment]
The issue seems to relate to C# MVC 4.5.2, I'm not at work till Monday, so will continue my investigation.

**Comment by servocoder** [comment]
@IglooGary Are you still working on MVC connector? If so take a look at #163, you can collaborate your efforts with @sinanbozkus, otherwise close this issue, please.

**Comment by IglooGary** [comment]
Resolved my issue, as it was a configuration issue, but had to revert back to the latest version of FileManager not RichFileManager, as to get my project working. I will be looking at implementing RichFileManager next week and I believe the issue I had re the configuration will be resolved.

**Comment by servocoder** [comment]
Ok, please, refer to #163 for any further ideas, discussions and contribution.
