### ISSUE TITLE
"clipboard": false, is not working

### ISSUE THREAD

**Issue by RRangioni** [servocoder/RichFilemanager#158]
I want to disable the clipboard functionality, but the setting is not working.

"clipboard": false,
or 
"clipboard": true,

are acting the same.

**Comment by servocoder** [comment]
I will check, thanks for reporting.

**Comment by servocoder** [comment]
I have checked the reported issue. Once I set `clipboard` option to `false` the all UI elements related to clipboard copy/cut/paste action are gone. Please concretize your problem.

**Comment by servocoder** [comment]
Closed due to inactivity.
