### ISSUE TITLE
allowedactions working perfect with customized userdefined access rights. Can we also hide not-allowed menuitems?

### ISSUE THREAD

**Issue by RRangioni** [servocoder/RichFilemanager#159]
I have implemented my own user access into the AllowedActions part. It's working perfect !!
The get the message that the action is not allowed. 
Is there also an option to hide the NotAllowed actions in the menu's?

//AllowedSecurity is my own user-security-role check. 
$allowed=array();
$allowed = array("select","upload","copy","move","edit");
if (AllowedSecurity('50')){  $allowed[]="download"; }
if (AllowedSecurity('51')){   $allowed[]="delete";  
                                        $allowed[]="replace";}
if (AllowedSecurity('52')){   $allowed[]="rename"; }
$fm->setAllowedActions($allowed);

**Comment by servocoder** [comment]
Specify desired actions list in `options`.`capabilities` option of JSON configuration file
