### ISSUE TITLE
File upload fails for files over 16Mb

### ISSUE THREAD

**Issue by lelithium** [servocoder/RichFilemanager#162]
Hello,

First, thank you for your work on this project, it's a really nice file manager interface.

I am having issues with uploading files over 16Mb. I have set my max upload files to 10Gb in my php.ini and config.php files, but when I upload a large file to my server, the download seems to work, I get the "upload successful" alert, but the file just isn't there... Any thoughts ?

Thanks in advance

**Comment by servocoder** [comment]
Make sure you have set both options in php.ini:
```
upload_max_filesize = 100M
post_max_size = 100M
```

Also there is `fileSizeLimit` in the `config.php` file. Make sure to set it in BYTES.

Let me know if you will continue experiece issues with upload after that.
As a workaroud you can use ckunked upload, see `upload`.`chunkSize` option in the [JSON configuration file](https://github.com/servocoder/RichFilemanager/blob/master/config/filemanager.config.default.json)

**Comment by lelithium** [comment]
I'm guessing I missed the post_max_size parameter in php.ini . Will do tonight when I have access to the server ! Thanks for your quick answer !

**Comment by servocoder** [comment]
Ok, leave a feedback and close the issue once you solve it. Thanks

**Comment by lelithium** [comment]
Progress continues... I set the post_max_size to 0 (unlimited according to php.ini comments), and upload of a 30-ish Mb file worked fine. However, an 80Mb file fails with the "Failed to write file to disk" error. Ownership of the userdirs folder is granted to www-data:www-data, and file write for the 30-ish file worked fine. Any ideas ?
Thanks again

**Comment by servocoder** [comment]
I can't help you with that, because it doesn't relate to RFM. "Failed to write file to disk" is the label for PHP constant [UPLOAD_ERR_CANT_WRITE](http://php.net/manual/ru/features.file-upload.errors.php). It may be folder permissions, out of disk size or something else.

**Comment by lelithium** [comment]
Well thanks anyway ! Your help was very appreciated !
