### ISSUE TITLE
Option passed as plugin parameters in the index file not working.

### ISSUE THREAD

**Issue by triawarman** [servocoder/RichFilemanager#167]
Hello i'm trying to change baseUrl in index.html
$('.fm-container').richFilemanager({
        baseUrl: 'something else'
});

or
'baseUrl': 'something else'

its not working, i think there's bug or i'm wrong how to use this option ?

**Comment by servocoder** [comment]
Set `baseUrl` option inside [filemanager.init.js.example](https://github.com/servocoder/RichFilemanager/blob/master/config/filemanager.init.js.example) file, or rather the copy of this file that you had to create - `filemanager.init.js`

**Comment by triawarman** [comment]
ahh yes its work now, thanks
