### ISSUE TITLE
Can't Rename Folders When They Contain Subfolders (AWS S3)

### ISSUE THREAD

**Issue by DannyGrimes89** [servocoder/RichFilemanager#168]
I have successfully hooked up your plugin to my s3 bucket and I am able to upload, delete, etc. But when it comes to renaming there appears to be some sort of issue renaming folders if they contain sub folders. I get the following error:

![developer tools - http admin evo assets plugins rich-filemanager index html trigger_name filemanager_select v_target content 2017-04-27 11-04-49](https://cloud.githubusercontent.com/assets/10912462/25478584/a1c4419c-2b39-11e7-8d85-558c479fa02e.png)

I have tracked it down to the following line in your code:
https://github.com/servocoder/RichFilemanager/blob/master/connectors/php/plugins/s3/S3Filemanager.php#L350

For some reason it throws a 404 but when I try to rename a folder with no sub folders it works perfectly. 

Any ideas?

Thanks.

**Comment by servocoder** [comment]
Pushed a fix. Try again and let me know how if works now, please.
