### ISSUE TITLE
Allowing users to choose their language

### ISSUE THREAD

**Issue by Milousek** [servocoder/RichFilemanager#171]
Hello,
This project is very good, a few minor features are missing. Do you plan to include the option of creating archives or allowing users to choose their language? It would also suit the file set-up feature, as with the FTP client.

Thanks  Miloslav

I can send an updated translation for the Czech language

**Comment by servocoder** [comment]
1. Create archive - not planned
2. Allowing users to choose their language - possible, maybe later

> I can send an updated translation for the Czech language

Sure, you can create pull request, contribution are welcome

**Comment by presta-modulShopmkCZ** [comment]
Hello,
Thank you for replying, file I send
 
S pozdravem  Kubín Miloslav

**Comment by servocoder** [comment]
Let me know if you are going to update Czech language, note that the last released version could have some new translations. Thanks.

**Comment by Milousek** [comment]
This is my updated lang file:

[cs.zip](https://github.com/servocoder/RichFilemanager/files/982558/cs.zip)

**Comment by servocoder** [comment]
Thanks, will be included in the next release
