### ISSUE TITLE
knockout-3.4.0.js:70 Uncaught Error: You cannot apply bindings multiple times to the same element.

### ISSUE THREAD

**Issue by triawarman** [servocoder/RichFilemanager#172]
i'm trying to render RichFilemanager inside pjax,
say from myurl.com/news to myurl.com/own-files

i get error :
knockout-3.4.0.js:70 Uncaught Error: You cannot apply bindings multiple times to the same element.

i read in stackoverflow that i should ko.cleanNode(node); before apply bindings ko.applybindings(fmModel);

i tried  :
node = fmModel; 
or 
node = document.getElementsByClassName('fm-preview-wrapper');

but i got weird behavior, when the filemanger previewing the image, 
its refreshing the preview every seconds.

**Comment by servocoder** [comment]
I have no experience in intergation knockout with pjax. Can't help you with this.

**Comment by triawarman** [comment]
its ok, i'l try
