### ISSUE TITLE
Ajax Responses Contain Data in response object (MVC connector)

### ISSUE THREAD

**Issue by ssinno28** [servocoder/RichFilemanager#173]
Hello,

I'm having a strange issue where the response is in the response object and not the response.data object. I'm not sure if this is a jquery thing or if it has to do with how I'm sending the response back from the server. 

Is there any way around this?

Thanks,
Sam

**Comment by servocoder** [comment]
Insufficient description for giving an advice or solution.

**Comment by ssinno28** [comment]
All of the ajax calls are expecting the body of the response in the data property of the response object. When the response comes back for me the body is in the parent object and not the data property. For instances:

```
$.ajax({
url: '/api/filemanager'
dataType:json,
success: function(response){
if(response.data){
//right here is where it errors out for me
}
}
});
```

All of the calls are set up like this...

**Comment by ssinno28** [comment]
Does that make sense? I can't tell if its jquery or something else...

**Comment by ssinno28** [comment]
Now realizing that the MVC connector which is what I was using for a reference is outdated I did not see any data object coming off of the response in that connector so I assume that it shouldn't be there. I'm now using the ash X connector to build my own

**Comment by servocoder** [comment]
That's right. It's noted at the main page that only PHP and Java connectors are actual. If you mentioned that you were trying to use MVC connector then I would caution you. Be aware that ASHX connector doesn't support all features and wasn't updated after some important incompatible changes. Please, share an updated version if you are going to update ASHX connector.

**Comment by skullycheese** [comment]
Okay well I'll probably take a look at the Java version then I'm actually
building out a version using Nancy API in c#.. I'll Share when I'm done..

**Comment by servocoder** [comment]
Thanks.
