### ISSUE TITLE
Absolute Urls

### ISSUE THREAD

**Issue by ssinno28** [servocoder/RichFilemanager#174]
Hello,

The path for my URLs are absolute, but for some reason filemanager keeps appending them as if they are a relative path. How can I get around this?

**Comment by servocoder** [comment]
Which connector do you use?
What do you mean behind this statement "The path for my URLs are absolute"?
Provide your configuration options.

**Comment by ssinno28** [comment]
I'm using azure blob storage, so the urls are not relative to my web app.. I'm building my own connector right now and when I send the image with an absolute url it always prepends the current base url to it.

**Comment by servocoder** [comment]
It's hard to say for the storage you use, but try to play with `viewer`.`absolutePath` and `viewer`.`previewUrl` options. See description here: https://github.com/servocoder/RichFilemanager/wiki/Configuration-options

**Comment by skullycheese** [comment]
Can I change the base URL in the initiate call?

**Comment by servocoder** [comment]
you can set it in your `config/filemanager.init.js` file, as it's described in the wiki article that I linked above

**Comment by ssinno28** [comment]
it says the base url is for the plugin folder, what exactly do you mean by plugin folder?

**Comment by servocoder** [comment]
The path to folder where RichFilemanager application is located. You may want to change it in case you are going to change folders structure of RFM.
