### ISSUE TITLE
ReadOnly

### ISSUE THREAD

**Issue by leonel-lordford** [servocoder/RichFilemanager#179]
Hi there, I can't configure RFM for readOnly, can I get some help? I just set readOnly config var but nothing happend, regards.

LordFord.

**Comment by servocoder** [comment]
1. What connector do you use?
2. How did you set `readOnly ` config option? Describe the steps: filename in which you made changes and exact changes.
3. Provide a code snippet of the changes: screenshot or attach file.
4. Provide the configuration of client-side JSON configuration file.

**Comment by leonel-lordford** [comment]
[configs.zip](https://github.com/servocoder/RichFilemanager/files/1011090/configs.zip)

Thanks for answering, I'm running version 2.3.2 (got it like 1 month ago
maybe), fresh install, using PHP connector, just added readOnly option both
client and server side, just like I read in the configuration options
page... you can see the file attached... I just want my users to list and
download my files...

By the way, is there any way to download folders keeping the original
folder name?

Regards...

**Comment by servocoder** [comment]
`readOnly` introduced since v2.4.0
You have to reinstall RichFilemanager via composer

> By the way, is there any way to download folders keeping the original folder name?

No. But you could create a separate ticket for this enchancement and suggest the format for downloading zip file name. I will consider your suggestions.

**Comment by leonel-lordford** [comment]
Excellent... I'll upgrade and let you know ! Thx for your answer.

**Comment by leonel-lordford** [comment]
Excellent... I'll upgrade and let you know ! Thx for your answer.

**Comment by leonel-lordford** [comment]
Excellent... I'll upgrade and let you know ! Thx for your answer.
