### ISSUE TITLE
Download: keep folder name

### ISSUE THREAD

**Issue by leonel-lordford** [servocoder/RichFilemanager#180]
This could be an enhancement:
- it would be usefull to download a folder **keeping the original folder name**, so we can locate the correct **_zip_** file in our Downloads folder.

My suggestion is to _**rename**_ the resulting zip file using this format:

**folder_name-timestamp.zip**

and maybe normalize **folder_name** removing all non-alphanumeric chars including spaces and other symbols keeping just the numbers, letters, underscores and hyphens.

Regards.

**Comment by servocoder** [comment]
Thanks for suggestion, I will consider your request.

**Comment by leonel-lordford** [comment]
I just reviewed some code and tried to solve this by myself... It works for me and send you a pull request for RichFilemanager-PHP... take a look at https://github.com/servocoder/RichFilemanager-PHP/pull/1
Hope this can be useful.
Regards...

**Comment by servocoder** [comment]
Thanks! I will review it on weekend

**Comment by leonel-lordford** [comment]
Thx ! I just used the "current" folder name since it was already "normalized"... thanks to you for this amazing project.
Regards.

**Comment by servocoder** [comment]
Incuded into 2.5.0 release, check [release notes]
Thanks for your PR
