### ISSUE TITLE
PHP Notice: Undefined index: REMOTE_ADDR

### ISSUE THREAD

**Issue by Jeffery4000** [servocoder/RichFilemanager#184]
Hi, Im new to web developing. As i try to use the php connector after configuration, I run 'sudo php filemanager.php', it give me an error with 
![image](https://cloud.githubusercontent.com/assets/27762422/26437880/46b778e4-4152-11e7-9cce-8d22d111d722.png)
May i know its that a typo or there is something wrong with my workflow?
I did try adding "@" in front of $_SERVER['REMOTE_ADDR'] but getting another error: 
<h2>Server error: MODE_ERROR</h2>

**Comment by servocoder** [comment]
What you are trying to do? RichFimanager intended to be used via web browser. You have to install and setup web server and then refer to RichFimanager by http protocol, as it works at the demo page.

**Comment by Jeffery4000** [comment]
I did try running under python SimpleHTTPServer but getting an error : 
Unable to perform initial request from server.

**Comment by servocoder** [comment]
If you are using Python connector look at this [repository](https://github.com/jsooter/RichFilemanager-Python3Flask). The maintainer of this coonector is @jsooter. You can address your questions to him.

**Comment by Jeffery4000** [comment]
Even I am running RichFilemanager in apache2, I am still getting the same error. Can you please kindly advise?

**Comment by servocoder** [comment]
No advice. I'm not aware of your web server configuration and not going to dive into it.

Btw, what connector do you use? PHP or Python?

**Comment by Jeffery4000** [comment]
PHP connector

**Comment by servocoder** [comment]
PHP connector works without issues, so you have to figure out with your webserver.
I close this issue since it doesn't relate to RichFilemanager directly.
