### ISSUE TITLE
[Help] How do I make certain file extensions visible??

### ISSUE THREAD

**Issue by egold555** [servocoder/RichFilemanager#186]
Hi,

For the life of me I can not figure this out. How do I make it so I can view .json files? I have looked in the wiki under configuration section and I have added this section to my config and it doesn't change anything.

`"security": {
	    "extensions": {
			"policy": "ALLOW_LIST",
			"restrictions": [
			    "json"
		    ]
		}
	},`

**Comment by egold555** [comment]
From what I understand, "security": '{ "extensions": { "policy": "ALLOW_LIST", "restrictions": [ "json" ] } },' should make it so I can not see any other type of file. But, I can still view, read, and edit .txt files

**Comment by servocoder** [comment]
Which file do you add these lines to?
Are you trying to modify JSON configuration file?

Have you read [Configuration options](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) wiki article? Especially section about Implicit configuration options.

There you could also fins a link to [PHP connector](https://github.com/servocoder/RichFilemanager-PHP#configuration) configuration description.

**Comment by egold555** [comment]
I figured it out. Forgot to close this
