### ISSUE TITLE
System module "zip" not found

### ISSUE THREAD

**Issue by Jeffery4000** [servocoder/RichFilemanager#187]
Hi, when i try to unzip a file its show that System Module "zip" not found like picture below.
![image](https://cloud.githubusercontent.com/assets/27762422/26478054/309f1a08-41fc-11e7-9f82-ca519be43afc.png)
May i know what's the issue? Moreover, does Rich Filemanager only support zip format for now or there is any other compressed format? I tried tar.gz but doesn't seems working.

**Comment by Jeffery4000** [comment]
Even when i try to download a folder, it doesn't show up anything. Its that suppose to let me to download the folder with zip archive?

**Comment by Jeffery4000** [comment]
Problem solved with installing php-zip. Back to the question above, does RichFilemanager only support zip archive at the moment?

**Comment by servocoder** [comment]
Right, zip extension for PHP is required for zipping feature.

RichFilemanager uses [ZipArchive](http://php.net/manual/ru/class.ziparchive.php) to handle archives, so the answer is positive. Perhaps ZipArchive supports some other types, but I didn't dive deep into this.
