### ISSUE TITLE
Minimum PHP Version? 

### ISSUE THREAD

**Issue by justingit** [servocoder/RichFilemanager#189]
Really strong work on this project - I am very impressed! 

One small question: is there a minimum php version that the php connector requires? I have experienced problems where the php connector fails for mysterious reasons, and it turns out the server account is configured to use a very old version of PHP. 

Perhaps if there is a known minimum version of PHP required, that the php connector could throw an error reporting that a newer version of PHP should be used? 

I am shipping Rich Filemanager with Dada Mail: http://dadamailproject.com/ I didn't see a way for me to edit the Wiki page to add it (https://github.com/servocoder/RichFilemanager/wiki/They-use-Filemanager)

**Comment by solaris1967** [comment]
Hi,

RichFilemanager requires PHP 5.4 or higher.

Best regards
Frank

**Comment by servocoder** [comment]
> RichFilemanager requires PHP 5.4 or higher.

This is correct, it's specified at the top of description of [PHP connector](https://github.com/servocoder/RichFilemanager-PHP) for RichFilemanager

> I am shipping Rich Filemanager with Dada Mail: http://dadamailproject.com/ I didn't see a way for me to edit the Wiki page to add it

I will do it for you

**Comment by servocoder** [comment]
Done

**Comment by justingit** [comment]
Thanks! I'll update my own docs to let people know that php v5.4 is required. That helps me out a lot, thank you!
