### ISSUE TITLE
Installation Failed with JS Error - TypeError: this.rdo(...).attributes is undefined

### ISSUE THREAD

**Issue by cornernote** [servocoder/RichFilemanager#190]
After installing I just get a spinning icon.

When I look with firebug I get this:

![image](https://cloud.githubusercontent.com/assets/51875/26632328/ea421afe-464e-11e7-93cf-fc68f432e999.png)

```
TypeError: this.rdo(...).attributes is undefined
```

Have I missed something in the installation?

**Comment by servocoder** [comment]
What connector do you use?

Change `filemanager.min.js` to `filemanager.js` inside the `index.html` file, run it again and share console error.

**Comment by cornernote** [comment]
Had the same problem, when I looked at the code I saw it was still min'd.

Seems I have enabled cloudflare JS compression, which is causing the issue.  When I disabled that everything worked fine.
