### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by leonel-lordford** [servocoder/RichFilemanager#191]
Hello, is there any way to get the exact url of any item and share it with someone? I mean, I just want my co-worker to get a file or folder but I must explain (maybe I'm wrong) by email the location and it's kind of difficult if the item is located deep in my folder structure... Maybe it's possible to add an item to the clipboard, something like "share item" o "get url" and show a messagebox like in **rename** (read-only of course) so we can copy the direct URL for downloading the file or folder...
Regards...

**Comment by servocoder** [comment]
Open the file in preview mode and click the icon next to the filename (under preview image)

![screenshot_1](https://cloud.githubusercontent.com/assets/1310273/26683541/d275e5b0-46ec-11e7-9855-390f0a26f94d.png)

This also may be added to the context menu, that appears when you click the right mouse button on file/folder item.

**Comment by servocoder** [comment]
Just checked.
Hmm... It doesn't work for me, maybe something was broken.
Let me know how it goes for you.

**Comment by leonel-lordford** [comment]
Thx for asnwer so soon... but I't doesn't work for me either, I guest that button (copy to clipboard) just work internally, maybe for "paste" in other location, but I can't use the "copied content (url)" anywhere (ie: in an email), I'm reviewing the code and trying to find a solution as well...

**Comment by jsooter** [comment]
This totally depends on your server configuration. For example in my own implementation the files are not accessible except by Rich Filemanager and the only way to get the file is to navigate to it and download it through the GUI.

However you could configure your web server to serve your file directory for read only access and then you could create the links yourself.

Apache config might look like this:
# let's say your files are in /var/files
Alias /files /var/files
<Location "/files">
    <LimitExcept GET>
        Require valid-user
    </LimitExcept>
</Location>

Then all of your links would be from yoursite.com/files/<filepath>

**Comment by leonel-lordford** [comment]
Hmmm... sounds OK, but still we need to "build" the complete path in order to add it to your SITE_ROOT, just imagine your folder structure has 7-8 levels, makes more sense to get the URL vía Copy to clipboard button, I keep looking througth the code...
Hope to find a solution soon...
Leonel.

**Comment by leonel-lordford** [comment]
For instance, I'm running a local copy and this is my current code for the copy to clipboard button:

<a href="#" class="btn-copy-url zeroclipboard-is-hover" data-bind="attr: {title: $root.lg().copy_to_clipboard, 'data-clipboard-text': viewer.pureUrl()}" title="Copiado al Portapapeles" data-clipboard-text="http://localhost/rfm24/userfiles/aqui/0000_cert.pem"></a>

The files are accesible via Apache... and the path here is easy to remember... but this is me at home, back in my office things are a lot different... Looking at the code I can see a "valid" URL in data-clipboard-text attribute, I think this is what I need to put into "clipboard", but how? 

Regards...

**Comment by jsooter** [comment]
I was able to add a link in the index.html

```html
<div class="fm-preview-title">
							<h1 data-bind="text: rdo().attributes.name, attr: {title: rdo().id}"></h1>
<!-- added a link here -->
                            <p>
                                <a data-bind="text: rdo().attributes.name, attr: {href: viewer.pureUrl(),title: rdo().id}"></a>
                            </p>
<!--end link -->
							<div class="fm-preview-title-controls">
								<a href="#" class="btn-copy-url" data-bind="attr: {title: $root.lg().copy_to_clipboard, 'data-clipboard-text': viewer.pureUrl()}"></a>
								<!-- ko if: viewer.isEditable() && !editor.enabled() && viewer.options().is_writable -->
								<a href="#" class="btn-editor-open" data-bind="attr: {title: $root.lg().editor_edit}, click: editFile"></a>
								<!-- /ko -->
								<!-- ko if: viewer.isEditable() && editor.enabled() -->
								<a href="#" class="btn-editor-save" data-bind="attr: {title: $root.lg().editor_save}, click: saveFile"></a>
								<a href="#" class="btn-editor-quit" data-bind="attr: {title: $root.lg().editor_quit}, click: closeEditor"></a>
								<!-- /ko -->
							</div>
						</div>
```

**Comment by servocoder** [comment]
Sure, it's possible to add link.
@jsooter Thanks for sharing.

However the main idea is to get the link by demand. As when you click on "Copy URL" icon. Since it's broken at the moment @leonel-lordford can use solution of @jsooter, and I'm going to fix the button either way.

**Comment by leonel-lordford** [comment]
Great... I just tried the link and works that way for me, maybe not for the rest of the users, there is only one problem: that way is useful for sharing folders..., so I think It's a better way to add an item in the context menu for each item, either it is a file or folder, and copy to the clip board maybe the correct URL for downloading the content directly or for browsing if the item is a folder... either way it's a solution already, I'l try to continue looking around and waiting for next releases...
Thx for your time.
LordFord.

**Comment by leonel-lordford** [comment]
I'm sorry.... I misspelled a sentence in my previous comment, I don't speak English so often, sorry... I mean: 

(...)Great... I just tried the link and works that way for me, maybe not for the rest of the users, there is only one problem: **that way is useless for sharing folders**(...)

So we can use the solution provided by @jsooter but only for files, in general terms the ideal would be using context menu providing a "Share" or something... copying the right path into clipboard.
I'll try to provide a solution but I'm having som problems adding a new item to clipboard... either way I'll continue to try... also waiting for the solution mentioned by @servocoder 
Regards...

**Comment by servocoder** [comment]
I undestood the problem.
I will try to add "copy URL" feature to context menu soon.

**Comment by leonel-lordford** [comment]
Hello again... I was looking at the code, maybe **ZeroClipboard** isn't working because _flash_ support in my browser, I just read it uses flash (invisible movie or something) + javascript, I'm starting reading about that now, anyway, I just tried adding **clipboard.js** and the copy url to clipboard button is working great !!! Maybe ZeroClipboard is broken or something, anyway I'll continue waiting for future releases...
LordFord.

**Comment by servocoder** [comment]
Yeap, [clipboard.js](https://github.com/zenorocha/clipboard.js) seems a good substitution.
I'm going to use it and will let you know once it's ready.
Link to #150

**Comment by leonel-lordford** [comment]
Great... hope this change won't break any other function in the system... looking forward for the next release...
LordFord.

**Comment by servocoder** [comment]
Incuded into 2.5.0 release, check [release notes](https://github.com/servocoder/RichFilemanager/releases/tag/v2.5.0).
Also see new `encodeCopyUrl` configuration options in the JSON configuration file.
