### ISSUE TITLE
ViewerJS

### ISSUE THREAD

**Issue by FlorentYaicene** [servocoder/RichFilemanager#192]
Hello,

I have an issue when I'm trying to display a pdf file. I think it's a ViewerJS issue, because my path is good(.png pictures can be displayed). Moreover, when I copy the url with the icon next to the filename (under preview image) and access it in my browser, the pdf is well loaded.

![capture du 2017-06-02 14 42 12](https://cloud.githubusercontent.com/assets/22771165/26726149/44a4812c-47a2-11e7-9356-1b55ce012161.png)

You can check my config here:

{
    "_comment": "IMPORTANT : go to the wiki page to know about options configuration https://github.com/servocoder/RichFilemanager/wiki/Configuration-options",
    "options": {
        "culture": "fr",
        "theme": "flat-dark",
        "defaultViewMode": "grid",
        "localizeGUI": true,
        "showFullPath": true,
        "showTitleAttr": true,
        "showConfirmation": true,
        "browseOnly": false,
        "clipboard": true,
        "searchBox": true,
        "fileSorting": "NAME_ASC",
        "folderPosition": "bottom",
        "quickSelect": false,
        "logger": false,
        "allowFolderDownload": true,
        "allowChangeExtensions": false,
        "capabilities": [
            "select",
            "upload",
            "download",
            "rename",
            "copy",
            "move",
            "delete",
            "extract"
        ]
    },
    "filetree": {
        "enabled": true,
        "foldersOnly": false,
        "reloadOnClick": true,
        "expandSpeed": 200,
        "showLine": true,
        "width": 200,
        "minWidth": 200
    },
    "manager": {
        "dblClickOpen": false,
        "selection": {
            "enabled": true,
            "useCtrlKey": true
        },
        "renderer": {
            "position": false,
            "indexFile": "readme.md"
        }
    },
    "api": {
        "lang": "php",
        "connectorUrl": false,
        "requestParams": []
    },
    "upload": {
        "multiple": true,
        "maxNumberOfFiles": 5,
        "chunkSize": false
    },
    "viewer": {
        "absolutePath": false,
        "previewUrl": false,
        "image": {
            "enabled": true,
            "showThumbs": true,
            "thumbMaxWidth": 64,
            "extensions": [
                "jpg",
                "jpe",
                "jpeg",
                "gif",
                "png",
                "svg"
            ]
        },
        "video": {
            "enabled": true,
            "extensions": [
                "ogv",
                "mp4",
                "webm",
                "m4v"
            ],
            "playerWidth": 400,
            "playerHeight": 222
        },
        "audio": {
            "enabled": true,
            "extensions": [
                "ogg",
                "mp3",
                "wav"
            ]
        },
        "iframe": {
            "enabled": true,
            "extensions": [
                "htm",
                "html"
            ],
            "readerWidth": "95%",
            "readerHeight": "600"
        },
        "opendoc": {
            "enabled": true,
            "extensions": [
                "pdf",
                "odt",
                "odp",
                "ods"
            ],
            "readerWidth": "640",
            "readerHeight": "480"
        },
        "google": {
            "enabled": true,
            "extensions": [
                "doc",
                "docx",
                "xls",
                "xlsx",
                "ppt",
                "pptx"
            ],
            "readerWidth": "640",
            "readerHeight": "480"
        },
        "codeMirrorRenderer": {
            "enabled": true,
            "extensions": [
                "txt",
                "csv"
            ]
        },
        "markdownRenderer": {
            "enabled": true,
            "extensions": [
                "md"
            ]
        }
    },
    "editor": {
        "enabled": true,
        "theme": "default",
        "lineNumbers": true,
        "lineWrapping": true,
        "codeHighlight": true,
        "matchBrackets": true,
        "extensions": [
            "html",
            "txt",
            "csv",
            "md"
        ]
    },
    "customScrollbar": {
    	"enabled": true,
    	"theme": "inset-2-dark",
    	"button": true
    },
    "extras": {
        "extra_js": [],
        "extra_js_async": true
    },
    "url": "https://github.com/servocoder/RichFilemanager",
    "version": "2.4.0"
}

I look forward to your response.

**Comment by servocoder** [comment]
Perhaps ViewerJS can't handle your particular PDF file internally. Have you tried other PDF files?

**Comment by FlorentYaicene** [comment]
Thank you for your response.

Yes I tried to see other PDF files, but I have the same issue.
I also tried to put the same files in your example page test at this address http://fm.devale.pro/ and it works properly

**Comment by servocoder** [comment]
Do you experience this issue locally?
What is your OS?
Have you tried it unloaded to server?

**Comment by FlorentYaicene** [comment]
I access locally to my Apache server which is running on a virtual machine.
Files are shared in NFS from locally to my virtual machine.

both are on Ubuntu Trusty(14.04).

Yes, I tried to put a file directly in the folder which is reach by FileManager but I have the same issue.

**Comment by servocoder** [comment]
Have no idea for your case.
Please, leave feedback if you will manage to handle the issue.

**Comment by FlorentYaicene** [comment]
Yes, I've just solved the problem.

I don't know if it has been any incidence but I moved out packages from the vendor when I got this issue.

So, I reinstall packages and organized it in this way.
-- vendor
   -- servocoder
       --richfilemanger
       --richfilemanager-php
And it's work.

Thank you for taking time, have a nice day !

**Comment by servocoder** [comment]
Thanks for your feedback.
