### ISSUE TITLE
Upload svg as image

### ISSUE THREAD

**Issue by howdu** [servocoder/RichFilemanager#193]
Unable to upload svg as an image without changing regex:
`$this->options['image_file_types'] = '/\.(svg|gif|jpe?g|png)$/i';`

I thought it would check the upload->restrictions from json. Also unable to overwrite 'image_file_types' in json options.

**Comment by leonel-lordford** [comment]
Have you checked connector's config options as well ?

**Comment by howdu** [comment]
Yes svg exists there also. It was the regex for image_file_types which was causing this issue.

**Comment by servocoder** [comment]
The regex come from original uploader script.
Not sure why SVG type was omited. This should be well explored.

Do SVG files upload smoothly for you now?
Don't you experience issues with thumbnail files for uploaded SVG images?
