### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by ferenczAndras** [servocoder/RichFilemanager#2]
Me again. The rename function has a bug. When you rename a file, using php connector it does it well, but sadly it is called the connector twice, so the message on site is shown that the file dose not exist. If you refresh the page, the file will be show with the new name. 
So the error is that it shows a message, that the file dose not exists instead of showing a succesfull message.

**Comment by servocoder** [comment]
Hm, I can't reproduce it neither on my local machine nor at http://fm.16mb.com/

**Comment by servocoder** [comment]
Have you found out the reason of the issue?

**Comment by ferenczAndras** [comment]
I followed the network view on Chrome. It happens only in subfolders. I had no time to see exactly what it is, but I am ganna go deeper to see it.

**Comment by servocoder** [comment]
Ok, keep an eye on it. I'm not able to reproduce this issue with subfolders either. Perhaps it depends on your config or environment. Looking forward your feedback.

**Comment by servocoder** [comment]
Hi @ferenczAndras 
A few updates have been released since the moment you had opened this issue.
Could you check the latest version and share your feedback?

**Comment by ferenczAndras** [comment]
Hy @servocoder. I will update my project soon, and will message you. I had this issue since i opened this only twice..

**Comment by ferenczAndras** [comment]
I close the issue, because i did not find it since the last version is up!
