### ISSUE TITLE
thumbs not working when using s3 storage

### ISSUE THREAD

**Issue by cornernote** [servocoder/RichFilemanager#200]
I have s3 storage working, awesome!

However the thumbs don't display :(

If I view thumb img src, it points here:

```
https://example.com/connectors/php/filemanager.php?path=%2Ftest.png&mode=getimage&thumbnail=true&time=1499824543091
```

When I view it directly it renders this HTML:
```
<h2>Server error: NOT_ALLOWED_SYSTEM</h2>
```

In apache log I get this:

```
PHP Warning:  imagepng(): Unable to open 's3://my-bucket/_thumbs/test.png' for writing: No such file or directory in /home/me/fm/connectors/php/vendor/servocoder/richfilemanager-php/src/Repository/BaseUploadHandler.php on line 806
```

So it seems the thumb script isn't handling the thumb on S3.  Is this because I missed something in the setup?

**Comment by servocoder** [comment]
Thanks for reporting. I will take a look this issue in the coming days.

**Comment by servocoder** [comment]
Ok, I found an issue that affected LOCAL storage path when dealing with image thumbnails and fixed it, you can reinstall php connector for RFM. However, based on  the apache log I can suppose that your problem may not be covered with my fix. If you will continue experience the issue after the update of PHP connector then provide the content of your `filemanager.php` file. Don't forget to hide your AWS credentials.

**Comment by servocoder** [comment]
Closed due to inactivity
