### ISSUE TITLE
Cannot read property 'policy' of undefined

### ISSUE THREAD

**Issue by dsu** [servocoder/RichFilemanager#201]
I'm using Java connector with the [default configuration ](https://github.com/servocoder/RichFilemanager/blob/master/connectors/java/src/main/resources/filemanager.config.default.properties) . 

When I upload a file I get a JS error. It seems like the connector is not providing all the data necessary. 
`config.security.extensions` is undefined.
```
filemanager.js:3839 Uncaught TypeError: Cannot read property 'policy' of undefined
    at HTMLButtonElement.<anonymous> (filemanager.js:3839)
    at HTMLButtonElement.dispatch (jquery-1.11.1.min.js:3)
    at HTMLButtonElement.r.handle (jquery-1.11.1.min.js:3)
```

```
if(config.security.extensions.policy == 'ALLOW_LIST') {
   ....
```

Server response for initialization:
```
{"data":{"attributes":{"config":{"security":{"editRestrictions":["txt","csv","md"],"allowNoExtension":false},"upload":{"restrictions":["jpg","jpe","jpeg","gif","png","svg","txt","pdf","odp","ods","odt","rtf","doc","docx","xls","xlsx","ppt","pptx","csv","ogv","avi","mkv","mp4","webm","m4v","ogg","mp3","wav","zip","rar","md"],"fileSizeLimit":16000000},"options":{"capabilities":"select,upload,download,rename,copy,move,replace,delete,edit","culture":"en","charsLatinOnly":false,"allowFolderDownload":false}}},"id":"/","type":"initiate"}}
```

fix:

	AbstractFileManager:398
```
		JSONObject extensions = new JSONObject();
		extensions.put("restrictions", propertiesConfig.getProperty("upload_restrictions").split(","));
		extensions.put("policy", propertiesConfig.getProperty("upload_policy"));
		security.put("extensions",extensions);
```

**Comment by servocoder** [comment]
I have merged updates for JSP connector, try it please. Also note that RFM provides 2 different Java connectors (/java and /jsp), which eventually will be joined into the one, but for now you could try both.

In case of further issues you should address your requests to the maintainers of these connectors:

JSP - @gmkll (have been just updated)
JAVA - @fabriceci
