### ISSUE TITLE
Default files location ASHX connector

### ISSUE THREAD

**Issue by samcov** [servocoder/RichFilemanager#206]
For some reason the ashx connector does not find the default files location, "userfiles".

Is there a way to set the default location through any config?

**Comment by servocoder** [comment]
ASHX connector is outdated. If you feel strong enough in ASHX  you can update ASHX connector or write it from scratch. Anyhow I would appreciate if you take a lead on any of connector and become a maintainer. Let me know if you need any help.

**Comment by servocoder** [comment]
Closed due to inactivity.
