### ISSUE TITLE
Culture should be moved to the server side

### ISSUE THREAD

**Issue by fabriceci** [servocoder/RichFilemanager#212]
The culture should be decided by the server not the client:

- to format the date according to the culture (server side),
- to handle multi-language websites, culture should be set dynamically (server side).

**Comment by servocoder** [comment]
I disagree. Culture won't be moved to the server-side.

Date formatting is not a such important feature to do this. Eventually date formatting can be performmed at the client-side as well.

I don't mind to provide an ability to override culture option from the server-side on "initiate" API method, but that's all.

**Comment by servocoder** [comment]
Closed for the time being.
