### ISSUE TITLE
Change connectorUrl from filemanager.init.js isn't possible

### ISSUE THREAD

**Issue by kverfaille** [servocoder/RichFilemanager#217]
When specifying connectorUrl through the filemanager.init.js it is ignored during configuration.

This is caused by the configure function that loads both default & user settings, without taking into account the options provided from filemanager.init.js. Take a look at the code snippet I added below.

```
var configure = function() {
		return $.when(loadConfigFile('default'), loadConfigFile('user')).done(function(confd, confu) {
			var config_default = confd[0];
			var config_user = confu[0];

			// remove version from user config file
			if (config_user !== undefined && config_user !== null) {
				delete config_user.version;
			}

                        /******************* Issue demo *********************/
                        console.log("filemanager.init.js config: ");
			console.log(fm.settings.api.connectorUrl);
			alert("ConnectorUrl already available");
                        /*****************************************************/
			// merge default config and user config file
			config = $.extend({}, config_default, config_user);

                        /****************** Fix suggestion ******************/
                        /* Add pluginOptions to the config (not settings to avoid defaults) */			
			config = $.extend({}, config_default, config_user, pluginOptions);
                        /*****************************************************/

                        // setup apiConnector
			if(config.api.connectorUrl) {
				apiConnector = config.api.connectorUrl;
			} else {
				var connectorUrl = location.origin + location.pathname;
				var langConnector = 'connectors/' + config.api.lang + '/filemanager.' + config.api.lang;

				// for url like http://site.com/index.html
				if(getExtension(connectorUrl).length > 0) {
					connectorUrl = connectorUrl.substring(0, connectorUrl.lastIndexOf('/') + 1);
				}
				apiConnector = connectorUrl + langConnector;
			}
		});
	};
```

Regards,
Kevin

**Comment by servocoder** [comment]
Hi Kevin.

What is your reason to set `connectorUrl` in `filemanager.init.js` file?
The right place for `connectorUrl` option is `filemanager.config.json` file.

I don't want to allow too many places to set configuration option because it will cause a mess with options eventually.

**Comment by servocoder** [comment]
The reason of splitting config into 2 files is that you are not able to define a complex structures in JSON file, like functions. So `filemanager.init.js` is intended for keeping parameters which are required on plugin initialization step and callback functions. All other stuff should be defind in the `filemanager.config.json` file.

**Comment by servocoder** [comment]
I have updated wiki article that details configuration options, added info about configuration files:
https://github.com/servocoder/RichFilemanager/wiki/Configuration-options#client-side-configuration

Hope it's much clearer now.
Let me know if you will manage to solve the problem.

**Comment by kverfaille** [comment]
Hi Pavel,

Well the main reason is that there are no options available (as far as I know) to load different config files for different frontend pages.

My situation:

I have a websiteroot/filemanager folder that was installed through composer. Everything works out of the box after setting some configuration. Note that I removed the entry from index.html that loads the filemanager.init.js. Admins just go to website/filemanager/index.html and they can start managing the file tree. So far so good.

Now I want to expose the folder structure as a readonly browser for visitors. So I created a new page under my websiteroot (outside the filemanager folder) and I made sure that filemanager.init.js does get loaded (I could do it directly on the page too, but the problem would remain). Then I changed the baseURL in filemanager.init.js this way all files get correctly loaded from the filemanager folder, but also the config gets loaded from there, which causes the connectorURL to be wrong. By loading the extra filemanager.init.js I thought I would be able to change that URL but apparently not :-) (And the same applies for setting it on the component itself).

Therefore, I thought there would be a certain option overflow order. First, the options set on the component itself, then init.js, then user and finally default. However, after inspecting the code it seems this was not the case, so hence this post. I wanted to be sure this was intended or not.

Any suggestion on how to implement my usecase according the intended use of this framework?

Regards,
Kevin

**Comment by servocoder** [comment]
> Then I changed the baseURL in filemanager.init.js this way all files get correctly loaded from the filemanager folder, but also the config gets loaded from there, which causes the connectorURL to be wrong.

Why do you get a `connectorURL` value wrong?
Once you set it as absolute URL it will be constant.

Even if you want different config files for different frontend pages the `connectorURL` will remain the same for all pages, isn't it?

Perhaps I missed something. It would be good if you provide some code snippet and url examples which can help to understand the situation better.

> First, the options set on the component itself, then init.js, then user and finally default.

This is correct, but init.js doesn't intended to carry configurations options, this is the case.
I can think on some workaround, but first I want to understand your situation and reproduce it.

**Comment by kverfaille** [comment]
OMG you are absolutely right, this solves my issue.

The confusion comes from my first attempt to include your filemanager in our higher-level framework for usage on multiple websites. In that case I cannot configure a hard-coded absolute URL.

Our framework is checked out in the PHP includes directory, so multiple sites would use the same config.  Each site can configure our framework to have a different root folder.
Eg: 
- site1.domain?framework_router=filemanager_connector (would expose "site1-dir/files")
  - Required connector url for site1.domain/browser.html (outside framework & custom per site) =>
    - site1.domain?framework_router=filemanager_connector
- site2.domain?framework_router=filemanager_connector (would expose "site2-dir/files")
  - Required connector url for site1.domain/browser.html (outside framework & custom per site) =>
    - site2.domain?framework_router=filemanager_connector

In such a situation the correct connectorURL can be generated for the admin pages (which are part of the framework), but the (sub-) site pages (non-admin) require a different connectorURL.

So don’t bother, I guess it is too specific for our situation. I will adapt the JS once I will walk that path of integrating into our framework again...
Thanks for the help,
Kevin

**Comment by servocoder** [comment]
Sure, no problem!
Glad you managed to solve the case.
