### ISSUE TITLE
PHP Parse error: syntax error Macroable.php

### ISSUE THREAD

**Issue by forumarji** [servocoder/RichFilemanager#218]
Hi, I am using php 5.4.16 version. All is fine but I am getting below error, please check
PHP Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
in /RichFilemanager/connectors/php/vendor/illuminate/support/Traits/Macroable.php on line 56, 78
Thank you.

**Comment by servocoder** [comment]
Indeed, some of dependent libraries require php v 5.5.9
I have to check whether it's possible to rollback them to an earlier version without loss of functionality

**Comment by forumarji** [comment]
Okay, thank you. Please check and confirm. Its better to maintain same compatibility for the project, otherwise we stuck with it.  Total application is not loading due to this issue and showing initial error. For now to solve this issue, I just commented lines 55,56,57 & 77,78,79, then application working fine.

**Comment by servocoder** [comment]
Solved within related issue. Minimum required PHP version is set to >= 5.6.4
