### ISSUE TITLE
Add unzip functionality to FileManager

### ISSUE THREAD

**Issue by servocoder** [servocoder/RichFilemanager#22]
Original request by @SlitYahoo and discussion is [here](https://github.com/simogeo/Filemanager/issues/506)

**Comment by fabriceci** [comment]
I thinks it's a good idea.

In addition, I propose to add the ability to zip a folder in the contextual menu.

To handle the security issues for the unzip, a possible solution is the add a constructor with an array of roles. By default a user has all roles. When the file manager start, It do an extra request to get the user roles.

**Comment by simogeo** [comment]
@servocoder : what about unzipping files on `/tmp/` repo (sys_get_temp_dir ()) and check files individually to remove unwanted before copying the folder into the desired location ?

**Comment by servocoder** [comment]
Splendid idea, we should try it definitely when it comes to implementation. Thanks.

**Comment by ningappa** [comment]
Any Update on this?

**Comment by servocoder** [comment]
not yet, going to take care of this in the coming releases

**Comment by ningappa** [comment]
@servocoder  thanks 👍 I'll be waiting

**Comment by servocoder** [comment]
I have just commited "unzip" branch that includes `extract` feature.
@ningappa, @arvindkalbhor and other participants who are interested in this feature, please clone "unzip" branch, test it and give you feedback and bugs , if any. I'm going to releaze `extract` feature this weekend.

To extract zip archive you have to right click on zip file and select `extract` option at the bottom. Note, that `capabilities` option in JSON configuration file should include `extract` value. Extracted files will be restricted according to security setting in the `config.php` file (for PHP connector).

**Comment by ningappa** [comment]
Fantastic. It's working.

**Comment by servocoder** [comment]
Released in 2.3.2
