### ISSUE TITLE
Getting "selected" image relative path

### ISSUE THREAD

**Issue by donsingh** [servocoder/RichFilemanager#222]
Greetings!

First of all, I want to thank you for providing such an awesome plugin. I've been using it in my project for a while  now with CodeIgniter (PHP MVC) and CKEditor.

I do need help however getting the relative path of an image when I click on "SELECT".
Right now, it gives me a full path;

https://mydomain.com/assets/uploads/image1.jpg

And I'd prefer the relative path to my location folder as set in the "filemanager.php".

Something like;

"uploads/image1.jpg"

Is this at all possible? Sorry if the answer is quite obvious, Ive been looking for it in the wikis.

Thanks a lot again. Hope you can help me out.

**Comment by servocoder** [comment]
Yes, it's possible. You have to use `beforeSelectItem` callback.

1. Open your `config/filemanager.init.js` file

2. Define `beforeSelectItem` callback function, for example:

```javascript
$('.fm-container').richFilemanager({
    callbacks: {
        beforeSelectItem: function (resourceObject, url) {
            return resourceObject.attributes.path;
        },
    }
});
```

3. Profit!

For example, you can return just a name of file with `resourceObject.attributes.name` property, or any other file/folder attribute that is provided with `resourceObject` object. However I believe the `resourceObject.attributes.path` property is the one you are lookin for. And, of course, you can modify the url as you wish before return it.

**Comment by servocoder** [comment]
Follow the Wiki reference for details:
https://github.com/servocoder/RichFilemanager/wiki/Configuration-options#plugin-parameters

**Comment by donsingh** [comment]
Hello,

I have tried editing filemanager.init.js inside config. It still returns the full path of the image.

I would like to add that I am opening the filemanager two ways;

1. Using simplified text field as shown [here](https://github.com/simogeo/Filemanager/wiki/How-to-use-the-filemanager-from-a-simple-textfield)

2. Using CKEditor 3.x
```
CKEDITOR.replace( "mytextarea" ,{
          filebrowserImageBrowseUrl : '<?php echo base_url('assets/filemanager/index.html');?>'
});
````

Both methods return the full path with your suggestions.

**Comment by donsingh** [comment]
Yep. That did the trick.
