### ISSUE TITLE
Features (Copy, Cut, Paste, and Delete) Enable / Disable

### ISSUE THREAD

**Issue by renatodolce** [servocoder/RichFilemanager#223]
Hello guys, okay? I wonder if it is possible to easily enable and disable copy, paste, and delete features? Also in such specific folders ?? Thanks in advance!

**Comment by servocoder** [comment]
You could set it up in your JSON configuration file in 2 ways:

1. set `clipboard`.`enabled` option value to `false`
2. remove "copy" or/and "move" from the `options`.`capabilities` list

Both will disable clipboard features both: the buttons in the header and context menu items.
If you want to disable clipboard buttons solely, then just remove the appropriate block in the HTML template.

**Comment by chirag00757** [comment]
Is it any possible way to dynamically add and remove capabilities based on user logged in?
