### ISSUE TITLE
MODE_ERROR

### ISSUE THREAD

**Issue by renatodolce** [servocoder/RichFilemanager#224]
After configuration this code:
![image](https://user-images.githubusercontent.com/5089350/29363105-02504920-8265-11e7-909b-434724c7c417.png)
(line 107-109 and 118 it's redundant)
 
return this message:
`{"errors":[{"id":"server","code":"500","message":"MODE_ERROR","arguments":[]}]}`

Do I need to set up somewhere else??
help me please!

**Comment by servocoder** [comment]
Config seems fine. Does it work for with the default `filemanager.php` file ?

**Comment by renatodolce** [comment]
Yes

**Comment by servocoder** [comment]
1. Check whether "_materias_prontas" folder exists. If not create it or set second argument of `setRoot` method to `true`:
```
$local->setRoot("_materias_prontas", true, true);
```

2. Check permissions of the "_materias_prontas" folder

**Comment by renatodolce** [comment]
1. I already tested with the default folder and mine, both same error.
2. What would be advisable and safe?

**Comment by servocoder** [comment]
It depends on RFM config and your web server setup.

To test if permissions are the reason of your issue set the whole folder to 777 and then reduce them gradually to reach the optimal configuration.

**Comment by renatodolce** [comment]
Another thing I noticed, after you run the composer, did the files and folders become symbolic link?

![image](https://user-images.githubusercontent.com/5089350/29379750-d7983fbe-8299-11e7-845d-45fb921eb762.png)

**Comment by servocoder** [comment]
Files and folders shouldn't be symlinks.
Try to reinstall RFM from scratch.

https://github.com/servocoder/RichFilemanager/wiki/PHP-connector

**Comment by renatodolce** [comment]
I deleted everything and did it again, I checked the permissions, I even put the log to see if it helps, but it returns the same thing 😒
`Error code: MODE_ERROR`

**Comment by servocoder** [comment]
Not sure what is the reason of the problem.

Btw, what is your web server and PHP version?

**Comment by renatodolce** [comment]
Apache 2.4.6 and PHP 7.0.21

**Comment by servocoder** [comment]
Hmm, so strange. I have no ideas at the moment. Let me know if you will find a solution.

**Comment by renatodolce** [comment]
In the log shows this, is there something wrong? To thinking that it might be in dynamicRoot:
`$this->storageRoot: "/var/www/html/test/_materias_prontas/"
    in /var/www/html/test/sys/vendor/filemanager/connectors/php/filemanager.php:117`
`$this->documentRoot: "/var/www/html/test"
    in /var/www/html/test/sys/vendor/filemanager/connectors/php/filemanager.php:117`
`$this->dynamicRoot: "/_materias_prontas/"
    in /var/www/html/test/sys/vendor/filemanager/connectors/php/filemanager.php:117`
`Error code: MODE_ERROR
    in /var/www/html/test/sys/vendor/filemanager/connectors/php/filemanager.php:126`

**Comment by renatodolce** [comment]
I think I figured out the reason for the error, I was running filemanager.php directly and I believe it's the right call to index.html. Thank you for your attention right away.

**Comment by BuiHuyCuong** [comment]
Can you show me solution for this problem, I get message same.
Thank you!

**Comment by renatodolce** [comment]
> After configuration this code:
> ![image](https://user-images.githubusercontent.com/5089350/29363105-02504920-8265-11e7-909b-434724c7c417.png)
> (line 107-109 and 118 it's redundant)
> 
> return this message:
> `{"errors":[{"id":"server","code":"500","message":"MODE_ERROR","arguments":[]}]}`
> 
> Do I need to set up somewhere else??
> help me please!

> Can you show me solution for this problem, I get message same.
> Thank you!

@BuiHuyCuong The only difference is that in the image line 118 is commented and is working perfectly until today. Another thing that might help, I use framework and every framework has its vendors and its autoload, perhaps the directory you are accessing is in the wrong place, try debugging the var_dump / print_r code and exit, to see if it is showing right path, if not going to give this error, experience itself.
