### ISSUE TITLE
Given config file (./config/filemanager.config.json) does not exist!

### ISSUE THREAD

**Issue by renatodolce** [servocoder/RichFilemanager#226]
File exist and permission is right. What can it be?

**Comment by servocoder** [comment]
Provide screenshot that depicts files/folders tree of your project including the expanded `config` folder

**Comment by renatodolce** [comment]
![image](https://user-images.githubusercontent.com/5089350/29456677-3b1d1f4c-83ed-11e7-8274-d21aea72a992.png)

**Comment by servocoder** [comment]
Files look fine. Perhaps you include RFM in some framework or CMS that provides a custom URLs routing. If so you have to set correct `baseUrl` in your `config/filemanager.init.js` config file. You can set an absolute URL there. Follow the link for details:

https://github.com/servocoder/RichFilemanager/wiki/Configuration-options#plugin-parameters

**Comment by renatodolce** [comment]
I'm doing the tests at the root of www, so with just the baseUrl '.' Already solve, is not it?

**Comment by renatodolce** [comment]
Strange that he finds the default.json, then when I change the folder to some that does not exist there he complains that he does not find the 2 config.json, then I go back to the right folder he only complains of config.json

**Comment by renatodolce** [comment]
![image](https://user-images.githubusercontent.com/5089350/29461144-046ebeec-8401-11e7-9df4-d48ac8919ebe.png)
I found the error, it was a comma at the end of an array inside the json, as I had commented some feature that I will not allow on my system. Thank you in advance for your attention and willpower.

**Comment by abubasil70** [comment]
Hi
Um instead of putting unsupportedCharsReplacement , please consider adding support for utf8 languages by using :
$name=iconv("somecharset","utf8",$name);   //somecharset=windows-1256
