### ISSUE TITLE
Questions and Doubts (Multi dir, create folder and etc)

### ISSUE THREAD

**Issue by renatodolce** [servocoder/RichFilemanager#227]
1. I'm sorry for not thanking you previously, but Congratulations on the tool, it's amazing!
2. I would like to know if you have how to use multiple directories as root? If you have not like, I suggest as a new feature ;-)
3. Can you disable folder creation?

**Comment by servocoder** [comment]
1. Thank you.
2. No, this feature isn't supported and not planned.
3. I will think over it.

**Comment by renatodolce** [comment]
2. Ok, Do you have plans to do this? Or do you have any suggestions on where to develop this? 
3. I asked if you can disable folder creation and in fact it was to be: how to disable folder creation and where to do this? :-)

**Comment by renatodolce** [comment]
4. What permission do you need to search? Because nothing happens to me. Does it search from the root or only in the current folder?

**Comment by servocoder** [comment]
2. No, but you can create 2 or more folders infide user folder by yourself. Actually I can't get the idea behind multiple directories as root. What's the point of this?

3. You can't remove "create folder" menu item now. I will add this to capabilities list, so you will bw able to disable it.

4. Right. The search is for the client-side solely, and it's limited with currently viewed folder. Not very useful thing at this point.

**Comment by renatodolce** [comment]
2. I have more than 1 directory as root, for now my supervisor will do in apache as a virtual directory, there already will solve, but if it were possible, nor would it be necessary to create these virtual directories.
3. For now I just commented in JS the places that call this feature and worked, but if you give to disable it will be great and practical.
4. I understood, but when you type something to look for, nothing happens, strange ...

**Comment by servocoder** [comment]
1-5. Currently not supported. There are plans for (possible) integration of [jsTree](https://www.jstree.com/) plugin into the project for better filetree management. This may help to solve some or all things that you requested. Anyhow this is not a primary concern at the moment.

6-6. At the moment date formatting happens at the server-side, so it's not possible to modify its format or language translations. This should be fixed. Date should be formatted at the client-side. I will remain this ticket open until this particular issue fixed.

**Comment by servocoder** [comment]
Released in v2.7.0
