### ISSUE TITLE
Content filter does not work on list view

### ISSUE THREAD

**Issue by simogeo** [servocoder/RichFilemanager#228]
hey @servocoder, hope you're fine !

Have seen the recent work on RFM. Great.

Here a spotted bug on content filter with list view (works well with grid view !). Tested on your demo server. See the screenshot below : 

![filter-bug](https://user-images.githubusercontent.com/154323/29564728-509d6aa8-8743-11e7-859f-c832a60075b3.png)

Have a good day

**Comment by servocoder** [comment]
Hi @simogeo !

Yeah, it has been reported already in #225, thanks for keeping your eyes peeled

**Comment by simogeo** [comment]
Sorry for duplicate !
