### ISSUE TITLE
Unable to perform initial request to server

### ISSUE THREAD

**Issue by jimhtwong** [servocoder/RichFilemanager#229]
I install in CentOS 5 with PHP 5.4. I rename 2 configuration files. When I access, it says "Unable to perform initial request to server." any idea?

**Comment by servocoder** [comment]
1. Try to check folders permissions

2. It was found that some depencies require PHP 5.5.9 #218

3. Debug your code and catch the issue yourself.

Don't forget to leave feedback once your issue has been solved

**Comment by godtrix** [comment]
Hi, i've the same issue here. what folder permission has to change?

**Comment by githubertus** [comment]
Most likely you missed to install the connector via 'composer update'.
I found myself confronted with the same message, and perhaps the installing instructions could be a little be more straight foreward by moving the really relevant instructions from the connector to main app?

**Comment by servocoder** [comment]
> Filemanager is designed to interact with a number of programming languages via connectors. The actual connectors are: PHP, Java, ASHX, ASP, NodeJs & Python 3 Flask.

For this very reason PHP connector with all relevant instructions will remain in the separate repository. The process is well described in the [Deploy and setup](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) wiki article, and the reference to PHP connector is provided there. I believe it's quite straightforward.
