### ISSUE TITLE
Undefined index: content-type in 

### ISSUE THREAD

**Issue by Chintan7027** [servocoder/RichFilemanager#232]
I am using S3 Storage for File manager, while clicking on object for downloading file it throws me error of:

**development.ERROR: ErrorException: Undefined index: content-type in /Applications/MAMP/htdocs/s3tree/app/filemanager/vendor/servocoder/richfilemanager-php/src/Repository/S3/ItemModel.php:284**

**Comment by servocoder** [comment]
This ticket was opened a long time ago, anyway I inform you that PHP connector, and especially S3 storage, has been greatly reworked and I would ask you to update php connector via composer and try to reproduce the bug once again.
