### ISSUE TITLE
"type" parameter on url disturb the upload capability

### ISSUE THREAD

**Issue by sorryjack** [servocoder/RichFilemanager#237]
Hello, its a great FM I ever met,
BTW I use version 2.0.3, I use "type=images" parameter on url when calling the FM via tinymce. It works well, filter out all file displayed but images. Unfortunately when I upload any files including images file, it said that the type of file I upload is restricted. 
**SS 1: filterout non images file**
![screenshot_211](https://user-images.githubusercontent.com/6811578/30518637-ec9b400a-9bad-11e7-933c-89661ca4841e.png)
**SS 2: upload failed**
![screenshot_212](https://user-images.githubusercontent.com/6811578/30518640-fc644720-9bad-11e7-93c6-97535ea9a953.png)

thank you.

**Comment by servocoder** [comment]
why don't you try to use the latest version?

**Comment by topanalfa** [comment]
gan @sorryjack , awal setting buat richfilemanager di nodejs gimana? (saya masih baru main nodejs)
ikutin step by stepnya dimana?

**Comment by sorryjack** [comment]
@servocoder well,,, I tried but, its too tricky for me to implement the latest version, so, I stick on the version I am using. I just remove the "type" parameter. 

@topanalfa wah gan,, saya belum belajar node.js nya.. saya pake php. maaf saya tidak ada referensinya.

**Comment by servocoder** [comment]
I see. Unfortunately I don't support old versions.
Thanks for your interest to RFM.

**Comment by sorryjack** [comment]
Yea I got it man. thanks for your works.
