### ISSUE TITLE
Server error - filenames with Greek characters

### ISSUE THREAD

**Issue by freris** [servocoder/RichFilemanager#238]
Hello !

I have a problem with filenames with Greek characters. My server is Apache 2.4 and running on Windows 7 SP 1.

In case that a folder contains a file with Greek letters, got a server error message. When rename the file with Latin characters - all is OK.

Any help is appreciated.
Thank you

**Comment by javicaballero** [comment]
I have the same issue with accents (á, é, í, ó, ú) and ñ. Only occurs in Windows. In Linux works.

**Comment by servocoder** [comment]
I found a bug in the latest version 1.1.0 of PHP connector, that has been released 2 days ago. It fails on every rename operation no matter what chars are in the name. However other operations work good. Please, specify what is your case, and what exact operations fail if you are sure that it happens not only on rename operation.

**Comment by javicaballero** [comment]
If one file have a special character in the selected folder it doesn't show any files at all, so we cannot select, rename or delete it. I use the latest version of PHP connector.
![error](https://user-images.githubusercontent.com/6868879/31960963-bef65ccc-b8cf-11e7-83cb-29f6561cf7a2.png)

**Comment by servocoder** [comment]
Interesting. I'm not able to reproduce this issue on Windows, despite the fact that I included the chars that you listed in filenames. Could you attach a file that should cause the error?

**Comment by servocoder** [comment]
As I said before I wasn't able to reproduce the issue with Greek characters that you mentioned. The problem may also depend on your specific server configuration.  

@freris. @javicaballero please, attach file(s) with problematic name(s) to this ticket that you can't handle with RFM. Otherwise I will have to close the issue.

**Comment by freris** [comment]
Hi servocoder, 

The files had Greek filenames such as  Λιστα.txt or Κατάλογος.xls  or Φωτογραφία-2.jpeg.  And the result is as javicaballero says. Using PHP 5.3 or 7.0 , same results.

Thank you and Have a nice day
