### ISSUE TITLE
can't upload audio files

### ISSUE THREAD

**Issue by anhro92** [servocoder/RichFilemanager#239]
Hello!
I try to upload audio files with mp3 extension but i got a error message.

**Comment by hou0122** [comment]
Please provide error message.

**Comment by anhro92** [comment]
you can upload and got a error message in http://fm.devale.pro/

**Comment by servocoder** [comment]
I fixed an error at http://fm.devale.pro/
The php.ini file was misconfigured.
Thanks for the report.

Let me know if you catch the same error at your server.
