### ISSUE TITLE
Feature request: roles management (multi-profile)

### ISSUE THREAD

**Issue by fabriceci** [servocoder/RichFilemanager#24]
I think it will be nice to have a simple roles management.

Suggestion:

We can add a new constructor with an array of roles as extra parameters. By default, if nothing is provided (actual case) a user has all roles.

When the file manager start, it does an extra request to get the user roles to the connector. (It does not seem too hard to implement because the logic is already implemented with the "has_capability" functions.)

This will real plus in a CMS usage or when you have different profiles of users that use the file manager in your app.

**Comment by servocoder** [comment]
What is the purpose of that?
If you want to disable/enable filemanager for some users depending on their role you could implement this in [filemanager.php](https://github.com/servocoder/RichFilemanager/blob/master/connectors/php/filemanager.php)::auth()

**Comment by fabriceci** [comment]
To be more granular.

If your app has x group of users and you want to give different rights, for example :

- User : can access to the FM, select or download a file.
- admin :  all above +  upload/delete files + zip
- super admin : all above + unzip files 

(by default, actual cases, have all roles )

**Comment by servocoder** [comment]
I see now, may be interesting feature.
Do you want to implement it with a new PR?

**Comment by fabriceci** [comment]
Yes, I will do that but before I finish my java connector ( maybe merge with the work of @gmlk ) and then see if I can improve the visual with a new theme ( the true defect of the plugin for now in my opinion)

**Comment by servocoder** [comment]
Great!
Concerning to PR #21, I would like to ask you to communicate with @gmkll. I prefer that one of you take a lead on implementing Java connector to not create a various PR for that purpose. Create new issue if you need to discuss all the things with him.

**Comment by servocoder** [comment]
Of course if you both work on the same connector.

**Comment by fabriceci** [comment]
Connectors are very close, but I can't use the @gmkii without modifications. I will open 
in the coming days a new issue and discuss with him to see what we will do.

**Comment by servocoder** [comment]
That's would be great.
He, also made a number of modifications in JS file, which I have to review anyway.

**Comment by jlaustill** [comment]
I have a similar need that I will be implementing into my node connector.  In my case, I need to block access to files based upon user roles.  So my root folder will have folders for each role, and each request will verify that the user has the role that matches the folders name or they will be denied.  This way I can have groups that have private files.  I will write it in such a way that it can be easily ignored, aka, opt-in.  Node uses a standard user configuration that roles can be added to, I'm not sure how it would work in other connectors except .net.  I did this to my current .net connector, but it was horribly messy and non-standard so I never even thought about passing it back as a pull request.  My node connector I will, though. I will go to lengths to make it standard compliant and clean.

**Comment by servocoder** [comment]
Solved with the RichFilemanager release v2.0.0
See "setAllowedActions()" method called from [filemanager.php](https://github.com/servocoder/RichFilemanager/blob/master/connectors/php/filemanager.php). Feel free to reopen the issue if you have any advanced ideas on this subject.
