### ISSUE TITLE
Preview Not Working any single type of file when connect with S3

### ISSUE THREAD

**Issue by vineetdikonia** [servocoder/RichFilemanager#242]
I implemented this package in my applications, everything is working fine on local storage but when I am connected it by S3 bucket the preview section is not working. I have attached a screenshot for your informations and below is the url which show in the preview section.
http://localhost/user_folder/Testing_FileManager/po_4079.PNG?time=1507534419214

![rich filemanager 2017-10-09 12-59-16](https://user-images.githubusercontent.com/13980482/31328400-8746798a-acf2-11e7-94cf-f01698733855.png)

**Comment by servocoder** [comment]
You should set `viewer.absolutePath` to `false` in your JSON configuration file. In the next release I will set it by default for S3 connector.

**Comment by servocoder** [comment]
Released in the v1.1.0 of the PHP connector. Use `composer update` and try again.
