### ISSUE TITLE
Users access control to directories

### ISSUE THREAD

**Issue by maudam** [servocoder/RichFilemanager#243]
Hi,
 i'm testing RFM to browse some directories on my web server.

Requirements:
User 1 have to access read and write all directories
User 2 only his directory
User 3 only his directory

Structure: (can be two)

/ sharing root
-----/User1 dir
-----/User2 dir
-----/User3 dir

or

/ sharing root
-----/User1 Dir
----------/User2 dir
----------/User3 dir

I cannot set filesystem permissions because files have to be readable and writeable from a sync app i use to sync files between computers.

What's the best way to accomplish this result ?
Do i need additional software like an authentication method  or i can solve with htaccess files or similar method ?

Thanks in advance.

**Comment by servocoder** [comment]
If you use PHP connector you can write your own rules based on the filepath. See `fm_has_read_permission` and `fm_has_write_permission` in the [filemanager.php](https://github.com/servocoder/RichFilemanager/blob/master/connectors/php/filemanager.php)
