### ISSUE TITLE
Make Window Close When File is Selected

### ISSUE THREAD

**Issue by stevelittlefish** [servocoder/RichFilemanager#246]
I'm using the filemanager as a file browser for CKEditor. With the old version of Filemanager (i.e. from before RichFilemanager), when I selected an image with the tick icon, the image URL would be copied into the image widget and the filemanager window would automatically close.  With the new version, the URL is still copied but the window doesn't close.

Is this configurable?  I would very much like to get the old behaviour back as it's confusing to the user that the window doesn't close and they think it hasn't worked.

**Comment by servocoder** [comment]
It should work exactly like you describe. I will check it and give you a feedback soon.

**Comment by servocoder** [comment]
Ok, I have checked it and it works as expected.
You can check it out at the demo page (it isn't completed yet though): http://fm.devale.pro/demo/index.html

Copy-paste of the implementation code that you will be able to find at the source code of demo page:

```javascript
/*---------------------------------------------------------
 CKEditor init example
 ---------------------------------------------------------*/
CKEDITOR.replace('editor_ckeditor');
CKEDITOR.on('dialogDefinition', function (event)
{
	var editor = event.editor;
	var dialogDefinition = event.data.definition;
	var dialogName = event.data.name;

	var cleanUpFuncRef = CKEDITOR.tools.addFunction(function ()
	{
		// Do the clean-up of filemanager here (called when an image was selected or cancel was clicked)
		$('#fm-iframe').remove();
		$("body").css("overflow-y", "scroll");
	});

	var tabCount = dialogDefinition.contents.length;
	for (var i = 0; i < tabCount; i++) {
		var browseButton = dialogDefinition.contents[i].get('browse');

		if (browseButton !== null) {
			browseButton.hidden = false;
			browseButton.onClick = function (dialog, i)
			{
				editor._.filebrowserSe = this;
				var iframe = $("<iframe id='fm-iframe' class='fm-modal'/>").attr({
					src: './../index.html' + // Change it to wherever  Filemanager is stored.
					'?CKEditorFuncNum=' + CKEDITOR.instances[event.editor.name]._.filebrowserFn +
					'&CKEditorCleanUpFuncNum=' + cleanUpFuncRef +
					'&langCode=en' +
					'&CKEditor=' + event.editor.name
				});

				$("body").append(iframe);
				$("body").css("overflow-y", "hidden");  // Get rid of possible scrollbars in containing document
			}
		}
	}
});
```

**Comment by servocoder** [comment]
Closed. Let me know if you continue experience the issue.

**Comment by stevelittlefish** [comment]
I've got this working now.

I didn't realise I had to do that stuff manually - in the old FileManager it used to close automatically, even when not using and iframe.

Thanks for your help!
