### ISSUE TITLE
Feature Request: Simple File Uploads

### ISSUE THREAD

**Issue by stevelittlefish** [servocoder/RichFilemanager#247]
Something that would be useful, and I don't know how much effort this would be to do, would be if there was a configuration option to simplify the upload feature.  At the moment, when I click upload, a window pops up with some buttons and a target to drop files.  To open a file browser I then click on the window, select my files and click "ok".  After that I must click "upload" to upload the files.

Would it be possible to add a simple upload mode, where clicking "upload" takes you straight to the file browser, and then when you click "ok" it uploads the file?  The upload feature is the main thing that causes confusion amongst my users, and normally they only want to upload a single file anyway.

**Comment by servocoder** [comment]
Have you tried to set `upload.multiple` value to `false` in your "filemanager.config.json"? I think that is what you are looking for.

**Comment by stevelittlefish** [comment]
I hadn't tried that, and it's very close to how I'd like it to work.  I still think this is a little bit confusing though.

At the moment you have to press the '+' button to select a file, which opens the file browser, and then you have to click upload.  It would be a lot better if the '+' button and filename field were not there, and you just pressed upload to open the file picker.  Then, after selecting a file it could just automatically upload.

Does that make sense?

**Comment by servocoder** [comment]
Yeah, this may be the case. It really looks like redundant step. I will think of your suggestion.

**Comment by servocoder** [comment]
I removed all redundant steps and elements. Check the last commit out and let me know whether this what you expected. Thanks.

**Comment by servocoder** [comment]
Released in v2.6.3

**Comment by stevelittlefish** [comment]
This is absolutely perfect.  Thanks so much for your help - I appreciate it!
