### ISSUE TITLE
enhancement : don't block the ui when an operation is succeed

### ISSUE THREAD

**Issue by fabriceci** [servocoder/RichFilemanager#25]
When you successfully do something (delete a file, add a file) there is a success message box that blocks the ui and force to click on the OK button (and just after the fm refresh the ui).

It will be better to have instead an instant refresh and a notification that disappears automatically after x seconds without blocking anything. (something like [that](http://ned.im/noty/#/about)).

**Comment by servocoder** [comment]
Noty is a nice plugin. It's ok for me, but I believe we have to force user to click OK button for some important messages (errors e.g.) to be sure he got the message. Anyway, this enhancement should take the lowest priority.

**Comment by simogeo** [comment]
@fabriceci : set `showConfirmation` to  `false` [in config file](https://github.com/servocoder/RichFilemanager/blob/master/scripts/filemanager.config.default.json#L12).

**Comment by servocoder** [comment]
If I got @fabriceci right, he wants to display notifications with the help of `showConfirmation`, but to make them less obtrusive. They are not supposed to block the page and dissapear after N seconds. The Noty plugin is intended for a such behavior. But I doubt whether this is an appropriate behavior for an important messages, like errors etc. What do you think @simogeo ?

**Comment by simogeo** [comment]
First, I wanted to be sure @fabriceci knew about `showConfirmation` option.

Noty is nice but does not handle prompting user input (which is needed and now handled with impromptu library). Both functionalities are useful and indeed, it would be great to have confirmation messages less intrusive  ... but as you said before, it does not appear to me as a priority. A switch to a library handling both prompt dialog box and notifications would be perfect. According to me, [alertify.js](https://fabien-d.github.io/alertify.js/) is more appropriate but is no more maintained ...

Right now, it would be useful to set `showConfirmation` to `false` on the default config file.

**Comment by jlaustill** [comment]
[Sweet Alert](http://t4t5.github.io/sweetalert/) is pretty awesome for blocking alerts and dialogs.  I've been using it and love it.  But I have been looking for a nonblocking alerting library for awhile with no luck.  I would like to find something that slides in alerts on the bottom right and then fades them out like facebook does, so I'll be following this conversation to see what y'all come up with :)

**Comment by simogeo** [comment]
Didn't know Sweet alert ... Nice. 
Anyone to maintain http://fabien-d.github.io/alertify.js ??? ;-))

**Comment by servocoder** [comment]
New notifications have implemented based on alertify plugin with my modifications:
https://github.com/servocoder/alertify.js

@simogeo @fabriceci @jlaustill 
Check dev branch and #41

**Comment by simogeo** [comment]
excellent ! great
