### ISSUE TITLE
Will this file manager can be integrated with AWS S3 bucket?

### ISSUE THREAD

**Issue by ganeshrc35** [servocoder/RichFilemanager#254]
Hi. I am developing a CMS app in Laravel.

I wanted the files to be uploaded in AWS S3. Please help me how to integrate with S3.

**Comment by servocoder** [comment]
Yes, it can be integrated with AWS S3 and this is declared in the repo overview, isn't it?
Have you read articles in wiki? Don't hesitate to do this:

https://github.com/servocoder/RichFilemanager/wiki

Setup for S3 storage is detailed here:

https://github.com/servocoder/RichFilemanager-PHP
