### ISSUE TITLE
Webdav support in RichFileManager?

### ISSUE THREAD

**Issue by mehrdaad** [servocoder/RichFilemanager#256]
Hi, thanks for the effort to create this library.  
Just found this library out. Is it possible to connect this library to a webDAV client?  
Is it officially supported or a connecter should be written?  
Any hint/help is appreciated.

**Comment by servocoder** [comment]
I had no experience with webDAV.
I believe it isn't supported, at least I didn't put any efforts for this.

Connectors was designed to make RFM compatible with new programming language.
If webDAV can be implemented on any language (sorry, I don't have time to learn what is webDAV), you can choose any of existing connectors.

If webDAV is a some kind of storage like AWS S3 you can use PHP connector and implement you own API and Storage classes as it's done for AWS S3 storage.

https://github.com/servocoder/RichFilemanager-PHP

**Comment by servocoder** [comment]
Closed since it's duplicated in the https://github.com/servocoder/RichFilemanager-PHP repo
