### ISSUE TITLE
How to turn off Image auto-resize

### ISSUE THREAD

**Issue by osiris22** [servocoder/RichFilemanager#257]
For some reason I can't find anywhere how to turn of Image auto-resize, can some one point this out for me please

Thank you
Alex

**Comment by servocoder** [comment]
Assume you use PHP connector.

See `images` in the server-side [configuration file](https://github.com/servocoder/RichFilemanager-PHP/blob/master/src/config/config.local.php#L172). Set `maxWidth` and `maxHeight` options to `false`, by overriding config options as described in the [Configuration](https://github.com/servocoder/RichFilemanager-PHP#configuration) section.

**Comment by osiris22** [comment]
Perfect, thank you so much, it worked.
found it under 
/connectors/php/vendor/servocoder/richfilemanager-php/src/config/config.local.php
