### ISSUE TITLE
Scripts to support quick uploads and drag n drop in ckeditor

### ISSUE THREAD

**Issue by kimkarau** [servocoder/RichFilemanager#259]
Have been searching for ways to integrate this filemanager to ckeditor for config.filebrowserUploadUrl  for quick uploads and config.uploadUrl for drag n drop without success.
Am using 

1. RFM 2.6.3 with java connector
2. ckeditor 4.7.3

Direction to what I can do or may be a new feature will be appreciated.

**Comment by servocoder** [comment]
You can't use RFM uploader without filemanager UI (if I got you right). That means there is no direct url to invoke an RFM uploader. The base implementation of CKEditor integration can be found at the [demo page](http://fm.devale.pro/demo/).
