### ISSUE TITLE
fileRoot directory can be exist outside web root folder

### ISSUE THREAD

**Issue by badsaarow** [servocoder/RichFilemanager#262]
From API document at below.
https://github.com/servocoder/RichFilemanager/wiki/API#get-download

download api just send real path to client.  
So it seems requesting to web server by real path.

If upload folder located outside web root, how can it be downloaded?
I think web service cannot access upload folder becaused 

ex)
upload folder :  /upload
web root : /htdocs/wwwroot/

to download, 
client request : filemanager?mode=download&path=/test.zip
filemanager response: /upload/test.zip
client request http://foo.bar/upload/test.zip  => it will failed, because it is outside web root.

How can I overcome this case?

**Comment by servocoder** [comment]
I can't reproduce this issue with PHP connector. It requests full connector's path and works as expected for me. Try to discover `downloadItem` method in the "filemanager.js" file. Perhaps the issue is specific for NodeJs connector.

**Comment by badsaarow** [comment]
I got it.  I'll try to with php connector.
thanks

**Comment by servocoder** [comment]
Ok, feel free to ask in case of further related questions appear.
And keep in mind that PRs are welcome, in case you will decide to improve NodeJs connector.
