### ISSUE TITLE
Modal Window disable 

### ISSUE THREAD

**Issue by Arnoost** [servocoder/RichFilemanager#263]
https://github.com/servocoder/RichFilemanager/wiki/How-to-open-the-Filemanager-from-CKEditor-in-a-modal-window

Modal Window script in the CK EDITOR blocks open dialog for the TABLE settings / And special charts things so. I tried it in the DEMO folder in Filemanager folder. The dialog box for the TABLE does not open. On screenshot. Only overlay.

Uncaught TypeError: Cannot read property 'get' of undefined

![demo folder click table icon ck editor](https://user-images.githubusercontent.com/33807014/32995287-96211b7c-cd72-11e7-8eed-3017dc65136e.png)

**Comment by servocoder** [comment]
Fixed. Check it out.

**Comment by Arnoost** [comment]
It works well in CK 4.6.3 and 4.7.3. (Last ver.) 
Thank you very much for your fix and help.
