### ISSUE TITLE
Relative url in CK Editor

### ISSUE THREAD

**Issue by Arnoost** [servocoder/RichFilemanager#264]
When I select an image or file, the URL contains protocol and Domain name.
Is it possible set a URL without https://example.com/?
Something like: /_files/userfiles/image.jpg?

Please, help me set it up?
Thank you for your help.

**Comment by servocoder** [comment]
You should use `beforeSelectItem` callback function. You can treat URL inside that function as you want and return it. Do this inside `config/filemanager.init.js` file:

```javascript
$('.fm-container').richFilemanager({
    callbacks: {
        beforeSelectItem: function (resourceObject, previewUrl) {
            return resourceObject.attributes.path;
        }
});
```

**Comment by Arnoost** [comment]
Thanks for your help.
