### ISSUE TITLE
Failed to resize image (thumbnail) in new folder

### ISSUE THREAD

**Issue by Arnoost** [servocoder/RichFilemanager#266]
Filed to resize image (thumbnail) when I upload images to a new folder.

My steps:
- Create new folder or subfolder in folder
- Upload new image
And click to upload - Failed to resize image (thumbnail)

I found the same "bug" on the official demo. See screenshot.
After refresh the page/folder, thumbnail images appear. The next time upload files to a folder, it's okay.

Filemanager say:
Failed to resize image (thumbnail)

Some files are failed during upload.
Hover your mouse over a file in the queue to view detailed information.

Tested in Chrome and Opera (last ver)

![snimek obrazovky 2017-11-20 v 14 02 18](https://user-images.githubusercontent.com/33807014/33019751-fcd691c4-cdfb-11e7-8b19-0474023f1ef3.png)
![snimek obrazovky 2017-11-20 v 13 58 29](https://user-images.githubusercontent.com/33807014/33019752-fcf00e4c-cdfb-11e7-8a2d-56ab0053058a.png)

**Comment by servocoder** [comment]
It was an issue in the PHP connector. Update PHP connector with `composer update` command (should be updated to v.1.1.4) and let me know if the issue is fixed for you.

**Comment by Arnoost** [comment]
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
**Nothing to install or update**
Generating autoload files

When I tried to create a new copy of FileManager and run the "composer update", it's the same result. But maybe I'm wrong. :(

My steps:
1) composer create-project --prefer-dist servocoder/richfilemanager _filemanager
2) composer require servocoder/richfilemanager-php (Nothing to install or update)
3) composer update

**Comment by servocoder** [comment]
When you create new project it setup the latest versions fo dependent packages. So it should be fine. You can navigate to folder that containg RFM package and run the following command:

`composer show servocoder/richfilemanager-php`

Look for the "version" line in the output.

**Comment by Arnoost** [comment]
I tried to install the file manager again.
I still have version 1.1.3.
Composer update say: Nothing to install or update

composer show servocoder/richfilemanager-php
name     : servocoder/richfilemanager-php
descrip. : PHP connector for RichFilemanager
keywords : connector, filemanager, php, plugin, richfilemanager
versions : * v1.1.3
type     : project
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/servocoder/RichFilemanager-PHP.git c30a378a37abd0fb028ca56f116147348693b9f4
dist     : [zip] https://api.github.com/repos/servocoder/RichFilemanager-PHP/zipball/c30a378a37abd0fb028ca56f116147348693b9f4 c30a378a37abd0fb028ca56f116147348693b9f4
names    : servocoder/richfilemanager-php

**Comment by servocoder** [comment]
This is the issue at your side. Here the packagist link:
https://packagist.org/packages/servocoder/richfilemanager-php

You can see that the latest version is 1.1.4
Seems that you locked "richfilemanager-php" package at v 1.1.3

Check your conposer.json file(s).
If they are correct perhaps you locked it globally somehow. Have no idea actually.

**Comment by Arnoost** [comment]
Thank you for your help. Unfortunately, I don't know the Composer and I don't know what Iam doing wrong. When I delete all files, clear Composer Cache (rm -rf ~/.composer/cache*) and run create project, system download all files as new.

composer create-project -prefer-dist servocoder/richfilemanager _filemanager

  - Installing symfony/polyfill-php54 (v1.6.0): Downloading (100%)         
  - Installing symfony/http-foundation (v2.8.31): Downloading (100%)         
  **- Installing servocoder/richfilemanager-php (v1.1.3): Downloading (100%)**   

After install and config everything works fine, but with old "richfilemanager-php". 
I apologize for your time. Thank you. :(

Info:
When i run composer create-project servocoder/richfilemanager-php also download v 1.1.3.

**Comment by servocoder** [comment]
Again. It's not an issue of the package itself. When I run the
```
composer create-project -prefer-dist servocoder/richfilemanager _filemanager
```
command it installs v1.1.4 of "servocoder/richfilemanager-php" package.

Try to google your issue.
The last advice I can get you is to check your PHP version. The latests version of "servocoder/richfilemanager-php" package requies PHP >= 5.6.4

If this is not your case I can't help you.

**Comment by Arnoost** [comment]
Iam using MAMP for MAC with php 7.1.1. 
I apologize for your time. Thank you.

**Comment by Arnoost** [comment]
Now everything works. I am so sorry. My fail.
Thank you very much for your help.

**Comment by servocoder** [comment]
Great, my congrats.
I'm curious what was the reason of the issue?

**Comment by Arnoost** [comment]
My stupidity.
MAMP using PHP7.1 but Composer uses system PHP (old version in El Capitan OSX)
Thank you and sorry.

**Comment by servocoder** [comment]
No problem. Good luck.
