### ISSUE TITLE
Search inside all the userfiles

### ISSUE THREAD

**Issue by SergioSaavedra** [servocoder/RichFilemanager#271]
There is some option in the configuration to enable the search within all the folders and not only in the current folder?

**Comment by servocoder** [comment]
No. This will require server-side search implementation and there are accompanying difficulties. I can't tell you whether this feature will be implemented ever.

**Comment by servocoder** [comment]
I have revised my opinion. This feature was requested before and it will fit for the upcoming release. So I will implement it for PHP connector. To get it supported for other connectors you have to request this feature from an appropriate maintainer or implement it yourself.

**Comment by SergioSaavedra** [comment]
Pavel that would be great!

**Comment by servocoder** [comment]
Released in v2.7.0
