### ISSUE TITLE
Problem when deploying at root context path

### ISSUE THREAD

**Issue by benbosman** [servocoder/RichFilemanager#274]
The code at https://github.com/servocoder/RichFilemanager/blob/master/connectors/jsp/libraries/java/src/edu/fuberlin/AbstractFM.java#L82 will cause an issue when the contextPath is empty (the application is deployed at root)

The code at https://github.com/servocoder/RichFilemanager/blob/master/connectors/jsp/libraries/java/src/edu/fuberlin/AbstractFM.java#L87 will still work at that time

**Comment by servocoder** [comment]
@fabriceci can help you with Java connector

**Comment by fabriceci** [comment]
Hi @benbosman, I wrote a more updated version of the connector. Which version of java and servlet API do you use ? (I used the Servlet 3.1 for the upload, I don't know if it's an issue for you.)

**Comment by benbosman** [comment]
Hi @fabriceci, I used both Servlet 3.0 and 3.1, but it's not specific to the version.

If referer is e.g. "https://www.example.com/filemanager/connectors/jsp/index.html" and contextPath = ""
referer.substring(referer.indexOf(contextPath) + 1 + contextPath.length(), referer.indexOf("index.html"))
=> ttps://www.example.com/filemanager/connectors/jsp/
=> incorrect

If referer is e.g. "https://www.example.com/example/filemanager/connectors/jsp/index.html" and contextPath = "example"
referer.substring(referer.indexOf(contextPath) + 1 + contextPath.length(), referer.indexOf("index.html"))
=> com/example/filemanager/connectors/jsp/
=> incorrect

If referer is e.g. "https://www.example.com/myapp/filemanager/connectors/jsp/index.html" and contextPath = "myapp"
referer.substring(referer.indexOf(contextPath) + 1 + contextPath.length(), referer.indexOf("index.html"))
=> filemanager/connectors/jsp/
=> correct


All 3 examples are handled correctly by https://github.com/servocoder/RichFilemanager/blob/master/connectors/jsp/libraries/java/src/edu/fuberlin/AbstractFM.java#L87 however

**Comment by servocoder** [comment]
@benbosman have you tried it with https://github.com/fabriceci/RichFilemanager-JAVA connector?

**Comment by fabriceci** [comment]
@benbosman I updated the connector linked by @servocoder to handle  "the current folder" as the file manager starter path and fix a little bug. It's an updated version that implement last features. I have not written the JSP connector, please try with this connector, the only requirement is java 7 and servlet 3.1 for the upload. (Both of these requirements can be easily downgraded).

**Comment by servocoder** [comment]
I have removed legacy built-in Java/JSP connectors and linked the actual Java connector in the [wiki](https://github.com/servocoder/RichFilemanager/wiki/JAVA-connector). I close the issue, feel free to reopen it in case of any unresolved issues.
