### ISSUE TITLE
Connector RichFilemanager-PHP using fm_authenticate() doesn't redirect to logon page

### ISSUE THREAD

**Issue by Nayenezgani** [servocoder/RichFilemanager#278]
I'm using _RichFilemanager-PHP_ connector with implemented function "**fm_authenticate()**"
when the function end with "`return ['redirect' => '/auth'];`", the UI doesn't redirect to the logon page but failed with error "Unable to perform initial request to server."
Response from "/connectors/php/filemanager.php" is:
`{"errors":[{"id":"server","code":"500","title":"AUTHORIZATION_REQUIRED","meta":{"redirect":"\/auth","arguments":[]}}]}`
Is this issue or I have something wrong configured?
Thx & Br

**Comment by servocoder** [comment]
It was a bug. I have committed a fix. Try it again and let me know if it's fixed, please.

**Comment by Nayenezgani** [comment]
Thank you, issue is fixed and working well now :-) 👍

**Comment by servocoder** [comment]
Released in v2.7.1
