### ISSUE TITLE
Crash on Fresh install (IIS)

### ISSUE THREAD

**Issue by cengizkrbck** [servocoder/RichFilemanager#279]
**In raising this issue, I confirm the following (please check boxes):**

- [X] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [X] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [X] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [ ] PHP connector by @servocoder
- [ ] Java connector by @fabriceci
- [ ] Python3 Flask connector by @jsooter
- [ ] Python3 Flask connector by @stevelittlefish
- [ ] NodeJs connector by @jlaustill and @forestlake
- [ ] ASP.NET Core connector by @sinanbozkus
- [X] ASHX connector by @richeflits
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [X] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

Hi All,

I willing to use this awesome plugin in my project. Project setup; asp.net + wcf+ ckeditor4 + jquery.1.41 

Here is the problem;
- I deployed 2.7.0 version folder 
- renamed config and init files like the wiki recommendation.
- just renamed files not edited!

When i browse to deployed  /RichFilemanager/index.html, a fatal error occurs and crashes.
Here is the console log;(i cropped value field, complete log at the file.
[cldr_error.txt](https://github.com/servocoder/RichFilemanager/files/1642014/cldr_error.txt)
)

cldr.js:339 Uncaught Error: E_INVALID_PAR_TYPE: {"expected":"Plain Object","name":"json","value":"{\n  \"main\": {\n    \"tr\": {\n      \"identity\": {\n        \"version\": {\n          \"_number\": \"$Revision: 13705 $\",\n          \"_cldrVersion\": \"32.0.1\"\n        },\n        \"language\": \"tr\"\n      },\n      \"dates\": {\n        \"calendars\": {\n[ABBREVITED]}\n  }\n}\n"}
    at createError (cldr.js:339)
    at validate (cldr.js:355)
    at validateType (cldr.js:372)
    at validateTypePlainObject (cldr.js:400)
    at coreLoad (cldr.js:520)
    at Function.Cldr.load (cldr.js:576)
    at Array.Globalize.load (globalize.js:373)
    at Array.<anonymous> (jquery-1.11.3.min.js:2)
    at j (jquery-1.11.3.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.3.min.js:2)
    at Array.<anonymous> (jquery-1.11.3.min.js:2)
    at j (jquery-1.11.3.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.3.min.js:2)
    at Object.<anonymous> (jquery-1.11.3.min.js:2)
    at j (jquery-1.11.3.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.3.min.js:2)
    at x (jquery-1.11.3.min.js:5)
    at XMLHttpRequest.b (jquery-1.11.3.min.js:5)

**Comment by servocoder** [comment]
CLDR has been added in v2.7.0
Also some backward incompatible changes included in this release, that's why you get errors:
https://github.com/servocoder/RichFilemanager/releases

I personally don't support ASHX connector (IIS).
You can either install __v2.6.*__ or try to make ASHX connector up to date to support the latest changes It should be compatible with the [API](https://github.com/servocoder/RichFilemanager/wiki/API). I'm pretty sure it won't be a big deal for a person experienced with ASP. I would appreciate your help.

**Comment by servocoder** [comment]
Sure, making a PR would be great.
Thanks in advance.

**Comment by servocoder** [comment]
Have you got a progress with ASHX connector ?

**Comment by servocoder** [comment]
Closed this issue due to no feedback. Let me know if are working on it and I will reopen the issue.
