### ISSUE TITLE
integration RichFilemanager with FTP

### ISSUE THREAD

**Issue by webcoweb** [servocoder/RichFilemanager#280]
Hello,
At first thanks for these perfect package.
I like to know , how can I integration this filemanager with FTP connection for remote uploading with nodejs ?

**Comment by servocoder** [comment]
Thanks for your appreciation.
RichFilemanager has been designed to handle HTTP requests.
I don't think it's possible to integrate it with FTP connection unfortunately.

**Comment by jsooter** [comment]
If you wanted to create a desktop ftp client with electron (nodejs + Chromium) all you would have to do would be to write a nodejs module for handling the ftp between the client and the server. Just pick your client npm: https://www.npmjs.com/package/ftp

This would make a fun project.

**Comment by webcoweb** [comment]
Thanks...
