### ISSUE TITLE
Save File does not pass the Set Request Params as other methods

### ISSUE THREAD

**Issue by OmarAlkylaney** [servocoder/RichFilemanager#282]
Dear All,
Save File Method does not pass the parameters that been set on the beforeSetRequestParams as I need these parameters as they will be used on the server side.
Please note that I am using ASP NET DNN

**Comment by OmarAlkylaney** [comment]
Save File Method does not pass the parameters that been set on the beforeSetRequestParams as I need these parameters as they will be used on the server side.

**Comment by servocoder** [comment]
It does, but Save File accept form parameters, which should be treated in a special way. Let's assume you would like to add parameter "jwt" with "token" value. In this case the "beforeSetRequestParams" callback should look as the following:

```javascript
$('.fm-container').richFilemanager({
    baseUrl: '.',
    callbacks: {
        beforeSetRequestParams: function (requestMethod, requestParams) {
            // treating form parameters
            if (requestMethod === 'POST' && $.isArray(requestParams)) {
                requestParams.push({name: "jwt", value: "token"});
            } else {
                requestParams.jwt = 'token';
            }
            return requestParams;
        }
    }
});
```

**Comment by servocoder** [comment]
Not sure is there any particular issues related to the  ASP NET platform though

**Comment by OmarAlkylaney** [comment]
I think that will be work then as I am only using the requestParams as an object and not an array of objects.

Thanks mate.
