### ISSUE TITLE
Call to undefined : mime_content_type()

### ISSUE THREAD

**Issue by agoenks29D** [servocoder/RichFilemanager#283]
Message: **Call to undefined function RFM\Repository\Local\mime_content_type()**
in file : **vendor\servocoder\richfilemanager-php\src\Repository\Local\ItemModel.php**

i think this function has been deprecated
php version : 7.0.1

**Comment by servocoder** [comment]
Check whether your PHP is compiled with "fileinfo" extension. On Windows use "php_fileinfo.dll" file.

**Comment by servocoder** [comment]
Have you solved your issue?

**Comment by agoenks29D** [comment]
Yes sir,thank you so much for your help..
