### ISSUE TITLE
Office files preview not working

### ISSUE THREAD

**Issue by richakadkade** [servocoder/RichFilemanager#284]
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [x] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [x] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [x] PHP connector by @servocoder
- [ ] Java connector by @fabriceci
- [ ] Python3 Flask connector by @jsooter
- [ ] Python3 Flask connector by @stevelittlefish
- [ ] NodeJs connector by @jlaustill and @forestlake
- [ ] ASP.NET Core connector by @sinanbozkus
- [ ] ASHX connector by @richeflits
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

{issue content here}

**Comment by richakadkade** [comment]
I am trying to preview office files in the file manager but it does not seem to work.
My upload folder is on local root directoty.
https://localhost/filemanager/userfiles/
I am running the code from my windows local system
This is what my json file looks like:

"absolutePath": true,
        "previewUrl": "http://localhost/",
Let me know where I am going wrong.
Please help!!!

**Comment by servocoder** [comment]
Sorry for late response. This viewer is quite "special", however it works well at the RFM demo site. Try to run it at server and see how it's go.
