### ISSUE TITLE
Extending plugin functionality

### ISSUE THREAD

**Issue by deepchandyadav** [servocoder/RichFilemanager#286]
I want to add image cropping feature. 
How could I do this using other jQuery plugin?

**Comment by servocoder** [comment]
The [Blueimp Fileuploader](https://github.com/blueimp/jQuery-File-Upload), included into Filemanager, supports images cropping. Follow the plugin Wiki for examples. Feel free to experiment and implement cropping by yourself. In case of success experience you can suggest a PR with a complete solution.
