### ISSUE TITLE
How to deal with composer and asset management (Yii2)

### ISSUE THREAD

**Issue by robsch** [servocoder/RichFilemanager#287]
I'm wondering how to deal with the RichFilemanager in conjunction with composer, the vendor directory, and asset management of Yii2. I don't know if you know Yii2, but I will try to explain my problem more or less independently of this framework.

I _require_ RichFilemanager with composer. It gets copied to the vendor folder. I assume, what might be wrong, that the browser does not and should not access files in the vendor directory directly. Therefore Yii2 has the asset management, which copies files (for the usage by the browser) from the vendor dir to a web accessible dir. So now the RichFilemanager files are placed in _myProject/web/16875791_ for example. This directory was generated and could be a different one - I don't know the hash and cannot access it within my code.

The js and css files all get requested by the browser correctly, that is the accoring tags were injected into the html by the asset management. That's okay. But other files like json (configuration files!) or image files cannot be injected. They get requested programatically by RFM. For that it uses the baseUrl. This url by default is '.' which means the current browser path. But e.g. language/en.json is in the asset directory, it cannot be accessed with the current path!

Since I cannot change baseUrl to the asset directory, because I don't know the hash directory name, those files cannot be found. 

Another problem is, if I would be able to change baseUrl to this directory, then the configuration files (filemenager.config.json and filemanager.config.default.json) would be expected there as well. But this is also not sound: this directory gets generated as the files gets copied from the vendor dir to the asset dir. I cannot edit the configuration files there. They are even not under version control.

It's probably a bit confusing - also to me :-D
In the end I would suggest to change the meaning of baseUrl and the usage of the configuration files somehow. I would let point baseUrl to (the parent of) the directory where filemanager.js was retrieved from by default. All files of RFM can be found in this directory. At least baseUrl shouldn't use the current url path. This path has no meaning, as I get it right. 
And maybe the configuration files should be either specified via another parameter (path to this file) or dropped completely. Dropping would be okay, I think: why not provide the whole configuration via _$('.fm-container').richFilemanager({...config...})_? At least it should be possible that RFM does not request the server for configuration files anymore.

I saw #76 too. @triawarman ended up with copying the RFM files into his project instead of just requiring them via composer (there is a require statement in composer.json though, but the files were copied anyway).

I hope you see the problems. There may be other, better solutions. However, approaching it would make the RFM more usable, also for other frameworks. Or you could update the documentation to clarify how to do it correctly.

RFM rocks! 👍

**Comment by robsch** [comment]
Okay, as far as I understand this project is not set up in a composer-way. Right? All libraries that is uses are contained in the project instead of that they get _required_ with composer.

I'm now a bit confused how to set it up in my project when I have fetched it via composer. Maybe the wiki does not describe it clearly enough - for dummies like me (confused by the lot of technologies). What to do if RFM is in the vendor folder? Symlinking it? Copy it? Use some kind of asset management tools?

Is the [index.html](https://github.com/servocoder/RichFilemanager/blob/master/index.html) file intended to be used directly, probably in an iframe? Because jQuery 1.11.13, whereas my Yii2 based application uses jQuery 3.x. and other stuff already. Without an iframe it seems to be not that easy to integrate the RFM.

**Comment by servocoder** [comment]
It's not mandatory to install the whole project with composer. You can clone this git repository into the folder that convenient for you. After that install the "servocoder/richfilemanager-php" package with composer separately. See [here](https://github.com/servocoder/RichFilemanager-PHP#installation).

Thus way you can avoid to use publishing files with assets manager. Just put repo files into the public folder. And, of course, you will have to configure paths in the RFM config files. See the Wiki

**Comment by robsch** [comment]
I have done it that way and it works so far! Wouldn't it be interesting to set up the project in a composer way? Would be helpful (esp. with keeping the package up to date). But I know it needs time, knowledge and efforts. Fully understand if this is beyond the scope. Anyway, I'm glad that RFM exists! Thanks.

**Comment by servocoder** [comment]
Thanks for your words and suggestion.

Sure this may be interesting, but I'm too busy on my current project now. If you can implement this idea go ahead you create a PR when it's ready. I welcome a wise contribution.
