### ISSUE TITLE
Some files are during upload

### ISSUE THREAD

**Issue by salamat1995** [servocoder/RichFilemanager#288]
@#
<img width="1208" alt="2018-02-18 21 22 30" src="https://user-images.githubusercontent.com/30227583/36354181-088a96c2-14f2-11e8-9c33-a1b8a1b8873e.png">.
 When i Upload file i have the following error.  Some files are failed during upload. On the console as you see internal fatal error. How can fix it?

**Comment by servocoder** [comment]
This may be fixed with next release. I will let you know

**Comment by salamat1995** [comment]
Thank you. I will wait

**Comment by servocoder** [comment]
Update to the latest version (2.7.1) and try again

If the issue will persist then I expect you to provide more comprehensive description and logs.

**Comment by salamat1995** [comment]
Thank you. It worked
