### ISSUE TITLE
Rename issue

### ISSUE THREAD

**Issue by supun19** [servocoder/RichFilemanager#289]
i rename the video and image. it will rename but cannot open it show error system permission do not allow you to perform this action and also there are appear with lock icon. could you help

**Comment by servocoder** [comment]
System permissions error means that file becomes unreadable. Check system permissions of your files after rename.

**Comment by supun19** [comment]
files are uploaded to s3 bucket. s3bucketFullAccess is given to file manager. file uploading is working. when i renamed the file. the file is delete from bucket automatically.

**Comment by servocoder** [comment]
When you rename objects at S3 the underlying process is the following:

1. Copy object to new location
2. Remove original object 

Seems the copy fails, but remove is successful. Try to copy object directly to your destinatination folder. I guess it will fail as well. Perhaps your target folder has some policies that forbid to put new objects, or other restrictions.

**Comment by supun19** [comment]
I can rename and copy bucket object using awsCli and i check i have given AmazonS3FullAccess for richfilemanager

**Comment by servocoder** [comment]
Have you tried the latest (yesterday's) release?

**Comment by supun19** [comment]
yeah i try it. its also have error. 
copy object to new location mean current folder know(rename object directory in bucket )

**Comment by supun19** [comment]
I set the server side encryption as $config_s3['encryption'] = 'AES256'; in connectors/php/filemanager.php  file.

but  'ServerSideEncryption' => '$this->encryption(line 308), this line not get encryption method as 'AES256' in connectors/php/vendor/servocoder/richfilemanager-php/src/Repository/S3/Storage.php

so i hardcoded as 'ServerSideEncryption' => 'AES256', in connectors/php/vendor/servocoder/richfilemanager-php/src/Repository/S3/Storage.php

not can file rename and move . what do i missed in configuration  . can you help

**Comment by supun19** [comment]
now can rename and move file

**Comment by servocoder** [comment]
I followed the steps you had described and can assure you that value `$config_s3['encryption'] = 'AES256';` defined in the `filemanager.php` file is passed correctly to the `Repository/S3/Storage.php`. I believe there is some implicit error source at your side. You can attach your `filemanager.php` file, and I will be able to review your configuration definition. Don't forget to cleanup sensitive data like AWS keys.

**Comment by supun19** [comment]
here is my filemanager.php
[filemanager.php.zip](https://github.com/servocoder/RichFilemanager/files/1769790/filemanager.php.zip)

**Comment by supun19** [comment]
$app->api = new RFM\Api\LocalApi(); .I though  that line need for keep thumbnail in local storage that why i use that line. is it

**Comment by servocoder** [comment]
No, the following lines are all you need to keep thumbnail in local storage:

```php
$local = new \RFM\Repository\Local\Storage($config);
$local->setRoot('userfiles', true);
$app->setStorage($local);
```

The API instance should be used for main storage only, the S3 API in your case.
