### ISSUE TITLE
filemanager.ashx not handling virtual directories

### ISSUE THREAD

**Issue by gkustas** [servocoder/RichFilemanager#290]
**In raising this issue, I confirm the following (please check boxes):**

- [x ] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [x ] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [ x] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [x ] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [ ] PHP connector by @servocoder
- [ ] Java connector by @fabriceci
- [ ] Python3 Flask connector by @jsooter
- [ ] Python3 Flask connector by @stevelittlefish
- [ ] NodeJs connector by @jlaustill and @forestlake
- [ ] ASP.NET Core connector by @sinanbozkus
- [x ] ASHX connector by @richeflits
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

I am using the ashx connector. When I run it on a local web site (with no virtual directory created in IIS) everything works fine. When I upload to a server hosted on http://playtennisconnect.com/testtinymce, the paths are mapped incorrectly. The code uses Server.Mappath() which leaves out the virtual directory name and ends up with a path like http://playtennisconnect.com/images/picture.png.

I am going to try the asp connector, but before I did I thought I'd check to see if my ashx problem might be a configuration error I made on my end.

Also - are there any instructions for installing the asp connector? I notice that there are references to the AspNetCore MVC libraries.

**Comment by servocoder** [comment]
ASHX/ASP connectors became outdated after few last releases. This may cause issues. I personally support PHP connector and can't assist you with ASHX connector unfortunately.

@richeflits did a lot, but I you'd better rely on your own.  If you feel strong enough in ASHX you can update ASHX connector or write it from scratch. Each connector should implement the [API](https://github.com/servocoder/RichFilemanager/wiki/API). I'm pretty sure it won't be a big deal for a person experienced with a particular programming language.

There are no instructions, unfortunately.

Any updates and PR's are welcome.

**Comment by gkustas** [comment]
Thanks Pavel for the response. For the time being we are OK because our
production server isn't hosted under a virtual directory. The current ashx
connector is old, but simple and simple is good for this kind of thing. It
works fine. I think the asp core connector is overkill and has way too many
dependencies making for a very bloated server.

Maybe one day I'll fix the Mappath problem. I started doing it but I didn't
have time to finish it and I wanted to hear what you had to say about it.
We'll see...

**Comment by servocoder** [comment]
Sound good. Good luck!
