### ISSUE TITLE
Invalid dates for create and modified time in preview window

### ISSUE THREAD

**Issue by gkustas** [servocoder/RichFilemanager#291]
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [x] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [ ] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [ ] PHP connector by @servocoder
- [ ] Java connector by @fabriceci
- [ ] Python3 Flask connector by @jsooter
- [ ] Python3 Flask connector by @stevelittlefish
- [ ] NodeJs connector by @jlaustill and @forestlake
- [ ] ASP.NET Core connector by @sinanbozkus
- [x] ASHX connector by @richeflits
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

In filemanager.js, line 1018, 1019 as well as 1930, 1931, formatTimestamp is called but instead of a milliseconds timestamp (integer) it is passing a formatted date/time string. The resulting date displat with "NaN/NaN/....." etc.

I was able to fix this locally by using the javascript Date object like so:

formatTimestamp(new Date(resourceObject.attributes.created).getTime());

ALSO IMPORTANT:
The formatTimestamp method assumes a timestamp is sent in seconds (not milliseconds). I couldn't find any instance in the code where that was being done. So, I changed the code that sets the date to this:

 var date = new Date(timestamp);

The changes appear to be working.

**Comment by servocoder** [comment]
I can see you use ASHX connector. Client-side code was adapted for PHP-connector mainly and I can't see any issues with dates at the demo site. All issues you described seems caused by ASHX connector, which is a bit out of date with the latest client-side updates. The main idea here is not to modify client-side code, but adapt ASHX connector code. If you will do this I would gladly accept your PR(s).

**Comment by gkustas** [comment]
OK... So I pulled down the ashx from the github site, and found that is was newer than the one I somehow ended up with. I resored both the filemanager.js and the ashx, and the problem does not exist. Sorry for the false alarm. I don't recall where I got that ashx if I didn't get the clone from github.
