### ISSUE TITLE
Don't load folder contents when unfolding tree

### ISSUE THREAD

**Issue by jnvsor** [servocoder/RichFilemanager#293]
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [x] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [x] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [x] PHP connector by @servocoder
- [ ] Java connector by @fabriceci
- [ ] Python3 Flask connector by @jsooter
- [ ] Python3 Flask connector by @stevelittlefish
- [ ] NodeJs connector by @jlaustill and @forestlake
- [ ] ASP.NET Core connector by @sinanbozkus
- [ ] ASHX connector by @richeflits
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

When unfolding a large folder in the tree, it would be nice if it didn't load the actual contents of the folder in the main pane. That largely defeats the purpose of having a separate tree.

You can also get *large* performance improvements when `foldersOnly` is on if it's a separate request.

**Comment by servocoder** [comment]
There is an idea to implement a kind of pagination for large folders. You can find some discussion here: https://github.com/servocoder/RichFilemanager/issues/98#issuecomment-277189581. Unfortunately I'm quite busy now to implement this feature.

**Comment by jnvsor** [comment]
@servocoder I'm not sure it's worth it. I did a quick test here and it's taking 2 seconds to open a folder from a readfolder request that takes... 43ms...

According to firefox perf tools there's a 2 second readystatechange event handler in knockout js. I think the biggest perf improvement would be from switching to something like vue or react but that's a full blown rewrite...

**Comment by jlaustill** [comment]
@jnvsor we could actually rewrite in vue very easily.  Knockout -> vue almost directly, just need to split viewmodels into data and methods, and update the templates to vue syntax.  I'll bet that could be knocked out in a weekend and boy would it be an improvement...

That being said, I'm a react developer for a living haha

**Comment by jnvsor** [comment]
I'm not (primarily) a JS developer so I don't have much to say about perf (Or architectural decisions) in general. @jlaustill Perhaps you should make an issue with some framework comparisons?

Anyway, it's my fault we're going a bit off topic here - I still think the original point is a good idea (Not refreshing the pane when unfolding a folder) for both perf and UX reasons

**Comment by servocoder** [comment]
1. The original topic issue.

I have implemented the feature you requested, but only if you click a plus(+) icon next to the folder name in the filetree. Let me know if it behaves as you expected. Is this sufficient for your case?

If you would like that it works the same when you click upon folder name, then a new configuration option should be provided, because other users may found the current behavior of filletree is more convenient for them. No perfect solution to satisfy all.

2. Knockout vs Vuejs

I definetely vote for migrating to Vuejs. @jlaustill is correct that Knockout is quite similar to Vue in terms of basics, but it's a time consuming milestone either way, and I personally have a lack of time. I'm ready to provide a support to anyone, how would like to assist in the RFM migration to Vuejs.

**Comment by jnvsor** [comment]
Yes that's exactly what I was hoping for, thanks!
