### ISSUE TITLE
Hide/Filter folders

### ISSUE THREAD

**Issue by pkollitsch** [servocoder/RichFilemanager#296]
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [x] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [x] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [x] PHP connector by @servocoder

**My familiarity with the project is as follows (check one):**

- [x] I have used the project extensively, but have not contributed previously.

---

I can't find an option to filter out folders from being displayed. In this specific case I have a folder loaded in rich file manager. Inside of the folder is a .git directory that is shown in the file manager. 

It should be possible to either filter this directory from being shown or filter all dot-directories (as they tend to be "hidden" directories).

**Comment by pkollitsch** [comment]
Sorry, this is the job of the connector, obviously.

**Comment by chirag00757** [comment]
How did you solve, hiding folders using connector? I want to hide folders which are not permitted to particular user.
