### ISSUE TITLE
PDF Preview not working at all. Office files are getting a preview perfectly

### ISSUE THREAD

**Issue by RRangioni** [servocoder/RichFilemanager#298]
**In raising this issue, I confirm the following (please check boxes):**

- [X] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [X] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [X] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [X ] PHP connector by @servocoder
- [ ] Java connector by @fabriceci
- [ ] Python3 Flask connector by @jsooter
- [ ] Python3 Flask connector by @stevelittlefish
- [ ] NodeJs connector by @jlaustill and @forestlake
- [ ] ASP.NET Core connector by @sinanbozkus
- [ ] ASHX connector by @richeflits
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

Fileroot is inside the serverroot. 

PDF's are not rendered for preview.
DOC(X), XLS(S) are perfectly previewed.

filemanager.config.json 

    "viewer": {
        "absolutePath": true,
        "previewUrl": false,

config.local.php
     "serverRoot" => true,
     "fileRoot" => "/collections/",

the preview is failing, but when i copy the URL and paste into a new window, the preview is loaded !!

https://<domain>/rfm-org/connectors/php/filemanager.php?path=/solutions.pdf&mode=readfile

**Comment by servocoder** [comment]
PDF files preview works well, just tested it at the demo site.

But I remember that I had issues with big PDF and office files. You can face it if your file is bigger than 2mb. However sometimes it works well even for big files. I can suppose this previwer can break at some specific content or symbols in the doc. Very fragile previewer. Let me know if you will find a better replacement.

**Comment by RRangioni** [comment]
The strange part is: the same PDF's are working fine in a different configuration where the fileroot is outside the ServerRoot.

    "viewer": {
        "absolutePath": false,
        "previewUrl": "/fileroot/",

in config.local.php:
        "serverRoot" => false,
        "fileRoot" => "/fileroot/",

**Comment by RRangioni** [comment]
When i copy the link and paste it into a new window/tab, the preview works perfectly.

**Comment by servocoder** [comment]
Weird indeed. I can't do much with this issue since it seems the viewer issue. Let me know if you find a solution.
