### ISSUE TITLE
IIS bug. "Directory path '/' is invalid"

### ISSUE THREAD

**Issue by Guanche** [servocoder/RichFilemanager#299]
**In raising this issue, I confirm the following (please check boxes):**

- [X] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [X] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [X] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [X] PHP connector by @servocoder
- [ ] Java connector by @fabriceci
- [ ] Python3 Flask connector by @jsooter
- [ ] Python3 Flask connector by @stevelittlefish
- [ ] NodeJs connector by @jlaustill and @forestlake
- [ ] ASP.NET Core connector by @sinanbozkus
- [ ] ASHX connector by @richeflits
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [X] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

Hi, an error happens when using the plugin with IIS. 
After a correct instalation this message appears everytime: "Directory path '/' is invalid".

The problem is into ItemModel.php, at connectors\php\vendor\servocoder\richfilemanager-php\src\Repository\Local, at this lines:

```
$realPathItem = realpath($this->pathAbsolute);
$realPathRoot = realpath($this->storage->getRoot());
array_unshift($allowedPaths, $realPathRoot);

// clean up paths for more accurate comparison
$allowedPaths = array_map([$this->storage, 'cleanPath'], $allowedPaths);
$match = starts_with($realPathItem, $allowedPaths);
        
if (!$match) {
		Log::info('Item path validation FAILED');            
		Log::info('Absolute path "' . $this->pathAbsolute . '"');            
		Log::info('Real path: "' . $realPathItem . '"');            
		Log::info('Tested paths: "' . json_encode($allowedPaths) . '"');
}
return $match;
```

What I did to solve it was replacing this lines:

```
/*
$realPathItem = realpath($this->pathAbsolute);
$realPathRoot = realpath($this->storage->getRoot());
*/
				
$realPathItem = $this->pathAbsolute;        
$realPathRoot = $this->storage->getRoot();
```

realpath function returns the path in windows format, using \ as separator. While method cleanPath turns \ into /. And then they don't match.

Now it seems that works fine. I've not had any problems till now.

Greetings from the Canary Islands.

**Comment by servocoder** [comment]
I'm glad you solved your issue, but `realpath` is important security check. Using it we can make sure that there are no symlinks linked to restricted locations outside userfiles folder. So I strongly don't recommend you to avoid it.

What if you rewrite it in the following way:

```php
$match = starts_with($this->storage->cleanPath($realPathItem), $allowedPaths);
```

This is appropriate solution that I can include in the next release.

I believe this should work for you. Let me know if so.

**Comment by Guanche** [comment]
Thanks. As you say it works ok.

**Comment by servocoder** [comment]
Fixed. Will be included in the next release.
