### ISSUE TITLE
nodejs  server file's  async problem

### ISSUE THREAD

**Issue by ftfuntjh** [servocoder/RichFilemanager#300]
in packge/connectors/nodejs/fillmanager.js file
in some case  
when readfolder run at  if($index>=loopInfo.total)  it will not  response all the files in file server'folder  

because the async fs.stat function  does't  finnish read file info inorder

for fix the bug 

use the follow code replace 
loopInfo[$index] = true;
if(isAllFinish(loopInfo)){
  callback(loopInfo.results)
}

function isAllFinish(l){
   for(var i=0;i<l.total;i++){
        if(!l.status[i])
           return false;
  }
     return  true;
}

or you can  use  Promise  fix the Bug

**Comment by servocoder** [comment]
Yeah, this connector may be outdated.
Thanks for the fix.

Btw, you can try this one:
https://github.com/dekyfin/RichFilemanager-NODE

Let me know how it works for you please.
