### ISSUE TITLE
error opening file browser when Editor Resize plugin is installed

### ISSUE THREAD

**Issue by Guanche** [servocoder/RichFilemanager#302]
**In raising this issue, I confirm the following (please check boxes):**

- [X] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [X] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [X] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [X] PHP connector by @servocoder
- [ ] Java connector by @fabriceci
- [ ] Python3 Flask connector by @jsooter
- [ ] Python3 Flask connector by @stevelittlefish
- [ ] NodeJs connector by @jlaustill and @forestlake
- [ ] ASP.NET Core connector by @sinanbozkus
- [ ] ASHX connector by @richeflits
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [X] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

Hi again.

I've added the Editor Resize plugin (https://ckeditor.com/cke4/addon/resize).

When the "browse files" button is pressed at the Enhanced Image plugin dialog window an error happens at the code added for opening the rfm in a modal window:

config.js?t=HBDD:94 Uncaught ReferenceError: $ is not defined
    at button.browseButton.onClick (config.js?t=HBDD:94)
    at button.<anonymous> (ckeditor.js:549)
    at button.m (ckeditor.js:10)
    at button.fire (ckeditor.js:12)
    at button.click (ckeditor.js:548)
    at CKEDITOR.dom.element.<anonymous> (ckeditor.js:540)
    at CKEDITOR.dom.element.m (ckeditor.js:10)
    at CKEDITOR.dom.element.fire (ckeditor.js:12)
    at HTMLAnchorElement.<anonymous> (ckeditor.js:65)

The code line is:

var iframe = $("<iframe id='fm-iframe' class='fm-modal'/>").attr({
			src: '/rfm' + // Change it to wherever  Filemanager is stored.
			'?CKEditorFuncNum=' + CKEDITOR.instances[event.editor.name]._.filebrowserFn +
			'&CKEditorCleanUpFuncNum=' + cleanUpFuncRef +
			'&langCode=en' +
			'&CKEditor=' + event.editor.name
		});

Is the code for opening the rfm in a modal window necessary? In my case if not included the browser button stays hidden even with the rfm path assigned as the file browser url.

Thanks

Edit:
I mean that the bug happens after installing this plugin and stop when I uninstall it. I've tried setting to false the resize option at ckeditor.config on the dialog open and show event, but it doesnt seem to work.

**Comment by servocoder** [comment]
I don't experience any issues with resize plugin for CKEditor. Moreover I can see it's enabled by default, and works smooth at the demopage: http://fm.devale.pro/demo/

**Comment by Guanche** [comment]
Oh, hell. I did an stupid setup error. I'm just starting with ckeditor and rfm. Sorry.
