### ISSUE TITLE
PDF preview over JAVA-connector

### ISSUE THREAD

**Issue by submediax** [servocoder/RichFilemanager#303]
FileManager (libs/ViewerJS/index.html) sends HEAD request to /api but connector expects for GET request so it entails not working PDF preview.

**Comment by servocoder** [comment]
@fabriceci could you vefify and fix the issue with Java connector?

**Comment by fabriceci** [comment]
@submediax @servocoder the issue is solved in my [last commit](https://github.com/fabriceci/RichFilemanager-JAVA/commit/5ab2466740a35d44aa55aef7a5329b8ff22b54ea).

**Comment by servocoder** [comment]
@fabriceci thank you

@submediax your feedback is appreciated

FYI: you can open issues directly in the [RichFilemanager-JAVA](https://github.com/fabriceci/RichFilemanager-JAVA) connector repository in case of further questions which relate to Java connector.
