### ISSUE TITLE
Removed and now .htaccess doesn't work

### ISSUE THREAD

**Issue by stingwraith** [servocoder/RichFilemanager#306]
**In raising this issue, I confirm the following (please check boxes):**

- [x ] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [x ] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [ x] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [x ] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [ x] PHP connector by **servocoder**
- [ ] Java connector by **fabriceci**
- [ ] Python3 Flask connector by **jsooter**
- [ ] Python3 Flask connector by **stevelittlefish**
- [ ] NodeJs connector by **jlaustill** and **forestlake**
- [ ] ASP.NET Core connector by **sinanbozkus**
- [ ] ASHX connector by **richeflits**
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

After following the instructions and setting everything up properly, I went to remove and uninstall everything and now my .htaccess isn't working, or just the auth portion of it as it would seem it's loading my css and header/footer fine but it isnt prompting me for any login info. I've completely removed and uninstalled composer and removed any trace of RFM from my apache directory, I've put the auth .htaccess file just about everywhere. I've reinstalled apache2.4 and replaced the httpd.conf with my custom one. Despite all this the auth doesn't seem to be working. Here's what I have in my .htaccess thats isn't working:

`AuthUserFile C:\Apache24\.htpasswd
AuthName "Please Enter Password"
AuthType Basic
Require valid-user`

I also have added this to my httpd.conf with no luck:

`<Directory />
    AllowOverride All
    Require all granted
</Directory>

<Directory "D:\Downloads">
    Allow from All
    Satisfy Any
</Directory>

DocumentRoot "D:\Downloads"
<Directory "D:\Downloads">

    Options Indexes FollowSymLinks
    AuthUserFile C:\Apache24\.htpasswd
    AuthName "Please Enter Password"
    AuthType Basic
    Require valid-user`

**Comment by servocoder** [comment]
Your question doesn't relate to RichFilemanager directly.

I can't help you with your apache config.

**Comment by stingwraith** [comment]
Umm, no. I'm showing you that my Apache config is set up correctly. The installation requirements of YOUR utility caused it to stop working. I'm simply asking what about this installation would break auth in a webserver?

Thanks.

**Comment by servocoder** [comment]
The package can't break apache server in any way. This is impossible. The `.htaccess` file affects only the folder where it's located. Deletetion of `.htaccess` file it does not leave any traces. You should learn how webservers work.

Again, this does not apply to the RichFilemanager.
