### ISSUE TITLE
NaN shown instead of Create and Modify Datetime

### ISSUE THREAD

**Issue by ShortBusKing** [servocoder/RichFilemanager#308]
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [x] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [x] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [ ] PHP connector by **servocoder**
- [ ] Java connector by **fabriceci**
- [ ] Python3 Flask connector by **jsooter**
- [ ] Python3 Flask connector by **stevelittlefish**
- [ ] NodeJs connector by **jlaustill** and **forestlake**
- [x] ASP.NET Core connector by **sinanbozkus**
- [ ] ASHX connector by **richeflits**
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

Hello, 
I am leveraging the ASP.NET Core connector on a windows 2008 R2 server. I would see a 'NaN' for the modified file dates. The issue come from the connector returning a human readable date in the timestamp, which then gets multiplied by 1000. This creates a undefined value. Below is one potential fix written against the javascript library. I also considered updating the connector so that it returns a UNIX timestamp, but I thought this was best as long as it doesn't mess up everyone.

	// Converts UNIX timestamp to formatted datetime string
	var formatTimestamp = function(timestamp) {
		// if value doesn't look like timestamp
		if (!timestamp || timestamp <= 0) {
			return '';
		}

            ////// proposed fix for windows ////////////
            if (Date.parse(timestamp)) {
                return timestamp;
            } else {
            ////// END proposed fix for windows ////////////

                // Converts UNIX timestamp to formatted datetime string
               var date = new Date();
               date.setTime(timestamp * 1000); // Creates undefined

                // Timezone support requires "iana-tz-data" package:
                // https://github.com/globalizejs/globalize/blob/master/README.md#3-iana-time-zone-data
                return globalize.formatDate(timestamp, config.formatter.datetime);
            }
	};

**Comment by servocoder** [comment]
I don't want to overload JS script trying to handle cases "for all occasions". There is a defined format for expected timestamp, so I would prefer the fix for ASP.NET Core connector. If you are able to create a PR (or provide a code snippet at least) for ASP.NET Core connector I would accept it and include into the package.

**Comment by ShortBusKing** [comment]
I fully understand that and completely agree. I know I presented this as a Windows fix but it might still be valuable. Are there situations where a date will parse but shouldn't be displayed?

I'm working with the ASP.NET connector and there are other changes already. What is the proper date format the UI code is expecting?

**Comment by servocoder** [comment]
> What is the proper date format the UI code is expecting?

[Unix timestamp](https://www.unixtimestamp.com/) in seconds


> I know I presented this as a Windows fix but it might still be valuable.

Ok, makes sense. I would propose it in a different manner. The code snippet below should handle seconds timestamp as well as milliseconds, and also make attempt to turn string into the `Date()` object. If fail it will return value without formatting. Check if this code snippet works for you:

```javascript
    var formatTimestamp = function (datetime) {
        var isString = typeof datetime === "string";
        var isInteger = typeof datetime === "number" && Math.floor(datetime) === datetime;

        // invalid argument
        if (!(isString || isInteger)) return '';

        // value look like seconds, while Date() accepts milliseconds
        if (isInteger && datetime < 10000000000) {
            datetime = datetime * 1000
        }

        var date = new Date(datetime);

        // invalid Date() object, display datetime without formatting
        if (!(date instanceof Date) || isNaN(date)) {
            return datetime;
        }

        // Timezone support requires "iana-tz-data" package:
        // https://github.com/globalizejs/globalize/blob/master/README.md#3-iana-time-zone-data
        return globalize.formatDate(date, config.formatter.datetime);
    };
```
Looking forward your feedback.


> I'm working with the ASP.NET connector and there are other changes already.

Awesome! If you will provide a changelog along with PR it would speed up a review.

**Comment by ShortBusKing** [comment]
This looks pretty bullet proof to me. :) I've updated the connector to return GMT time in Unix format. It seems to work well with your existing code. It even works correctly with the globalize library.
