### ISSUE TITLE
 Angular-Cli does not serve type:'HEAD'

### ISSUE THREAD

**Issue by ShortBusKing** [servocoder/RichFilemanager#309]
**I use the following server-side connector (check one):**
- [x] ASP.NET Core connector by **sinanbozkus**

**My familiarity with the project is as follows (check one):**
- [x] I have used the project extensively, but have not contributed previously.
---

Angular-Cli does not serve type:'HEAD' by default in development. This change introduced a small new bug for those that use it.

[https://github.com/angular/angular-cli/issues/5170](https://github.com/angular/angular-cli/issues/5170
)
Current:
```
	// Test if a given url exists
	var file_exists = function(url) {
		return $.ajax({
			type: 'HEAD',
			url: url
		});
	};
```

Previously working in 2.7.0:
```
        // Test if a given url exists
        var file_exists = function(url) {
            return $.ajax({
                type: 'GET',
                url: url
            });
        };

```

**Comment by servocoder** [comment]
It's not appropriate to use GET request just to check whether file exists. JS script code will stay with HEAD request. Try to modify the middleware to make it accept HEAD as discribed in https://github.com/webpack/webpack-dev-server/issues/924#issuecomment-313613266
