### ISSUE TITLE
JSON error on preview PDF's

### ISSUE THREAD

**Issue by RRangioni** [servocoder/RichFilemanager#311]
previous issue: https://github.com/servocoder/RichFilemanager/issues/298
Issue still not resolved, but maybe can you help me with this one? 

When you see the url for the PDF preview ( https://db.ducdiving.com/rfm-org/connectors/php/filemanager.php?mode=readfile&path=%2file.pdf&time=1522749916044 ) i can now see an error when debugging the response:

SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

Request method: HEAD
Remote address: 145.111.154.152:443
Status code: 500 Internal Server Error
Version: HTTP/1.1

It looks like there is no data at all.
Have you seen this before?

**Comment by RRangioni** [comment]
Just added PDF as an iFRAME extension in the JSON file.
Now its working. 

        "iframe": {
            "enabled": true,
            "extensions": [
                "htm",
                "html",
                "pdf"
            ],
            "readerWidth": "95%",
            "readerHeight": "600"
        },

**Comment by servocoder** [comment]
It's working because, in case of "iframe" viewer, PDF file is previewed with browser built-in viewer. This is ok for you, but I'm curios why PDF file preview doen't work for "opendoc" viewer. 

Do you utilize the latest (2.7.5) version of RFM? You can also try to update `servocoder/richfilemanager-php` package with `composer update` command. The latest version is "1.2.4"

**Comment by RRangioni** [comment]
Yes, running 2.7.5 and already updated everything. 2.7.5 and 1.2.4 are running on my server.

**Comment by ShortBusKing** [comment]
When visiting your link in the browse, I get an error
{"errors":[{"id":"server","code":"500","title":"FILE_DOES_NOT_EXIST","meta":{"arguments":["\\/ile.pdf"]}}]}

Notice your path variable starts with %2f which looks for the file "\\/ile.pdf"

filemanager.php?mode=readfile&path=**%2f**ile.pdf&time=1522749916044

**Comment by hathemi** [comment]
"PDF file preview doen't work for "opendoc" viewer." @servocoder  is there a solution for this ? 
i can displat .txt files. with  pdf files always get "Failed to load resource MissingPDFException "
