### ISSUE TITLE
Alternative to google's file viewer?

### ISSUE THREAD

**Issue by ShortBusKing** [servocoder/RichFilemanager#312]
**I use the following server-side connector (check one):**
- [x] ASP.NET Core connector by **sinanbozkus**

**My familiarity with the project is as follows (check one):**
- [x] I have used the project extensively, but have not contributed previously.
---

Hello, 
I have a question for you. While previewing a doc, docx, xls, etc with the google viewer, I noticed it requires direct access to the file from the internet. For security reasons, I'm not sure if I will be able to get that to happen on my production site. 

What would you suggest for viewing those file without the use of google's (or any) external API?

What is your opinion of this package?
https://www.npmjs.com/package/filepreview

Thanks for your time

**Comment by servocoder** [comment]
Unfortunately, I can't see an alternative. The package you referred declares the following:

> Will generate a file preview (gif, jpg or png) of about 450 different document formats.

As far as I have understood it just creates a preview image from a vide range of files. And it is lasts quite long. I wonder if you can suggest another use case of this package and, even better, experienced with it.

**Comment by servocoder** [comment]
I see. I don't really like the idea of generation extra resources (images) in order to preview files. But it's may be considered in the future as an alternative viewer. Anyhow thanks for sharing this package.
