### ISSUE TITLE
no preview available

### ISSUE THREAD

**Issue by palay** [servocoder/RichFilemanager#317]
in my local xampp, while I opened file docx, odc, rtf, anything like that, always appear no preview available, how this solve the problem ?

Please Help.. Thanks

**Comment by servocoder** [comment]
See the similar issues: https://github.com/servocoder/RichFilemanager/issues/284 https://github.com/servocoder/RichFilemanager/issues/312

**Comment by palay** [comment]
Thanks, solved.. :), but while I opened to file rtf, and doc, no preview available. Whats this problem ?

**Comment by servocoder** [comment]
Look the `viewer` section of your `filemanager.config.json`

The "doc" is listed under `viewer.google` section, but as far as I remember google viewer doesn't work at localhost. Once you host your project at remote server it should be fine.

The "rtf" is not listed in any of viewers and I doubt it's supported by any. Perhaps `viewer.google` can handle it, but not locally, again.
