### ISSUE TITLE
Clicking the "Go to parent Folder" button takes me to the root folder

### ISSUE THREAD

**Issue by JoeyWasHere** [servocoder/RichFilemanager#319]
**I use the following server-side connector (check one):**
- [x] ASP.NET Core connector by **sinanbozkus**

**My familiarity with the project is as follows (check one):**
- [x] I am an active contributor to the project.
---

When clicking the "Go to parent Folder" button, it takes me to the root folder. Could this be a bug with the ASP.Net Core connector or is this something the javascript side should check for? 

Example:
If I'm in the current working folder "/d/subfolder1/", the parent button will take me to the root instead of "/d".

The root cause is because the model.currentPath() returns 'd/subfolder1', while the code looks for two slashes. Since there is only one, the return string will be empty with a added "/" to indicate the root folder.

```
                this.navLevelUp = function() {
                    debugger;
                    var parentFolder = model.previewFile() ?
                        getDirname(model.previewModel.rdo().id) :
                        getParentDirname(model.currentPath() + '/');  <!--- the correct path is returned when adding a "/" -->

                    if (model.previewFile()) {
                        model.previewFile(false);
                    }

                    if (parentFolder !== model.currentPath()) {
                        model.itemsModel.loadDataList(parentFolder);
                    }
                };
```

Thanks for your time.

**Comment by servocoder** [comment]
Oh, this is exactly what I was talking about, when mentioned that absence of leading slash in path may my be the cause of implicit issues. You would better to prepend paths with leading slashes in all responses of the connector to avoid such surprises. Is this a problem? Could this be a problem?
