### ISSUE TITLE
Error in libs-main.js when trying to load index.html

### ISSUE THREAD

**Issue by ojaynico** [servocoder/RichFilemanager#320]
Uncaught Error: E_INVALID_PAR_TYPE: {"expected":"Plain Object","name":"json","value":"{\n  \"main\": {\n    \"en\": {\n      \"identity\": {\n        \"version\": {\n          \"_number\": \"$Revision: 13744 $\",\n          \"_cldrVersion\": \"32.0.1\"\n        },\n        \"language\": \"en\"\n      },\n      \"dates\": {\n        \"calendars\": {\n          \"gregorian\": {\n            \"months\": {\n              \"format\": {\n                \"abbreviated\": {\n                  \"1\": \"Jan\",\n                  \"2\": \"Feb\",\n                  \"3\": \"Mar\",\n                  \"4\": \"Apr\",\n                  \"5\": \"May\",\n                  \"6\": \"Jun\",\n                  \"7\": \"Jul\",\n                  \"8\": \"Aug\",\n                  \"9\": \"Sep\",\n                  \"10\": \"Oct\",\n                  \"11\": \"Nov\",\n                  \"12\": \"Dec\"\n                },\n                \"narrow\": {\n                  \"1\": \"J\",\n                  \"2\": \"F\",\n                  \"3\": \"M\",\n                  \"4\": \"A\",\n                  \"5\": \"M\",\n                  \"6\": \"J\",\n                  \"7\": \"J\",\n                  \"8\": \"A\",\n                  \"9\": \"S\",\n                  \"10\": \"O\",\n                  \"11\": \"N\",\n                  \"12\": \"D\"\n                },\n                \"wide\": {\n                  \"1\": \"January\",\n                  \"2\": \"February\",\n                  \"3\": \"March\",\n                  \"4\": \"April\",\n                  \"5\": \"May\",\n                  \"6\": \"June\",\n                  \"7\": \"July\",\n                  \"8\": \"August\",\n                  \"9\": \"September\",\n                  \"10\": \"October\",\n                  \"11\": \"November\",\n                  \"12\": \"December\"\n                }\n              },\n              \"stand-alone\": {\n                \"abbreviated\": {\n                  \"1\": \"Jan\",\n                  \"2\": \"Feb\",\n                  \"3\": \"Mar\",\n                  \"4\": \"Apr\",\n                  \"5\": \"May\",\n                  \"6\": \"Jun\",\n                  \"7\": \"Jul\",\n                  \"8\": \"Aug\",\n                  \"9\": \"Sep\",\n                  \"10\": \"Oct\",\n                  \"11\": \"Nov\",\n                  \"12\": \"Dec\"\n                },\n                \"narrow\": {\n                  \"1\": \"J\",\n                  \"2\": \"F\",\n                  \"3\": \"M\",\n                  \"4\": \"A\",\n                  \"5\": \"M\",\n                  \"6\": \"J\",\n                  \"7\": \"J\",\n                  \"8\": \"A\",\n                  \"9\": \"S\",\n                  \"10\": \"O\",\n                  \"11\": \"N\",\n                  \"12\": \"D\"\n                },\n                \"wide\": {\n                  \"1\": \"January\",\n                  \"2\": \"February\",\n                  \"3\": \"March\",\n                  \"4\": \"April\",\n                  \"5\": \"May\",\n                  \"6\": \"June\",\n                  \"7\": \"July\",\n                  \"8\": \"August\",\n                  \"9\": \"September\",\n                  \"10\": \"October\",\n                  \"11\": \"November\",\n                  \"12\": \"December\"\n                }\n              }\n            },\n            \"days\": {\n              \"format\": {\n                \"abbreviated\": {\n                  \"sun\": \"Sun\",\n                  \"mon\": \"Mon\",\n                  \"tue\": \"Tue\",\n                  \"wed\": \"Wed\",\n                  \"thu\": \"Thu\",\n                  \"fri\": \"Fri\",\n                  \"sat\": \"Sat\"\n                },\n                \"narrow\": {\n                  \"sun\": \"S\",\n                  \"mon\": \"M\",\n                  \"tue\": \"T\",\n                  \"wed\": \"W\",\n                  \"thu\": \"T\",\n                  \"fri\": \"F\",\n                  \"sat\": \"S\"\n                },\n                \"short\": {\n                  \"sun\": \"Su\",\n                  \"mon\": \"Mo\",\n                  \"tue\": \"Tu\",\n                  \"wed\": \"We\",\n                  \"thu\": \"Th\",\n                  \"fri\": \"Fr\",\n                  \"sat\": \"Sa\"\n                },\n                \"wide\": {\n                  \"sun\": \"Sunday\",\n                  \"mon\": \"Monday\",\n                  \"tue\": \"Tuesday\",\n                  \"wed\": \"Wednesday\",\n                  \"thu\": \"Thursday\",\n                  \"fri\": \"Friday\",\n                  \"sat\": \"Saturday\"\n                }\n              },\n              \"stand-alone\": {\n                \"abbreviated\": {\n                  \"sun\": \"Sun\",\n                  \"mon\": \"Mon\",\n                  \"tue\": \"Tue\",\n                  \"wed\": \"Wed\",\n                  \"thu\": \"Thu\",\n                  \"fri\": \"Fri\",\n

**Comment by servocoder** [comment]
1. What connector are you using?
2. Have you modified configuration in any way?
3. What exactly have been modified? Provide your configuration.
4. Outline steps to reproduce the issue.

**Comment by ojaynico** [comment]
I am using php connector.
Renamed filemanager.config.default.json -> filemanager.config.json
Renamed filemanager.init.js.example -> filemanager.init.js
Basically that's all i did.
I tried if with and without codeigniter framework but get the same error.

**Comment by servocoder** [comment]
That's odd.
I found a similar issue has been reported at cldrjs repo: https://github.com/rxaviers/cldrjs/issues/52#issuecomment-385240158

However I can't reproduce it any way.
Let me know if you will find a solution or a way to reproduce the issue.

**Comment by sebastianrozmus** [comment]
Sorry for posting for such an old issue. I have found the solution for that. You have to re-upload the libs directory and it should work.

**Comment by Draghmar** [comment]
I also have this issue...even though I didn't have it before. I'm not sure what do you mean by 're-uploading' @sebastianrozmus ? Like taking libs folder and uploading into my project? Because I did this and it didn't work.

**Comment by sebastianrozmus** [comment]
Yes I have removed libs directory and uploaded it again and it worked for me.

**Comment by Draghmar** [comment]
Ok, so it's weird...Maybe your re-uploaded folder had some different version of the lib that causes the issue?
