### ISSUE TITLE
error send file with aws s3

### ISSUE THREAD

**Issue by oOojhonnyoOo** [servocoder/RichFilemanager#322]
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [ ] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [ ] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [ ] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [x] PHP connector by **servocoder**
- [ ] Java connector by **fabriceci**
- [ ] Python3 Flask connector by **jsooter**
- [ ] Python3 Flask connector by **stevelittlefish**
- [ ] NodeJs connector by **jlaustill** and **forestlake**
- [ ] ASP.NET Core connector by **sinanbozkus**
- [ ] ASHX connector by **richeflits**
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [x] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

![image](https://user-images.githubusercontent.com/13945258/40193870-f9674730-59de-11e8-9a47-8f4321e8f7ec.png)

i dont know what happen... i follow all the configurations using php connector with integration aws s3, but when i want upload a file or generate a thumbnail the system make a error...

that is my log .:
[2018-05-17 17:12:07]#127.0.0.1# - loading image "s3://arquivos-jobb/arquivos/mutato/images/01244_CEN03_V02_CALCULO(1).png"
[2018-05-17 17:12:08]#127.0.0.1# - generating thumbnail "s3://arquivos-jobb/arquivos/mutato/_thumbs2/images/01244_CEN03_V02_CALCULO(1).png"
[2018-05-17 17:12:11]#127.0.0.1# - Error code: NOT_ALLOWED_SYSTEM, meta: {"arguments":[]}

and that is my connectors/php/filemanager.php .:

$configS3 = [
    "logger" => [
        "enabled" => true,
        "file" => '/home/developer/Música/log.txt',
    ],
    "options" => [
        "serverRoot" => true,
        "fileRoot" => false,
        "fileRootSizeLimit" => false,
        "charsLatinOnly" => false,
    ],
    "security" => [
        "readOnly" => false,
        "normalizeFilename" => true,
        "extensions" => [
            "policy" => "ALLOW_LIST",
            "ignoreCase" => true,
            "restrictions" => ["","jpg","jpe","jpeg","gif","png","svg","txt","pdf","odp","ods","odt","rtf","doc","docx","xls","xlsx","ppt","pptx","csv","ogv","avi","mkv","mp4","webm","m4v","ogg","mp3","wav","zip","md",
            ],
        ],
        "patterns" => [
            "policy" => "DISALLOW_LIST",
            "ignoreCase" => true,
            "restrictions" => [
                "*/.htaccess",
                "*/web.config",
                "*/.CDN_ACCESS_LOGS/*",
            ],
        ],
        "symlinks" => [
            "allowAll" => false,
            "allowPaths" => [],
        ],
    ],
    "upload" => [
        "fileSizeLimit" => 16000000,
        "overwrite" => true,
        "paramName" => "upload",
    ],
    "images" => [
        "main" => [
            "autoOrient" => true,
            "maxWidth" => 1280,
            "maxHeight" => 1024,
        ],
        "thumbnail" => [
            "enabled" => true,
            "cache" => true,
            "dir" => "_thumbs/",
            "crop" => true,
            "maxWidth" => 64,
            "maxHeight" => 64,
        ]
    ],
    "mkdir_mode" => 0755,
];

$configS3['images']['thumbnail']['useLocalStorage'] = false;
$configS3['allowBulk'] = true;
$configS3['aclPolicy'] = \RFM\Repository\S3\StorageHelper::ACL_POLICY_DEFAULT;
$configS3['encryption'] = null;
$configS3['credentials'] = [
    'region' => 'us-east-1',
    'bucket' => 'xxx',
    'endpoint' => null,
    'credentials' => [
        'key' => 'xxx',
        'secret' => 'xxx,
    ],
    'options' => [
        'use_path_style_endpoint' => false,
    ],
    'defaultAcl' => \RFM\Repository\S3\StorageHelper::ACL_PUBLIC_READ,
    'debug' => false,
];

$app = new \RFM\Application();
$s3  = new \RFM\Repository\S3\Storage($configS3);
$s3->setRoot('my_file_inside_the_bucket', true);
$app->setStorage($s3);
$app->api = new RFM\Api\AwsS3Api(); 

$app->run();

i am crazy i dont know what i need to do..

**Comment by servocoder** [comment]
The issue may be caused by AWS S3 policies.

First you have to make sure that you can upload files to S3 directly.

Try to upload your files with AWS CLI, being authorized with the same AWS credentials and settings that your have spefified  at RFM. https://aws.amazon.com/cli/

**Comment by servocoder** [comment]
Try the latest fix of PHP connector: https://github.com/servocoder/RichFilemanager-PHP/pull/48/files

Let me know if this helps for your case.

**Comment by talaysa** [comment]
I had same issue, later i realized, issue is related with DefaultACL. You have same attribute also in your setting, 
'defaultAcl' => \RFM\Repository\S3\StorageHelper::**ACL_PUBLIC_READ**,

You need give right for read and write.
'defaultAcl' => \RFM\Repository\S3\StorageHelper::**ACL_BUCKET_OWNER_FULL_CONTROL**,

This is from 2018, probably you solved issue but maybe someone can have same problem like us.
