### ISSUE TITLE
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in 

### ISSUE THREAD

**Issue by faab007** [servocoder/RichFilemanager#323]
I get An error:

Server error. 
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\atelierblinq\login\connectors\php\filemanager.php on line 14

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\atelierblinq\login\connectors\php\filemanager.php on line 14
Unable to perform initial request to server.

**Comment by servocoder** [comment]
You have to install PHP connector package as described at https://github.com/servocoder/RichFilemanager/wiki/PHP-connector

Take a time to read the docs thoroughly.

**Comment by faab007** [comment]
still getting the error.

Can you send me an copy of a already configured version!

**Comment by tim-moody** [comment]
I still had this error after running composer create-project --prefer-dist servocoder/richfilemanager filemanager as per the docs ( which I read many times)

running composer update fixed it. The docs could be clearer on the need to do this.

**Comment by faab007** [comment]
how do i run it

**Comment by tim-moody** [comment]
cd to directory where the RFM git repo was pulled and type
composer update

**Comment by faab007** [comment]
?

**Comment by tim-moody** [comment]
sorry, looks like you're on windows. the commands I gave are for linux.

**Comment by servocoder** [comment]
have you installed the [Composer](https://getcomposer.org/Composer-Setup.exe) for Windows?

**Comment by faab007** [comment]
now i have

**Comment by servocoder** [comment]
There is a topic at StackOverflow: https://stackoverflow.com/questions/40545795/how-do-i-install-composer-php-packages-without-composer

Also you can try the https://github.com/Wilkins/composer-file-loader package, as suggested is the StackOverflow discussion
