### ISSUE TITLE
nodejs connector help

### ISSUE THREAD

**Issue by tim-moody** [servocoder/RichFilemanager#327]
The php connector works well.
But I want permissions on files other than what apache/php has.
So I would like to use nodejs.

Learning Curve:
I followed instructions from https://github.com/dekyfin/RichFilemanager-NODE and did not use https://github.com/servocoder/RichFilemanager/tree/master/connectors/nodejs either code or instructions.
I finally realized that there is no server wrapper supplied so copied what is given under Usage above.
I modified RFM-Node to point to the config file in RFM and changed:
    "api": {
        "lang": "nodejs",
(I originally changed "connectorUrl" to host:9000/filemanager" but got cross site scripting error so proxied with apache instead)

Now if I start my app (node_connector.js) with node it runs and displays initialization output when I connect to RFM with a browser (chrome, latest)

But I get an error:

Uncaught TypeError: Cannot read property 'readOnly' of undefined
    at initialize (filemanager.js:447)
    at filemanager.js:247
    at e (libs-main.js:9)
    at libs-main.js:9

(Note I changed /RichFilemanager/index.html to use the unminified src/js/filemanager.js to try to troubleshoot, but libs-main.js is beyond me.)

**In raising this issue, I confirm the following (please check boxes):**

- [X ] I have read  the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [X ] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X ] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [ X] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [ ] PHP connector by **servocoder**
- [ ] Java connector by **fabriceci**
- [ ] Python3 Flask connector by **jsooter**
- [ ] Python3 Flask connector by **stevelittlefish**
- [ ] NodeJs connector by **jlaustill** and **forestlake**
- [ ] ASP.NET Core connector by **sinanbozkus**
- [ ] ASHX connector by **richeflits**
- [X ] Other (specified below)
see above
**My familiarity with the project is as follows (check one):**

- [X ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

{issue content here}

**Comment by codehunter12345** [comment]
@tim-moody  I added a new property :   `"security" : {},`  into the filemanager.config.json  file. 
Problem solved!!
