### ISSUE TITLE
Rename directory error

### ISSUE THREAD

**Issue by jlaustill** [servocoder/RichFilemanager#33]
When trying to rename a Directory it is giving the following error.

File type is not allowed.
Only following files are allowed: jpg, jpe, jpeg, gif, png, svg, txt, pdf, odp, ods, odt, rtf, doc, docx, xls, xlsx, ppt, pptx, csv, ogv, avi, mkv, mp4, webm, m4v, ogg, mp3, wav, zip, rar.

**Comment by servocoder** [comment]
Hmm, I can't reproduce it in any way. Where did you get that error? Which the connector was?

**Comment by jlaustill** [comment]
I'm only getting this error on the newest master branch, using my nodejs connector.  But the connector isn't even getting a request.  I'll step through the code today and see I can figure out where it's going wrong :)

**Comment by jlaustill** [comment]
Ok, I figured out what is causing this.  The function 
```javascript
// Test if path is dir
var isFile = function(path) {
	return path.charAt(path.length - 1) != '/';
};
```
on line 407.  When you normalize a path in nodejs and it is a directory, it will not include a trailing slash.  I think there is a much better way to deal with this since we are also passing back a 'File Type'.

I would write a new function called _$.isFile and take the entire object, first checking if file type = "dir", and if not, checking for a trailing slash to be robust.  If the api errors and sends a path with an incorrect file type, it will still work in this case.  

This function is used 12 times in filemanager.js, so that is 12 places for this bug to pop up.  

I would start with something like this
```javascript
_$.isFile = function(file) {
    if (file["File Type"] === "dir") {
        return false;
    } else {
        return (file["Path"].charAt(file["Path"].length - 1) !== "/");
    }
}
```

**Comment by servocoder** [comment]
This is not a solution and I'm not going to change `isFile` function, because there are a lot of places where I check `isFile` without the whole response object. There is a standard we have that all folder paths should end with trailing slash. You have to modify your connector to return correct paths for folders.

**Comment by servocoder** [comment]
But we are able to extend conditions like `!isFile(path) && data["File Type"] === "dir"` AND `isFile(path) && data["File Type"] !== "dir"` for the places where we have `data` object with "File Type" param, or create a new function for that purpose, but not to rewrire `isFile` function

**Comment by servocoder** [comment]
Anyway you should add trailing slash for each folder path in your connector

**Comment by servocoder** [comment]
The new API specifies that trailing slash is mandatory for folders.
