### ISSUE TITLE
only ja-json wouldn't mirrored.

### ISSUE THREAD

**Issue by Ganariya** [servocoder/RichFilemanager#332]
**In raising this issue, I confirm the following (please check boxes):**

- [☑️ ] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [ ☑️] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [☑️ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [☑️ ] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [☑️ ] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [☑️ ] PHP connector by **servocoder**
- [ ] Java connector by **fabriceci**
- [ ] Python3 Flask connector by **jsooter**
- [ ] Python3 Flask connector by **stevelittlefish**
- [ ] NodeJs connector by **jlaustill** and **forestlake**
- [ ] ASP.NET Core connector by **sinanbozkus**
- [ ] ASHX connector by **richeflits**
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [☑️ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

 Hello, My name is ganariya.
 I'm a student in Akita University in Japan.

 I want to ask and report bug.

 What I want to do is creating pop-up which says "Are you OK? If you delete this image file, you wouldn't see on this server." , when a user would try to delete image file.
 So, firstly, I tried to language file such that "ja.json" in languages file. And, I rewrote  「 "confirm_delete": "Are you OK? If you delete this image file, you wouldn't see on this server. (本当によろしいですか？もし画像ファイルを削除した場合、このサーバーから見る事が出来なくなります。)",」

However, when I rewrote this sentence and reset server again and again, ja-file wasn't  mirrored.  Other countries language files, for example en.json it.json, the change was mirrored. So, only ja.json wasn't mirrored in change.

Why wasn't only ja-json changed? Is this bug?
And, If I want to make pop-up, which says "Are you OK? If...." ,when a picture is selected and will be deleted, what file do I change?

Thank you very much.
This filesystem is so user-friendly,  I'm so happy.
I want to become to be able to make this great software, because I wrote 5000 steps software.

**Comment by servocoder** [comment]
I was able to reproduce the issue. It comes down to caching previous version of lang files by browser. If you prevent browser caching (in Chrome dev tools console e.g.) the changes are mirrorred as expected. Yet I have commited a fix to prevent the caching.
