### ISSUE TITLE
Search for partial file names

### ISSUE THREAD

**Issue by hhjung2013** [servocoder/RichFilemanager#336]
Is it possible to make the search feature look for files that contain the searched text anywhere in its name? Currently it only finds files if the name starts with the searched text.

**Comment by servocoder** [comment]
File search by wildcard pattern is already implemented at the `master` branch, but not released yet. Refer to issue #334. This one is closed as duplicate.

**Comment by hhjung2013** [comment]
Good to know the feature is coming. Thanks!
