### ISSUE TITLE
API Wiki update

### ISSUE THREAD

**Issue by jlaustill** [servocoder/RichFilemanager#34]
I don't have update permissions on the wiki, so here's what I added this morning, you can review and post to your liking :)
[API.zip](https://github.com/servocoder/RichFilemanager/files/418563/API.zip)

**Comment by servocoder** [comment]
Thank you. I have added most of your noted, and extended the API with new examples, specified request method (GET|POST) and so on. Check it out.

**Comment by jlaustill** [comment]
That looks great!  We all hate documenting, but it's sure nice to have moving forward.

**Comment by servocoder** [comment]
Right. And the API should be modified after you manage with #37
By the way we don't need to put `time` param for each request. It was initially added to prevent images from caching, so I believe we have to revise `time` and `config` params. Take a look on that while you work on #37.

**Comment by jlaustill** [comment]
I was wondering what the purpose was of the time, I completely ignored it so far in my nodejs api :)  I also ignored the config param and used a local copy for now assuming we would move towards separated config for api/ui.  

We will have to work through each endpoint for #37 , and I think updating the documentation should probably be done in the repo until that version ships, or we should clearly label each section with current version looks like this, next version looks like this.  I'm good either way.  I'd like to hear your thoughts on that.

**Comment by servocoder** [comment]
Sure it will work without these params in the basic implementation, but it doesn't mean that they are useless.  FM is a powerful plugin which can change it behaviour depending on configuration. So if `time` and `config` params exists I strongly believe they can take an effect in some case. As I said above `time` is definetely prevent images from caching. Don't ignore those params.

**Comment by jlaustill** [comment]
I won't ignore them once I understand their purpose, I promise :)

**Comment by servocoder** [comment]
Done. For any following questions and discussions go to #37
