### ISSUE TITLE
trigger readfolder/folder change on client side 

### ISSUE THREAD

**Issue by nicpillinger** [servocoder/RichFilemanager#345]
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [x] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [x] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [ ] PHP connector by **servocoder**
- [ ] Java connector by **fabriceci**
- [ ] Python3 Flask connector by **jsooter**
- [ ] Python3 Flask connector by **stevelittlefish**
- [ ] NodeJs connector by **jlaustill** and **forestlake**
- [ ] ASP.NET Core connector by **sinanbozkus**
- [ ] ASHX connector by **richeflits**
- [x] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

Hello - I'm wondering if there is any sort of client side api for this project? I want to try and trigger a readfolder action from the client (without having to reload the DOM/markup again) - is there any way to interact with the plugin client-side?

thanks

**Comment by servocoder** [comment]
Yes, it's exists. It's not the client side API actually, but rather a few public methods of RichFilemanager jQuery plugin. They are well described [here](https://github.com/servocoder/RichFilemanager/issues/275#issuecomment-355776557). I think that's exactly what you need.

**Comment by nicpillinger** [comment]
Hi @servocoder the loadFolder method is great but it doesn't allow me a way of opening the root folder, if I pass it "/" its trying to load "//" which isn't correct. I think its a simple change to the loadFolder so it doesn't always wrap the folder name you're trying to load?

**Comment by servocoder** [comment]
Merged the fix in PR #346. Thanks!
