### ISSUE TITLE
Directory's pulling wrong icon

### ISSUE THREAD

**Issue by jlaustill** [servocoder/RichFilemanager#36]
The code is checking for a file extension, and then using that + '.png' for the icon.  Directories don't have an extension, so it's trying to pull .png, which doesn't exist.  Changing line 554 to 

`var fileType = data["File Type"] === "dir" ? "_Open" : getExtension(data['Path']);`

Fixes it for me, but I'm not sure that hard coding the _Open is the proper solution.

**Comment by servocoder** [comment]
Should be fixed at the moment. Feel free to reopen this issue if it still seems buggy for you.
