### ISSUE TITLE
Standardize API's responses following the REST api json standard

### ISSUE THREAD

**Issue by servocoder** [servocoder/RichFilemanager#37]
[Original description](https://github.com/servocoder/RichFilemanager/issues/31#issuecomment-239972774) from @jlaustill.

**Comment by servocoder** [comment]
PHP connector got all actions standardized at the dev branch at the moment. API section in wiki should be adjusted after the merge to the master branch.

**Comment by servocoder** [comment]
I am pleased to present the new completely rewritten and standardized [Rich Filemanager API](https://github.com/servocoder/RichFilemanager/wiki/API) that follows [JSON API](http://jsonapi.org/) best practices. Note that it works only for the [DEV] (https://github.com/servocoder/RichFilemanager/tree/dev) branch at the moment.

@jlaustill, @simogeo, @fabriceci, @gmkll 
Your notes and critics are welcome.

**Comment by servocoder** [comment]
The only thing I didn't change is a request type of methods. For my opinion the following methods should be performed with POST method: "addfolder", "rename", "move", "delete". Note that I don't consider PUT and DELETE methods intentionally. Only GET and POST ones.

**Comment by simogeo** [comment]
Clear and efficient. Sounds great to me.
I agree regarding POST method. No need to change them.

I'll try to test the dev branch soon

**Comment by servocoder** [comment]
Closed with the release RichFilemanager v.2.0.0
