### ISSUE TITLE
more feature req for rf 

### ISSUE THREAD

**Issue by mexantos** [servocoder/RichFilemanager#38]
i want developer have a plan for implementing more features to RichFM
- easy drag and drop for moving file
- multiple selection for bulk action
- enable create a new file ie txt file
- zip unzip features
- more user friendly and modern ui 
- better preview for document file ie doc, docx, pdf, i have issue with doc file where no preview available.

last
how can i support for epub file and enable preview available.

thank

**Comment by servocoder** [comment]
Hi, most from your list are already in the roadmap. Currently there is no support for `epub` preview. Only images, media files and docs. I try to explore is there any tool to handle `epub`, but it will not be too soon. Thanks for the ideas and for the reporting of the issues.

**Comment by servocoder** [comment]
@mexantos selectable items and multiple actions (move, devele and upload) are now implemented at ["selectable" branch](https://github.com/servocoder/RichFilemanager/tree/selectable). You could download and check it now. Let me know if it works for you. Any feed back is appreciated.

**Comment by servocoder** [comment]
Selectable items and multiple actions released in v2.1.0
Leave this issue open as a reminder about other features request.

**Comment by servocoder** [comment]
All thing from the list are implemented except this one:

> enable create a new file ie txt file

Zip / unzip feature relies on the server-side connector and can't be provided as reliable mechanism

Creating new files is not planned for the near future.
