### ISSUE TITLE
No thumbs

### ISSUE THREAD

**Issue by prcboris** [servocoder/RichFilemanager#386]
**In raising this issue, I confirm the following (please check boxes):**

- [*] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [*] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [*] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [*] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [*] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [*] PHP connector by **servocoder**
- [ ] Java connector by **fabriceci**
- [ ] Python3 Flask connector by **jsooter**
- [ ] Python3 Flask connector by **stevelittlefish**
- [ ] NodeJs connector by **jlaustill** and **forestlake**
- [ ] ASP.NET Core connector by **sinanbozkus**
- [ ] ASHX connector by **richeflits**
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [*] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

Hello
Install this project with AppServ.
No thumbs display.
![2019-03-17_13-01-39](https://user-images.githubusercontent.com/1506636/54489508-05373100-48be-11e9-8dfb-126aee356bea.png)
![2019-03-17_13-02-15](https://user-images.githubusercontent.com/1506636/54489509-05373100-48be-11e9-87e7-b4dabad45fad.png)

**Comment by tommus4444** [comment]
Hey i have the same problem, how did you resolved it ?  ( @servocoder can you help me ? )

**Comment by prcboris** [comment]
If you change default directory, create a new dir with name - "thumbs", like in default directory

**Comment by tommus4444** [comment]
Thanks you, but it's no working in my project - I use default folder _thumbs and images was generated but not displaying and this is laravel's project.
