### ISSUE TITLE
PDF reader is not working

### ISSUE THREAD

**Issue by simogeo** [servocoder/RichFilemanager#4]
Working with the latest commit, I get an error with PDF reader :  

>http://localhost/userfiles/My_folder/xxx.pdf

should be

> http://localhost/userfiles/RichFilemanager/My_folder/xxx.pdf

**Comment by servocoder** [comment]
Check the latest version, please.

**Comment by servocoder** [comment]
Hey @simogeo !
Were you able to check the fix?
The problem occured not only for PDF files, but for any other file types during preview attempts.
Hope it will be good now.
