### ISSUE TITLE
Copy URL and selectItem

### ISSUE THREAD

**Issue by simogeo** [servocoder/RichFilemanager#40]
@servocoder : for your information ! Could be useful also for RFM

https://github.com/simogeo/Filemanager/commit/809b3b23885f1aa628dc046c3e89e470b64a6152

regarding Copy Url to clipboard, I think providing a full URL is a must ...
regarding selectItem it could be an option ? what do you think ?

**Comment by servocoder** [comment]
Done within the latest commit on dev branch - full URL are copied now in case `abslutePath` config option is set to `true`.
