### ISSUE TITLE
symbolic link for userfiles

### ISSUE THREAD

**Issue by billyrennekamp** [servocoder/RichFilemanager#42]
i've been using a symbolic link for my userfiles directory that points to another part of my server.
it worked fine as the root but symbolic links inside the userfiles did not work.

my problem is that i want to use a mounted drive for storage on my server, but the symbolic link to this drive breaks the file manager. i get the "the file / does not exist" error.

any ideas?

**Comment by billyrennekamp** [comment]
solution was to use a bind mount

**Comment by servocoder** [comment]
Thank you for posting the solution.
