### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by djb15** [servocoder/RichFilemanager#43]
Hi, I am attempting to start the development of a python connector for this project however I cannot seem to start the project with a PHP server.  I am receiving the following errors in my browser: 
<img width="1279" alt="screen shot 2016-09-08 at 10 14 35" src="https://cloud.githubusercontent.com/assets/17380181/18343990/7bd6bc7c-75ad-11e6-8615-c7bc145c2eb1.png">
<img width="1274" alt="screen shot 2016-09-08 at 10 14 57" src="https://cloud.githubusercontent.com/assets/17380181/18343996/81a4ad4e-75ad-11e6-8d33-f5f1971d06a9.png">

When I load the page I initially get this GUI error also: 
<img width="1258" alt="screen shot 2016-09-08 at 10 15 16" src="https://cloud.githubusercontent.com/assets/17380181/18344013/929ea456-75ad-11e6-8e91-4aec2b5b67ea.png">

I am starting the simple server with the following terminal command although no errors appear in the terminal, just in the browser:
<img width="496" alt="screen shot 2016-09-08 at 10 15 36" src="https://cloud.githubusercontent.com/assets/17380181/18344098/d90328c2-75ad-11e6-9f84-15437332b692.png">

Any help would be much appreciated, thank you!

**Comment by servocoder** [comment]
Python connector is outdated.
The only up-to-date connector is PHP, also there are maintainers for Java and NodeJs connectors, which are in the development state currently. You could take a lead on Python connector and bring it into line with the latest changes, if you want.

**Comment by djb15** [comment]
Yeah the issue is I can't get the PHP connector to run correctly as shown above. I just want to investigate the working application before I start development of the Python connector.

**Comment by servocoder** [comment]
Hmm, I have just set it up and it works for me.
Do you use "master" branch? Because the "dev" branch may cause some issues at the moment.

**Comment by djb15** [comment]
Yes I'm using the master branch and starting the simple PHP server from the root directory.  If your setup is different to mine I would love to know! Thanks!

**Comment by servocoder** [comment]
It should be good for your case.
Have you created "filemanager.config.json" file based on the "filemanager.config.default.json"?
Also change "filemanager.min.js" to "filemanager.js" in the "index.html" file to see which line is corrupted.

**Comment by djb15** [comment]
Yes I've duplicated and renamed the default filemanager config file.  After changing to "filemanager.js" in the "index.html" I receive the following error and a endless loading screen:
<img width="1279" alt="screen shot 2016-09-08 at 11 20 52" src="https://cloud.githubusercontent.com/assets/17380181/18346106/910cb3e0-75b6-11e6-94f3-ae8ae63a88ed.png">

This is both with the "filemanager.config.json" settings with server root set as true and as false with a fileRoot path set.

**Comment by servocoder** [comment]
Perhaps it's browser related bug. I may suppose this issue is related to sync ajax requests which were deprecated for some time. I am currently working on that problem at the dev branch. What is your browser name and version?

**Comment by djb15** [comment]
I'm using Safari 9.1.2.  Which browser should I use for development at the moment then? Chrome?

**Comment by servocoder** [comment]
Yeah, try Chrome please.

**Comment by djb15** [comment]
Apologies I'm still getting the same error with Chrome.  The issue is line 2342 of "filemanager.js" where it cannot read data of undefined which must mean that `loadedFolderData[path]` is returning no value.  My "filemanager.config.json" is exactly the same as the default file so I'm not sure why this error is occurring.

**Comment by servocoder** [comment]
I have never tested it at the mac OS
Perhaps there is some issue with PHP server, I'm not sure.

Try to use XAMPP server:
https://sourceforge.net/projects/xampp/files/XAMPP%20Mac%20OS%20X/5.6.24/
https://www.apachefriends.org/faq_osx.html

**Comment by djb15** [comment]
Starting it with the XAMPP server doesn't help.  Must be a Mac OS issue.  I'll look into it a bit more

**Comment by servocoder** [comment]
Keep me in touch, please.
I will also let you know when the possible solution will be ready at the "dev" branch.

**Comment by billyrennekamp** [comment]
i'm running on mac using MAMP. i had the server error when serving from a symbolic link. what happens when you try to load /connectors/php/filemanager.php (maybe different spelling not looking at it directly right now). if working correctly i remember seeing two quotes. i was getting the server error when that page loaded as an error 500. if that's the case it should be a problem with your set up, i'd try running a simple index.php file from the same location and check your server logs. could be a permissions issue in the same vein.

**Comment by servocoder** [comment]
@djb15 Check out the latest commit on the master branch. Should be fixed

**Comment by servocoder** [comment]
But the real problem described at this thread:
http://stackoverflow.com/questions/16765158/date-it-is-not-safe-to-rely-on-the-systems-timezone-settings

You missed timezone setup in you php.ini for "date.timezone" directive

**Comment by djb15** [comment]
Yeah that is where I found the solution too but I wasn't sure about the php.ini file.  Where is that located or do I need to create my own one?

**Comment by servocoder** [comment]
For xampp it's located in [xampp_folder]/php/php.ini
