### ISSUE TITLE
User persmission

### ISSUE THREAD

**Issue by cpxo** [servocoder/RichFilemanager#45]
Hi-, as a (french ;-)) newbie, is it possible to tell me how to configure user/password permission with richfilemanager because I don't understand the section with auth() !!

Tks

**Comment by simogeo** [comment]
C'est très simple, il suffit de tester si ton utilisateur a les permissions suffisantes et de renvoyer `true` ou `false` selon le cas : 

```php

function auth()
{
   if($_SESSION['authenticated'])   return true;
   // ou if($_SESSION['authenticated'] && $_SESSION['isAdministrator'])   return true;
  else return false;
}
```

n'oublies pas d'initialiser ta session en amont avec `session_start()`.

**Comment by cpxo** [comment]
Merci pour la réponse (en français !!)

Par contre je suis un peu perdu sur (je suis n00b !!) :
* ce qui tu me propose doit se mettre à la place de auth() dans le fichier filemanager.php ?
* du coup où sont stockés les user/passwords ?
* et -- désolé pour la question... -- où place-t-on le session_start() ?

D'avance merci ^_^

**Comment by simogeo** [comment]
tu peux placer le session_start() au début du fichier [filemanager.php](https://github.com/servocoder/RichFilemanager/blob/master/connectors/php/filemanager.php)

Dans ce même fichier tu remplaces la fonction auth par celle que je vien de te  mettre en exemple. Mais dans cet exemple, cela implique que tu as déjà une base de donnée utilisateur / et un système d'authentification déjà existant. Par défaut le Filemanager ne gère pas les utilisateurs et leurs droits  - ce n'est pas son rôle !

**Comment by cpxo** [comment]
Ah ok, c'est donc cela qui me manque... 
Mes maigres connaissances ne vont pas me permettre de m'en sortir je crois... Au pire je vais passer par un htaccess ça sera déjà cela !

Merci en tout cas !!!
