### ISSUE TITLE
Copy URL to clipboard does not work

### ISSUE THREAD

**Issue by simogeo** [servocoder/RichFilemanager#5]
I get : 

> /My_folder/agriculture-adaptation.png

should be : 

> http://localhost/RichFilemanager/userfiles/My_folder/agriculture-adaptation.png

**Comment by servocoder** [comment]
I have an idea to utilize ZeroClipboard for the other purpose in the future release instead of copying file URL. I believe it will be more useful to copy-paste files/folders with ZeroClipboard like you used to doing in your OS.
