### ISSUE TITLE
File Manager is loading infinte

### ISSUE THREAD

**Issue by commanderinchief** [servocoder/RichFilemanager#50]
I can't load a filemanger because of filemanager is loading infinite.
I used code from filemanager.config.default.json.
Everythings is smooth and working in localhost running, but those error is coming after I uploaded to my Cpanel Webhosting server. I copied all file under the public folder to public_html and www folder.
But Still got an error.
Please help me solve this problem.
![error1](https://cloud.githubusercontent.com/assets/18343641/18748401/0e84f796-80f8-11e6-942b-ce5f289ddfd0.jpg)

**Comment by servocoder** [comment]
Hmm I can see you had the same problem with simogeo Filemanager. Is that right?
Browser console says that jquery has failed to load. Have you include all the html template with scripts? And do your project web accessible to take a look on it?

**Comment by commanderinchief** [comment]
Yes, servo
I also got an error with simogeo , so I changing to Rich Filemanager ..
I don't know what you describe "html template". please explain me. What is it?
I'm copied all of component to my web hosting .. 
My project is running smoothly at my local host, but crashing on web host.
I'm also don't know project web accessible what you said.
I'm newbiee .. pls help me.

**Comment by servocoder** [comment]
"project web accessible"
I wonder whether it's uploaded to some webhost so I will be able try it out myself. From your message I can see that it was. so give me the direct link to the page where Filemanager is accessible.

**Comment by commanderinchief** [comment]
Now, my problem is solved.. but I don't know how fix it. I'm deleted file manager folder and re-copied again to web server. Then it's running ... So amazing.... I'm still confusing about those problem. Thank your for your care. I'm really appreciate your care about our problem and your creating. Thank you.
