### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mokrea** [servocoder/RichFilemanager#51]
I downloaded, copied filemanager.config.json but server has been showing this error
Uncaught TypeError: Cannot read property 'data' of undefined

on return of the below function

       Qa = function(b) {
            if (!m[b] || Date.now() - m[b].cached > 2e3) {
                var c = {
                    mode: "getfolder",
                    path: b,
                    showThumbs: f.options.showThumbs
                };
                a.urlParam("type") && (c.type = a.urlParam("type")), a.ajax({
                    async: !1,
                    url: Y(c),
                    dataType: "json",
                    cache: !1,
                    success: function(a) {
                        m[b] = {
                            cached: Date.now(),
                            data: a
                        }
                    },
                    error: I
                })
            }
            return m[b].data
        },

**Comment by servocoder** [comment]
Please change "filemanager.min.js" to "filemanager.js" in index.html file, and repost the error once againg

**Comment by mokrea** [comment]
filemanager.js:2342 Uncaught TypeError: Cannot read property 'data' of undefined

**Comment by mokrea** [comment]
loadedFolderData[path] is undefined and path is /

**Comment by servocoder** [comment]
There was [similar issue](https://github.com/servocoder/RichFilemanager/issues/43) with loadedFolderData[path] is undefined, check it please.

**Comment by mokrea** [comment]
ok, thanks
