### ISSUE TITLE
After accessMediasFolder can be accessible but showing only loading images in Filemanager

### ISSUE THREAD

**Issue by hengsoheak** [servocoder/RichFilemanager#57]
I'm fresh new in bestmomo/Filemanager.1.1 in Laravel5.3.20 after install everthing work fine ever create and upload any images of folders. But I can't see any items in that bestmomo/filemanager dialog box.
I used as below configure

 <script>
        CKEDITOR.replace( 'textarea', {
            filebrowserBrowseUrl: '{!! url('filemanager/index.html') !!}',
            ImageBrowser : true,
            autoUpdateElement:true,
            //language:'km',

        });
    </script>

Assess url 

GET http://shop.dev/filemanager/scripts/filemanager.config.js.default?_=1477550701623
	
200 OK
		1ms	
jquery-....min.js (line 5)
GET http://shop.dev/filemanager/scripts/filemanager.config.js?_=1477550701624
	
200 OK
		1ms	
jquery-....min.js (line 5)
HEAD http://shop.dev/filemanager/scripts/languages/en.js
	
304 Not Modified
		2ms	
fileman....min.js (line 7)
GET http://shop.dev/filemanager/scripts/languages/en.js
	
200 OK
		1ms	
jquery-....min.js (line 5)
GET http://shop.dev/filemanager/themes/flat-dark/styles/ie.css
	
304 Not Modified
		15ms	
jquery-....min.js (line 5)
GET http://shop.dev/filemanager/scripts/zeroclipboard/dist/ZeroClipboard.js?_=1477550701625
	
200 OK
		1ms	
jquery-....min.js (line 5)
GET http://shop.dev/filemanager/scripts/CodeMirror/lib/codemirror.js?_=1477550701626
	
200 OK
		13ms	
jquery-....min.js (line 5)
GET http://shop.dev/filemanager/scripts/CodeMirror/addon/selection/active-line.js?_=1477550701627
	
200 OK
		1ms	
jquery-....min.js (line 5)
GET http://shop.dev/filemanager/scripts/CodeMirror/addon/display/fullscreen.js?_=1477550701628
	
200 OK
		10ms	
jquery-....min.js (line 5)
GET http://shop.dev/filemanager/scripts/CodeMirror/dynamic-mode.js?_=1477550701629
	
200 OK
		1ms	
jquery-....min.js (line 5)
GET http://shop.dev/filemanager/scripts/filemanager.liveSearch.min.js?_=1477550701630
	
200 OK
		1ms	
jquery-....min.js (line 5)
GET http://shop.dev/filemanager/scripts/dropzone/downloads/dropzone.js?_=1477550701631
	
200 OK
		10ms	
jquery-....min.js (line 5)
GET http://shop.dev/filemanager/scripts/custom-scroll...y.mCustomScrollbar.concat.min.js?_=1477550701632
	
200 OK
		1ms	
jquery-....min.js (line 5)
GET http://shop.dev/filemanager/connectors/php/filema...config.js&mode=getfolder&showThumbs=true&time=88
	
200 OK
		241ms	
jquery-....min.js (line 5)
GET http://shop.dev/filemanager/connectors/php/filema...onfig.js&mode=getfolder&showThumbs=true&time=189
	
200 OK
		234ms

**Result**

{"\/ice_screenshot_20160727-141539.png":{"Path":"\/ice_screenshot_20160727-141539.png","Filename":"ice_screenshot_20160727-141539.png","File Type":"png","Protected":0,"Preview":"connectors\/php\/filemanager.php?mode=preview&path=%2Fice_screenshot_20160727-141539.png&1477550702&thumbnail=true","Properties":{"Date Created":null,"Date Modified":"27 Oct 2016 05:31","Height":467,"Width":1117,"Size":36146,"filemtime":1477546271},"Error":"","Code":0},"\/Till_repayment.PNG":{"Path":"\/Till_repayment.PNG","Filename":"Till_repayment.PNG","File Type":"PNG","Protected":0,"Preview":"connectors\/php\/filemanager.php?mode=preview&path=%2FTill_repayment.PNG&1477550702&thumbnail=true","Properties":{"Date Created":null,"Date Modified":"27 Oct 2016 06:42","Height":558,"Width":897,"Size":14893,"filemtime":1477550567},"Error":"","Code":0},"\/ddddd\/":{"Path":"\/ddddd\/","Filename":"ddddd","File Type":"dir","Protected":0,"Preview":"images\/fileicons\/_Open.png","Properties":{"Date Created":"27 Oct 2016 05:36","Date Modified":"27 Oct 2016 05:36","filemtime":1477546608,"Height":null,"Width":null,"Size":null},"Error":"","Code":0},"\/My_folder\/":{"Path":"\/My_folder\/","Filename":"My_folder","File Type":"dir","Protected":0,"Preview":"images\/fileicons\/_Open.png","Properties":{"Date Created":"27 Oct 2016 05:32","Date Modified":"27 Oct 2016 05:32","filemtime":1477546324,"Height":null,"Width":null,"Size":null},"Error":"","Code":0},"\/sdfasdf\/":{"Path":"\/sdfasdf\/","Filename":"sdfasdf","File Type":"dir","Protected":0,"Preview":"images\/fileicons\/_Open.png","Properties":{"Date Created":"27 Oct 2016 05:34","Date Modified":"27 Oct 2016 05:34","filemtime":1477546469,"Height":null,"Width":null,"Size":null},"Error":"","Code":0}}
![as](https://cloud.githubusercontent.com/assets/812528/19757529/8af08398-9c4d-11e6-87cd-b2b23855b921.jpg)

**Comment by servocoder** [comment]
The bestmomo/Filemanager based on simogeo/Filemanager and the current Rich Filemanager is far away from the both of them. You should ask the author of the fork where you get it - bestmomo/Filemanager. This repo is a wrong place to ask about product of another author.

**Comment by hengsoheak** [comment]
Sorry I confuse
