### ISSUE TITLE
Why I got wrong images path in textarea 

### ISSUE THREAD

**Issue by hengsoheak** [servocoder/RichFilemanager#58]
I have used defualt configuration in Rich file Manager that feature work as well but when I insert the text to database I found the images src point to filemanager.php instead it really wrong for me.
Please help how to configur that path.

used in Laravel5.3.

http://stackoverflow.com/questions/40301124/why-rich-file-manager-insert-filemanager-config-json-instead-of-insert-image-to

**Comment by servocoder** [comment]
The version that you use (latest on master branch) builds preview urls via connector request path only. It was done because some users keep connector file separate from the client-side scripts (different servers and so on). After some discussions it was decided to support both options: absolute path (by default) and connector path (configurable). It's already implemented in [DEV branch](https://github.com/servocoder/RichFilemanager/tree/dev), so you can dowload it and try out. It should work for you.

But keep aware that there are lot of changes DEV branch it. For example you will find 2 config files: json config file (as you have it now) and new `config.php` file. The separation was done due to security reasons. At the moment you have to setup them independently, but in the release version it will be possible to override json config options with the appropriate ones from the php file (which are common for both files).

**Comment by hengsoheak** [comment]
my god I download master branch

**Comment by servocoder** [comment]
Sorry?
Anyhow you can download code from DEV branch and check it or wait for the next stable release.

**Comment by hengsoheak** [comment]
so mean that I can't used my current right everthing almost done I just stuck with this case.

**Comment by hengsoheak** [comment]
my god it is working right now.

Thanks

**Comment by servocoder** [comment]
Have you used DEV branch to make it work?

**Comment by hengsoheak** [comment]
Yes this is dev branch but just in my mac computer not yet upload to hosting yet but i think it may be work as well

**Comment by servocoder** [comment]
Hope so. Leave the feedback after you upload it to your hosting, please. It's important for me to know how the DEV branch goes and whether any problems exist.

**Comment by hengsoheak** [comment]
I got errors when I upload to the real hosting

Invalid URI. Load of media resource failed.
TypeError: can't access dead object
![screen shot 2559-10-27 at 7 41 13 pm](https://cloud.githubusercontent.com/assets/812528/19812971/d6a0772a-9d61-11e6-8858-9f715a1f279d.png)
<img width="716" alt="screen shot 2559-10-28 at 10 45 43 pm" src="https://cloud.githubusercontent.com/assets/812528/19812972/d6a16766-9d61-11e6-8c3e-f33749434911.png">
![Uploading Screen Shot 2559-10-28 at 10.45.50 PM.png…]()
<img width="1112" alt="screen shot 2559-10-28 at 10 55 44 pm" src="https://cloud.githubusercontent.com/assets/812528/19812973/d6a29d20-9d61-11e6-9a8f-8968ddde7a85.png">


when I brow any images it display as below
![screen shot 2559-10-28 at 11 04 30 pm](https://cloud.githubusercontent.com/assets/812528/19813243/f93821a6-9d62-11e6-94ab-05c7e3040beb.png)

**Comment by hengsoheak** [comment]
it simply laravel route not allow I'm not sure with the path in server and configuration

**Comment by servocoder** [comment]
You have to set path/url in your configuration files.

If your file is successully uploaded but the preview is failed then it can be routing problem.
In this case you need set "previewUrl" option in "filemanager.config.json" file as the absolute url to userfiles folder. For example "http://site.com/my/route/userfiles".

**Comment by hengsoheak** [comment]
It is be can't use RewriteCond %{REQUEST_URI} !^/userfiles

**Comment by servocoder** [comment]
I hardly understand what you are trying to say. Anyhow you should handle your routings yourself.

**Comment by hengsoheak** [comment]
oh sorry,

Now you can see the demo http://demo.swagkh.com/richfilemanager/ we can access it without route but

**Comment by hengsoheak** [comment]
I don't understand why I can't access to specify file name in this url

http://demo.swagkh.com/richfilemanager/userfiles/My_folder/Screen_Shot_2559-10-20_at_7.58.07_PM.png

But I can access 

http://demo.swagkh.com/richfilemanager/
As I read Laravel5.3 document they said all the folder which gain access from /Public/ folder not need to used route. however we found the images request errors on route method and it is really difficult for me to map route for his images.

**Comment by hengsoheak** [comment]
I think rich file manager  Master provide user authentication which can all use have authorize to access the file manager right?

**Comment by servocoder** [comment]
RichFilemanager on master branch have nothing specific to deal with authentication.
I can see you have already solved your problem? Preview of images works fine at your demo site.

**Comment by hengsoheak** [comment]
Yes it is work fine Because I edit the .htaccess which existing at 
userfiles folder
SetHandler none
SetHandler default-handler

Options -ExecCGI
#php_flag engine off
RemoveHandler .cgi .php .php3 .php4 .php5 .php6 .phtml .pl .py .pyc .pyo
<FilesMatch "\.(jpg|gif|png)$">
Order Deny,Allow
    Allow from all
</FilesMatch>

However to disabled php.flag engine is good technic or not I'm not sure about this.
Another one I want to set or use an authenticate for accessing to http://demo.swagkh.com/richfilemanager because now all user can access it. 

Thanks

**Comment by servocoder** [comment]
You could set authentication in [filemanager.php](https://github.com/servocoder/RichFilemanager/blob/dev/connectors/php/filemanager.php) file - auth() function. Return "true" if your user is granted to access, otherwise return "false".

**Comment by hengsoheak** [comment]
require_once('application/Fm.php');
require_once('application/FmHelper.php');

function auth()
{
    // IMPORTANT : by default Read and Write access is granted to everyone.
    // You can insert your own code over here to check if the user is authorized.
    // If you use a session variable, you've got to start the session first (session_start())
    return true;
}

$config = array();

// example to override the default config
//$config = array(
//    'security' => array(
//        'uploadPolicy' => 'DISALLOW_ALL',
//        'uploadRestrictions' => array(
//            'pdf',
//        ),
//    ),
//);

$fm = Fm::app()->getInstance($config);

// example to setup files root folder
//$fm->setFileRoot('userfiles', true);

// example to set list of allowed actions
//$fm->setAllowedActions(["select", "move"]);

$fm->handleRequest();
It is already tern to true.
I'm testing it now

**Comment by servocoder** [comment]
Sure it is. And as I said above you can set it to "false" for users which you want to disable access for.

**Comment by hengsoheak** [comment]
Awesome Rich File Manager when I understand it much easier

Thanks

**Comment by servocoder** [comment]
You are welcome! Don't forget to visit WIKI if you have any further questions.

**Comment by hengsoheak** [comment]
Yes
