### ISSUE TITLE
download files issue

### ISSUE THREAD

**Issue by doziteh** [servocoder/RichFilemanager#60]
The problem is when trying to download single file we are getting files with 0 bytes.
Looking into code we found
In php connector LocalFilemanager.php line 852
actionDownload() method
...
```
$chunk_size = 16 * 1024 * 1024;
// read file by chunks to handle large files

        if ($chunk_size && $file_size > $chunk_size) {
            $handle = fopen($target_fullpath, 'rb');
            while (!feof($handle)) {
                echo fread($handle, $chunk_size);
                @ob_flush();
                @flush();
            }
            fclose($handle);
        } 
```

No else? I can't see where and how files with size <16Gb are output.
I added
```
else {
$handle = fopen($target_fullpath, 'rb');
echo fread($handle, $file_size);
@ob_flush();
@flush();

            fclose($handle);
        }
```
and now download single file works...

**Comment by servocoder** [comment]
Hi, you are right. I am able to reproduce the issue.
All downloaded files > 16Mb have zero size indeed.
I will fix it as soon as possible and update the repo.
Thanks for reporting.

**Comment by servocoder** [comment]
Fixed in v.2.0.1, thanks for the contribution
