### ISSUE TITLE
Some help for config.php (Unable to perform initial request to server)

### ISSUE THREAD

**Issue by tenq** [servocoder/RichFilemanager#62]
I tried to use this file manager with ckeditor in modal, but I receive this message:

Unable to perform initial request to server.

```PHP Parse error:  syntax error, unexpected '[' in \admin\editor\filemanager\connectors\php\config.php on line 10```

FileManger folder is in: /admin/editor/filemanager

My userfiles is in: /arquivos/userfiles (folder with write permission)

The Server is Windows 2008 running PHP.
thanks

**Comment by servocoder** [comment]
Seems you use PHP version < 5.4
RichFilemanager requires PHP 5.4 or higher

**Comment by tenq** [comment]
tks
