### ISSUE TITLE
Optionally return full S3 path on select

### ISSUE THREAD

**Issue by LukasCore** [servocoder/RichFilemanager#63]
Right now the "select" button returns a filemanager link instead of using the direct link to the file. This makes no sense when you want to link to an image directly.

**Comment by servocoder** [comment]
I will check it after complete the current features.

Initially S3 connector was developed to handle objects of protected buckets. I assume your S3 files are public and available via direct links. Could you give more details on your case. You could also share some of your public links.

**Comment by servocoder** [comment]
According to [this post](http://stackoverflow.com/a/35127502/1789808) it's not possible to create permanent direct link to Amazon S3 object. Please, describe your case and requirements in all details if you want to get assistance in your problem.

**Comment by LukasCore** [comment]
Yes the uploaded files are public. The user uploads the file and then adds it into his text through tinymce. The current links don't work since the tinymce is only accessible after admin login.
It would be best for us if we could set a prefix for the returned url paths, since in the end the s3 links should be CloudFront links that link to the S3 file.

**Comment by servocoder** [comment]
Could you provide some of your public links as is and the same links with the prefix (or postfix) including CloudFront links, so I will be able to understand your case better. Thank you.

**Comment by LukasCore** [comment]
An example would be: https://[cloudfronturl]/path/to/picture.jpg]. In S3 the file would be located at [bucket]/path/to/picture.jpg.
So the easiest way for us would be to provide the "https://[cloudfronturl]" prefix and get the full url back, instead of getting a filemanager link. The other option would be some kind of hook that can manipulate the url before it gets passed to tinymce or into the clipboard.

**Comment by servocoder** [comment]
It sounds good, but I don't use CloudFront and I don't have much time at the moment to handle this. Perhaps I can pay attention to this after new year. But, if you want to force it I need some real exmaples and more extensive description. You could left your email or Skype id and I will contact you for details.

**Comment by LukasCore** [comment]
email is support@zmbcube.com

**Comment by LukasCore** [comment]
this issue is fixed for me with the #70 ticket. so unless you want to do it anyway, i'm happy here:)

**Comment by servocoder** [comment]
Great, thanks for the feedback.
I will keep this issue open until make a decision what to do with it )

**Comment by servocoder** [comment]
In addition you can use callback functions, see example in #264

**Comment by erashdan** [comment]
Hello, please help how I can return S3 url to tinyMCE ?
