### ISSUE TITLE
Why this images/files path inserting in database?? 

### ISSUE THREAD

**Issue by anasadeel** [servocoder/RichFilemanager#66]
""C:\xampp\tmp\phpE258.tmp""

Controller's Code:
Employee::create($request->all());
$imageName = $request->employee_profile_image->getClientOriginalName();
 if ($request->file('employee_profile_image')->isValid()) {
$request->file('employee_profile_image')->move(base_path() . '/public/images/',$imageName);
}

**Comment by servocoder** [comment]
Original RichFilemanager doesn't deal with any database. I have no idea of that piece of code that you have provided. It doesn't relate to original RichFilemanager. So I suppose either you have made this modifications by yourself or you use some modified fork of RichFilemanager. In the last case you have to ask author of the fork.
