### ISSUE TITLE
How to allow users to have their own folder

### ISSUE THREAD

**Issue by polak25** [servocoder/RichFilemanager#68]
Hello,

the method is no update for the last version i thank

https://github.com/servocoder/RichFilemanager/wiki/How-to-allow-users-to-have-their-own-folder

Please help to add folderPath with Session Php ?!

**Comment by servocoder** [comment]
You are right, this article is outdated. I'm going to update it in the coming days. Also I have found an issue in the `setFileRoot` method, so I aslo have to perform a new bugfix release. I will let you know when the things are ready.

**Comment by polak25** [comment]
Thank you

**Comment by servocoder** [comment]
Hello, I have updated [wiki article](https://github.com/servocoder/RichFilemanager/wiki/Specify-user-folder%2C-configuration-cases). Please follow the instructions to set custom user folder. The bug that I had mentioned above relates to S3 plugin, so you can ignore it. I will release a patch later. Feel free to ask if you will face any troubles with user folder setup.
