### ISSUE TITLE
Trash Folder

### ISSUE THREAD

**Issue by fullergalway** [servocoder/RichFilemanager#69]
Useful project, thanks!

How about an optional "Trash" folder. If feature is turned on, deleted files are moved here. Files deleted from trash folder are unlinked.

Trash folder could contain slightly extended hierarchy to include timestamp of the delete.

For example, deleting fred/wilma.jpg would move the file to trash/{timestamp}/fred/wilma e.g. trash/2016/12/05/093530/fred/wilma.jpg

Some possible complications related to nicely displaying contents of trash folder if very large.

**Comment by servocoder** [comment]
Thanks for the suggestion, it's nice idea. I have labeled it as feature request and I need to think it over before decide whether to add it into TODO list. Anyhow I'm busy with other stuff at the moment, perhaps I will implement this feature later. Thanks again.

**Comment by servocoder** [comment]
Trash folder will require complex workaround and extremely depends on server capabilities.

I don't consider this feature as appropriate for the RFM at the moment.
