### ISSUE TITLE
Failed to upload files named by pure non-latin chars

### ISSUE THREAD

**Issue by billzt** [servocoder/RichFilemanager#7]
Using the lastest master version, upload files named by latin chars is totally OK. However upload files named by pure non-latin chars failed.

In configure file, "charsLatinOnly" has been set to "false"

When I upload a file called `测试文件.txt` , it shows:

![aa](https://cloud.githubusercontent.com/assets/1146090/16065291/062b96c8-32dc-11e6-9310-108132fc4799.PNG)
![20160615092018](https://cloud.githubusercontent.com/assets/1146090/16065293/0b28707e-32dc-11e6-8637-b6759833e187.png)

When I upload a file called `a测试文件.txt` (begin with latin chars, end with non-latin chars), it is OK. 
When I upload a file called `测试文件a.txt` (begin with non-latin chars, end with latin chars), it is also OK, however non-latin chars would be deleted. Therefore the result name is only `a.txt`.

**Comment by simogeo** [comment]
> Using the lastest master version, upload files named by latin chars is totally OK. However upload files named by pure non-latin chars failed. 

same problem here

**Comment by servocoder** [comment]
Try to set `normalizeFilename` to _false_
https://github.com/servocoder/RichFilemanager/wiki/Filemanager-configuration-file#the-security-section

If you has INTL extension installed it would transliterate chars, otherwise it cuts non-latin chars.

**Comment by billzt** [comment]
Well, first I confirm that php-intl has been installed (this is the output from `<?php phpinfo(); ?>`)
![20160615205925](https://cloud.githubusercontent.com/assets/1146090/16080586/0e71831e-333c-11e6-835a-ff35a49b8541.png)

Second, I changed ` "normalizeFilename": false,` in configure file.

However, the problem also occurs. 

It should be noticed that the filename stored in the **server directory** (viewed from FTP) is OK, but the filename shown in the **web Filemanager** is wrong. Non-latin chars again has been cut.

**Comment by servocoder** [comment]
I see, going to research it soon

**Comment by servocoder** [comment]
Hey, I have review my code and have come to such thoghts:
1) `normalizeFilename` should not affect your problem.
2) The version of your ICU is quite old, it would be a good idea to update it, but this is not the cause of the error.
3) Take a look at https://github.com/simogeo/Filemanager/issues/474 - this issue was opened by you. If that is the same case there is the solution I have provided for the problem via `setlocale`. Try it and let me know.

**Comment by servocoder** [comment]
So you have to add string `setlocale(LC_ALL, 'en_US.UTF-8');` in the `LocalFilemanager::__constructor()` [here](https://github.com/servocoder/RichFilemanager/blob/master/connectors/php/LocalFilemanager.php#L30). If you will manage with this, then I will think on the better way to apply it in the code.

**Comment by billzt** [comment]
Yes. After add `setlocale(LC_ALL, 'en_US.UTF-8');`, the bug is fixed. Thank you!

**Comment by servocoder** [comment]
The fix has been included.

**Comment by hnxuan** [comment]
In the latest version of this bug again.Cannot create the pure Chinese folder.
