### ISSUE TITLE
Callback documentation

### ISSUE THREAD

**Issue by LukasCore** [servocoder/RichFilemanager#70]
Is there a place in the wiki or in the code where i can see all the possible callbacks that i can define for the manager?
I would mostly need a way to hook into the selection process and react to it, possibly even changing parts of the selection before it is completed.
thank you

**Comment by servocoder** [comment]
There are no such callbacks at the moment, but it's a nice thing to be implemented. I will keep it in mind. Thanks.

**Comment by servocoder** [comment]
By the way, do you this this will help you with the CloudFront problem, that you described in #63 ? I have started to work on it, but faced with another issue, so it's required some extra time. This issue seems to be faster to implement, so I can perform it first in case it solves your problem.

**Comment by servocoder** [comment]
Just released in v2.0.3
All available callback functions are described in the [Wiki article](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options#client-side-configuration), hope it will cover you requirements.

**Comment by LukasCore** [comment]
Thank you.
Yes i think this will help with #63. 

Another question: How do you close the RichFilemanager when someone clicks the select button? As far as i can tell, there is no option or callback for this.

**Comment by servocoder** [comment]
It depends on WYSIWYG editor. Each one have it's own method to close dialog window.

**Comment by LukasCore** [comment]
No editor. Open it with a button, let the user select an image that gets displayed through the "field_name" query. After select, the filemanager should be closed.
Do I have to do this with a watcher on the display element or is there some way to know when "select" was clicked?

**Comment by servocoder** [comment]
Ok, if no editor in use I suppose you open filemanager in some modal window (jQuery, bootstrap, etc.). In this case you just need to close the modal window. RichFilemanager doesn't have it's own modal windows. In general you load it to some "container" (iframe or modal window) or use it as full screen filemanager as at the demo page. So you can't "close" filemanager, but you may want to close/hide container which contains filemanager. Hope it's clear.

**Comment by LukasCore** [comment]
Yes, that's what I'm trying to do, i just don't know "when" to close it. I mean, is there some callback or configuration where i can be notified if something was selected, so that i can close the modal?
Similar to the "beforeSelectItem" callback, just after:)

**Comment by servocoder** [comment]
Oh, I see now )
The short answer is no, except you open filemanager with `window.open()`. I would suggest you to create new issue. I will give more extensive answer there and we will think over solution.

**Comment by avatar** [comment]
Hi, I have the same problem as LukasCore (direct url to s3). I'm using CKeditor, but i don't know how to specify the callbacks mentionned in the wiki article specified. Just putting the mentionned code does not work, because i guess RicheFilemanager is instanciated by ckeditor.
