### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by polak25** [servocoder/RichFilemanager#71]
Hello,

your project is not on composer, it's bad ...

https://packagist.org/search/?q=servocoder

It's possible to add, it was easy for futur update.

Thanks

**Comment by servocoder** [comment]
Right, composer is going to be added in the one of closest releases.

**Comment by servocoder** [comment]
Released in v2.1.0

**Comment by polak25** [comment]
Hello,

i didn't find the package : https://packagist.org/search/?q=richfilemanager

Thanks

![screen shot 01-25-17 at 02 52 pm](https://cloud.githubusercontent.com/assets/6706279/22292932/e6c542a6-e30d-11e6-8e28-8ec7fe9cd275.PNG)

**Comment by servocoder** [comment]
Thanks for tracing packagist. Seems I forgot to add hook within the last release. Hope it will be ok the next time.

**Comment by servocoder** [comment]
Added to the packagist.
