### ISSUE TITLE
S3 connector treats urls as urlencoded

### ISSUE THREAD

**Issue by LukasCore** [servocoder/RichFilemanager#72]
There is an image named "Burkholderia%20spp.%20red.jpg" on our S3. When the S3 connector tries to show the image, it interprets the name as being urlencoded and tries to open the wrong url. It really should open "Burkholderia%2520spp.%2520red.jpg" in that case.
I know that files shouldn't be named like that, but if possible, it would be nice if this case could be fixed.
Thank you

**Comment by servocoder** [comment]
Yeah, url should be encoded.
I have just created a file with the same name and preview and select works correct.
Have you modified your filename with callback functions? Perhaps it's the case.
Check it without callbacks and if the problem remains then describe your action step by step.

**Comment by LukasCore** [comment]
ah you are right, sorry. i used the callback function and forgot to urlencode the "resourceObject.id" in the url.
