### ISSUE TITLE
Notification when a file was selected

### ISSUE THREAD

**Issue by LukasCore** [servocoder/RichFilemanager#73]
Right now it's hard to know when a user finished selecting files and then closing the filemanager. It would be great if there was a callback for more things that happen inside the filemanager, so the rest of the code can react to it.
Apart from that, it would be great if the callbacks could be configured in the config file, so that we don't have to manually merge the changes when a new version is released.

**Comment by servocoder** [comment]
There is no such callback at the moment, window will be closed in case it was opened with `window.open()` native browser method. But if you open filemanager in a modal window (jQuery, bootstrap, or a custom one) the only way to close it, is to utilize a callback like "afterSelectItem". I'm going to implement it soon.

As for your idea to define callbacks in the configuration file. I understand the problem and I like your suggestion, but it's not possible to define functions inside `json` files. I could change extension to js, but I have to think it over before do it. Perhaps you can see another solution.

**Comment by LukasCore** [comment]
including a callbacks.config.js as well as the config.js would be fine as well. that way we might even run some extra code without touching the index.html

**Comment by servocoder** [comment]
I have added "afterSelectItem" callback, including base example of usage with bootstrap modal loading filemanager via iframe. Check details at the [wiki article](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options#client-side-configuration), also there is working [demo example](https://github.com/servocoder/RichFilemanager/blob/master/demo/index.html) of bootstrap modal. I'm going to add more example soon. Let me know if that works for you.

At the moment you still have to specify "afterSelectItem" callback as plugin settings. I'm going to change this in the closest release. I will let you know.

**Comment by servocoder** [comment]
I have created a separate file for plugin initialization, so you won't need to merge the changes when a new version is released. It's located in `/config/filemanager.init.js.example` and you have to rename it to `/config/filemanager.init.js`. Also note that `json` configuration file was also moved to `/config/` folder.

It will be included in the next release. At the moment you could test it at the [dev branch](https://github.com/servocoder/RichFilemanager/tree/dev), I would appreciate your feedback.

**Comment by servocoder** [comment]
Released in v2.1.0
