### ISSUE TITLE
Uploading images is validating tmp file path

### ISSUE THREAD

**Issue by howdu** [servocoder/RichFilemanager#74]
I'm a bit stuck with this if anybody can offer any advice where I'm going wrong. 

Trying to setup with tinymce on window/wamp php7.0.10
I'm getting this error: Please upload only images, no other files are supported

When I debug the is_valid_image_file() it's always returning false for the first line.
`if (!preg_match($this->options['image_file_types'], $file_path)) {`

The var $file_path is the tmp file name 'C:\wamp\tmp\php1F82.tmp'

I've tried updating this in LocalUploadHandler.php so it passes the upload path  the first IF statement above but fails. with exif_imagetype.
```
        $upload_path = $this->get_upload_path($file->name);

        if($this->fmData['images_only'] && !$this->is_valid_image_file($upload_path)) {
```

**Comment by servocoder** [comment]
I have never tested it with php7, I will take a look

**Comment by champlainmarketing** [comment]
I'm getting the same error ( Please upload only images, no other files are supported) when trying to upload to my server running 7.0.15

**Comment by servocoder** [comment]
Could you attach file which was failed? I have checked the case with different images all of them have been uploaded successfully.

**Comment by champlainmarketing** [comment]
![orson](https://cloud.githubusercontent.com/assets/5174191/22451273/2248beee-e73b-11e6-8277-e9fc05255242.gif)
![no-country-for-old-blogs](https://cloud.githubusercontent.com/assets/5174191/22451274/224e802c-e73b-11e6-9e30-14d5f852b034.jpg)

**Comment by servocoder** [comment]
@champlainmarketing I have managed to upload your images.

1. Have you got any error on images which are failed? (inside error popup or upon hovering image thumbnail).

2. If no error and hover tooltip is empty, then most likely you will be able to find the error in browser's console (Network -> XHR tab for Chrome).

3. Finally the error should be logged in the log file of you web server (apache?).

Please provide the error you get.

**Comment by servocoder** [comment]
@howdu Could you provide some additional information or your image files? If it fails on exif_imagetype then it may be an issue with the files. Have you tried it in php5.x ?

**Comment by champlainmarketing** [comment]
Error: Please upload only images, no other files are supported.

PHP 5 breaks the CMS I'm building this into. I'll see if I can set this up in a different directory and use php.ini or htaccess to dial it back down to PHP 5.

**Comment by servocoder** [comment]
Hm, I tried on either PHP versions 5.6 and 7, but it works well for me.
Perhaps the issue depends on your PHP configuration or environment.
Try to test it with PHP < 7 to find out the the cause of the problem.

**Comment by champlainmarketing** [comment]
I tried it with PHP 5 and got the same error.

**Comment by servocoder** [comment]
Good, so now ne know for sure that the issue does not depend on PHP version. Try to play with the php extensions: turn on/off exif and mbstring (php_mbstring.dll and php_exif.dll on Windows).

**Comment by howdu** [comment]
Tested with php 5.5, 5.6 and 7.0 same error in all and both extension enabled. Perhaps it's a windows only issue. 

```php
protected function is_valid_image_file($file_path) {
    $file_name = $this->get_file_name($file_path);
    if (!preg_match($this->options['image_file_types'], $file_name)) {
        return false;
    }
    if (function_exists('exif_imagetype')) {
        return @exif_imagetype($file_path);
    }
    $image_info = $this->get_image_size($file_path);
    return $image_info && $image_info[0] && $image_info[1];
}
```

It's trying to validate the temporary path because $file_path is 'C:\wamp\tmp\php382F.tmp'

So it never passes this code. 
if (!preg_match($this->options['image_file_types'], $file_path)) {
      return false;
}

If I comment the above code out, then it works ok and passes exif_imagetype()

To fix perhaps passing the real filename as the second param. 
if($this->fmData['images_only'] && !$this->is_valid_image_file($uploaded_file, $file->name)) {

**Comment by servocoder** [comment]
Yeah, finally I have managed to reproduce the issue. Thanks for your help and details. I will take care of this problem in the coming days and let you know once it is solved.

**Comment by servocoder** [comment]
Fixed. Please, check on DEV branch and leave the feedback.

**Comment by howdu** [comment]
Confirmed to be working very well, thanks

**Comment by champlainmarketing** [comment]
I was getting two errors when trying to load File Manager. 
Given config file (./scripts/filemanger.config.default.json) does not exist!
Given config file (./scripts/filemanger.config.json) does not exist!

Until I cleared my cache. It's working now. Thanks!
