### ISSUE TITLE
Making RF as extension

### ISSUE THREAD

**Issue by triawarman** [servocoder/RichFilemanager#76]
I'm making yii2-richFilemanager extension, and had some problems, i expect to get some advice(or clue's).

https://github.com/triawarman/yii2-richfilemanager repo for the extension is being made.

After doing some adjustments to call js and css library, i get an error messages:
"Given config file (./scripts/filemanager.config.default.json) does not exist!"
"Given config file (./scripts/filemanager.config.json) does not exist!"

these two files are exists, maybe the problem probably a relative path to the folder FM which may be referred to "../web/" not on "../web/assets/8fec9a0f/scripts/" (this is path where relative RichFilemanager located).

any sugestion ?

**Comment by servocoder** [comment]
Have you solved your problem? Take a look `baseUrl` parameter description at [this code example](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options#client-side-configuration). If you publish RichFilemanager folder with other assets you have to change `baseUrl` to the correct one, passed from Yii2.

**Comment by triawarman** [comment]
i solved this one, and get another one, after read your comment, i'm not sure what i'm doing is good.
i alter few codes, like added

```javascript
   var scriptElements = document.getElementsByTagName('script');
    var i, element, myfile, myurl, assetsDir;

    for( i = 0; element = scriptElements[i]; i++ ) {

        myfile = element.src;

        if( myfile.indexOf( 'filemanager.js' ) >= 0 ) {
            var myurl = myfile.substring( 0, myfile.indexOf( 'filemanager.js' ) );
        }
    }
    var string = myurl;
    var arr = string.split('/');
    assetsDir = arr[arr.length-5] + '/' +arr[arr.length-4];
    //INFO: Will get value like assets/2e1daf3d
```

and then change some code like in localize
```javascript
var localize = function() {
var langCode = $.urlParam('langCode');
//var langPath = fm.settings.baseUrl + '/languages/';
var langPath = assetsDir + '/languages/';
```

This will give the exact location of the assets files, but i got another problem 
```javascript
knockout-3.4.0.js:68 Uncaught SyntaxError: Unable to parse bindings.
Bindings value: visible: !loadingView() && !previewFile() && viewMode() === 
Message: Unexpected token }
parseBindingsString @ knockout-3.4.0.js:68getBindingAccessors @ knockout-3.4.0.js:67a.B.i @ knockout-3.4.0.js:71Pc @ knockout-3.4.0.js:51Qc @ knockout-3.4.0.js:51aa @ knockout-3.4.0.js:50a.m.a.B @ knockout-3.4.0.js:49m @ knockout-3.4.0.js:71k @ knockout-3.4.0.js:69g @ knockout-3.4.0.js:69k @ knockout-3.4.0.js:69g @ knockout-3.4.0.js:69k @ knockout-3.4.0.js:69g @ knockout-3.4.0.js:69k @ knockout-3.4.0.js:69g @ knockout-3.4.0.js:69k @ knockout-3.4.0.js:69g @ knockout-3.4.0.js:69k @ knockout-3.4.0.js:69a.Rb @ knockout-3.4.0.js:75initialize @ filemanager.js:448(anonymous function) @ filemanager.js:255(anonymous function) @ jquery-1.11.3.min.js:2j @ jquery-1.11.3.min.js:2fireWith @ jquery-1.11.3.min.js:2e.(anonymous function) @ jquery-1.11.3.min.js:2j @ jquery-1.11.3.min.js:2fireWith @ jquery-1.11.3.min.js:2(anonymous function) @ jquery-1.11.3.min.js:2j @ jquery-1.11.3.min.js:2fireWith @ jquery-1.11.3.min.js:2x @ jquery-1.11.3.min.js:5b @ jquery-1.11.3.min.js:5
fonts.googleapis.com/css?family=Oxygen:1 GET https://fonts.googleapis.com/css?family=Oxygen net::ERR_TIMED_OUT
```

in construct = function(){
deferred
...
.then(function() {                 
                    includeAssets();
                    initialize();               
 });
the exact location is when to code try running "ko.applyBindings(fmModel);"

maybe i should let the RichFilemanager files location as the original one (not changing location or code), doing as code example code you give me

**Comment by servocoder** [comment]
Looks confusing and may cause to other troubles. Sure, you can try the way I have suggested.

**Comment by triawarman** [comment]
i have manage to make the extension.

another question, i'm trying to pass some parameter in jquery
```javascript
$('.fm-container').richFilemanager({
"config":{
       "options": {
                "theme": "flat-turquoise",
       }
}
 });
```
its not working, i'm doing this wrong ?

**Comment by servocoder** [comment]
It's not because of your changes in code. The plugin accepts only `callbacks` and `baseUrl` options. All other config options should be set via config file. I know it's not flexible and convenient as much as it could be. Perhaps I will add capability to override config options upon plugin init, when I will have much time for this.

**Comment by triawarman** [comment]
yup, i'll waiting, for next update.
RichFilemanager is great.

thank's for making this plugin.
