### ISSUE TITLE
Scrollbar not showing on initial load

### ISSUE THREAD

**Issue by doziteh** [servocoder/RichFilemanager#77]
On initial load of FM scrollbar is not showing and there is no way to access/view files that didn't fit on the window.
After browser window resize scrollbar appears.
I am using 2.0.1. "selectable" branch of FM
and browser is Chrome 55 and I have confirmed this behavior in Opera also.
Some configuration option or bug?

**Comment by servocoder** [comment]
It should be ok if you use default configuration. Could you share some screenshots and explain the context of using FM (wysiwyg editor or fullscreen as is) ?  It would be even better if you can share a live link to observe the problem. Btw, try the latest version at the [dev branch](https://github.com/servocoder/RichFilemanager/tree/dev), there were some changes which may potentially affect scrollbar.

**Comment by servocoder** [comment]
Oh, I can see the problem now. Missed you faced it on "selectable" branch. It's a bug definitely. Thanks for reporting.

**Comment by servocoder** [comment]
Check the "selectable" branch now.
Note that I have merged dev branch into selectable branch, so there are some more changes. [This one](https://github.com/servocoder/RichFilemanager/issues/73#issuecomment-271176870) is important. Looking forward for your feedback.

**Comment by doziteh** [comment]
It works now. 
Thank you very much.

**Comment by servocoder** [comment]
Fixed in v2.1.0
