### ISSUE TITLE
Selecting image does not close window after selection

### ISSUE THREAD

**Issue by justingit** [servocoder/RichFilemanager#82]
Hello! I'm trying to integrate RichFilemanger with CKeditor. I have a lot of experience using Filemanager, but there seems to be some differences.

 First, when you select a file from RichFileManager, the window that RichFileManager is in does not close itself, so it's difficult to know if things are selected. 

Secondly, if you do self-close that RichFileManager window, I do not get the actual URL to the image, but rather something like this, 

http://dancingindigochild.local/RichFilemanager/connectors/php/filemanager.php?mode=readfile&path=%2Fhum.jpg&time=1484627177072

When all I want is this, 

http://dancingindigochild.local/file_uploads/hum.jpg

Something I'm doing strange in my config? In the php connector, I've only changed two things: 

Set, 

        "serverRoot" => false,

And set a absolute path for, 

fileRoot

![preview](https://cloud.githubusercontent.com/assets/39739/22007814/ed947d22-dc32-11e6-9337-7b4e40fa8d53.jpg)

**Comment by servocoder** [comment]
RichFilemanager was reworked a lot and includes a lot of back incompatible changes. However the wiki article of "[How to open the Filemanager from CKEditor in a modal window](https://github.com/servocoder/RichFilemanager/wiki/How-to-open-the-Filemanager-from-CKEditor-in-a-modal-window)" works great, you can check the [live demo](http://fm.devale.pro/demo/index.html).

As for the second problem. Once you set `serverRoot` to `false` RFM interprets this as your images located outside server document root, where the RFM is located itself, so it's unable to autodefine url to your user files. All this stuff described in a [Specify user folder, configuration cases](https://github.com/servocoder/RichFilemanager/wiki/Specify-user-folder%2C-configuration-cases#configuration-examples) wiki article. In case your files may be accessible with a direct url, but located outside server root you can set `viewer`.`absolutePath` to `true` and setup `viewer`.`previewUrl` configuration options in your JSON configuration file to obtain direct url, see [Configuration-options](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options#the-viewer-section) wiki article.

**Comment by justingit** [comment]
Thanks for all those links. I have a lot to read for homework! 

And thank you for all the work you have all put into this new version,

**Comment by servocoder** [comment]
Sure, enjoy reading )
