### ISSUE TITLE
Logging Fails

### ISSUE THREAD

**Issue by justingit** [servocoder/RichFilemanager#83]
If I visit the php connector directly, I get a whole lot of verbose information about logging failing, 

	Warning: fopen(/var/folders/0b/1yhyqdn172z14v7cp8fzf5m00000gn/T/filemanager.log): failed to open stream: Permission denied in /Applications/XAMPP/xamppfiles/htdocs/dm/dada_mail_support_files/RichFilemanager/connectors/php/application/Logger.php on line 32

	Warning: fwrite() expects parameter 1 to be resource, boolean given in /Applications/XAMPP/xamppfiles/htdocs/dm/dada_mail_support_files/RichFilemanager/connectors/php/application/Logger.php on line 33

	Warning: fclose() expects parameter 1 to be resource, boolean given in /Applications/XAMPP/xamppfiles/htdocs/dm/dada_mail_support_files/RichFilemanager/connectors/php/application/Logger.php on line 34

	Warning: fopen(/var/folders/0b/1yhyqdn172z14v7cp8fzf5m00000gn/T/filemanager.log): failed to open stream: Permission denied in /Applications/XAMPP/xamppfiles/htdocs/dm/dada_mail_support_files/RichFilemanager/connectors/php/application/Logger.php on line 32

	Warning: fwrite() expects parameter 1 to be resource, boolean given in /Applications/XAMPP/xamppfiles/htdocs/dm/dada_mail_support_files/RichFilemanager/connectors/php/application/Logger.php on line 33

	Warning: fclose() expects parameter 1 to be resource, boolean given in /Applications/XAMPP/xamppfiles/htdocs/dm/dada_mail_support_files/RichFilemanager/connectors/php/application/Logger.php on line 34

	Warning: fopen(/var/folders/0b/1yhyqdn172z14v7cp8fzf5m00000gn/T/filemanager.log): failed to open stream: Permission denied in /Applications/XAMPP/xamppfiles/htdocs/dm/dada_mail_support_files/RichFilemanager/connectors/php/application/Logger.php on line 32

	Warning: fwrite() expects parameter 1 to be resource, boolean given in /Applications/XAMPP/xamppfiles/htdocs/dm/dada_mail_support_files/RichFilemanager/connectors/php/application/Logger.php on line 33

	Warning: fclose() expects parameter 1 to be resource, boolean given in /Applications/XAMPP/xamppfiles/htdocs/dm/dada_mail_support_files/RichFilemanager/connectors/php/application/Logger.php on line 34

	Warning: fopen(/var/folders/0b/1yhyqdn172z14v7cp8fzf5m00000gn/T/filemanager.log): failed to open stream: Permission denied in /Applications/XAMPP/xamppfiles/htdocs/dm/dada_mail_support_files/RichFilemanager/connectors/php/application/Logger.php on line 32

	Warning: fwrite() expects parameter 1 to be resource, boolean given in /Applications/XAMPP/xamppfiles/htdocs/dm/dada_mail_support_files/RichFilemanager/connectors/php/application/Logger.php on line 33

	Warning: fclose() expects parameter 1 to be resource, boolean given in /Applications/XAMPP/xamppfiles/htdocs/dm/dada_mail_support_files/RichFilemanager/connectors/php/application/Logger.php on line 34
	{"data":""}

I have to change the following line in connectors/php/application/Logger.php: 

        $this->file = sys_get_temp_dir() . '/filemanager.log';

to just, 

      $this->file = './filemanager.log';

Without this change, RichFileManager does not function. 

![_-_2017-01-16_21 31 24](https://cloud.githubusercontent.com/assets/39739/22007847/3fc8b9d2-dc33-11e6-8cfa-691209aa20ba.png)

**Comment by servocoder** [comment]
This means RFM doesn't have permissions to access `sys_get_temp_dir()` folder. The one way is to grant permissions, and the other is to change path to log file, as you did.
