### ISSUE TITLE
Have left-side tree show dirs only, not files

### ISSUE THREAD

**Issue by dereks** [servocoder/RichFilemanager#84]
I would like the tree to show only directories, not files. This is how phpFileManager does it:

> http://phpfm.sourceforge.net/img/ss0.9.9.png

I would be willing to write the code and submit a Pull Request for a new config option, but I could use some assistance with how / where to create this option in the source code.

Any advice is appreciated. (I'm using the PHP connector.)

**Comment by servocoder** [comment]
Accepted as a feature request. Shouldn't be too complex to implement.

**Comment by servocoder** [comment]
It's already implemented. Set `options`.`listFiles` option to `false` at your JSON configuration file.
