### ISSUE TITLE
Render Markdown files, with default file render

### ISSUE THREAD

**Issue by dereks** [servocoder/RichFilemanager#85]
I would like to populate my file system with "README.md" Markdown files that are automatically rendered into HTML when browsing the directories. It would be similar to what GitHub does, except I want it for all directories (not just the top-level one). This would allow me to create a self-documenting file system for my organization.

Embedding images, and links to other files (and other rendered Markdown pages on my server) would need to work as expected. Here is a great Javascript renderer library under MIT license:

> https://markdown-it.github.io/

Finally, I would like to configure whether the README.md files are rendered above the file listing, or below the file listing. For example, I might want to force users to see the README.md contents (as pretty HTML) before seeing the list of files and subdirectories.

(Files named README.md would be rendered automatically when listing a directory, but viewing any other .md Markdown file would also cause it to be rendered into HTML.)

If this is a desired feature, I would be willing to work on it, but would need some pointers on where to look in the existing code. I would also be willing to negotiate a bounty for it.

Thank you!

**Comment by servocoder** [comment]
It's a great scope of things to do. I'm not going to consider this soon. If you want to contact me personally you are able to find my email in the composer.json file, for example.

**Comment by servocoder** [comment]
Btw, it would be great if you provide a mockup that depicts the feature you request for better understanding of your idea.

**Comment by servocoder** [comment]
Released in v2.3.0
