### ISSUE TITLE
Integrate ACE code editor

### ISSUE THREAD

**Issue by dereks** [servocoder/RichFilemanager#87]
The included text file editor has no syntax highlighting (that I saw on the demo) and it uses a variable-width font, instead of a fixed-width font like courier.

Could you tell me how to replace that with ACE, the syntax-highlighting code editor?

> https://ace.c9.io/

I will submit a Pull Request if I can get some basic help learning where to make this change. (I would be using this primarily for Markdown files, by the way.)

Thank you!

**Comment by servocoder** [comment]
Which type of file you expect to highlight syntax? Provide an example, please.

**Comment by dereks** [comment]
> Which type of file you expect to highlight syntax?

For me, personally, I am most interested in editing Markdown files (.md files) with syntax highlighting. However, the ACE editor (linked above) supports highlighting for 110 different languages, so if this feature is implemented, I would expect it to syntax highlight any ACE-supported language (all of which are text files). For example: .js, .php, .html, .xml, .c, .java, .yaml, .ini, .sql, etc.

Here is a forum post explaining how to select the correct ACE highlight mode based on the filename extension. It's 4 lines of Javascript:

> http://stackoverflow.com/questions/15903191/how-to-automatically-pick-a-mode-for-ace-editor-given-a-file-extension

If the file does not have a defined syntax -- for example, just a .txt file -- then ACE still allows editing and shows line numbers. It would act just like the existing text file editor, except that it has a monospace font.

Finally, regarding linked issue #88 , note that **only .md files** would make sense for side-by-side editing (because .md files get rendered into HTML files). It does not make sense to do side-by-side editing of .c files or .js files, for example. (The side-by-side feature would make it easy to document folders in the filesystem.)

Thank you!

**Comment by servocoder** [comment]
I'm not going to implement ACE instead of CodeMirror, because CodeMirror supports Markdown files highlighting as well. Check the demo pages:

https://codemirror.net/mode/markdown/
https://codemirror.net/mode/gfm/

It's not a problem to apply one of above for md files.
Which one do you prefer?

P.S. Not going to implement side-by-side feature soon.

**Comment by dereks** [comment]
Thank you for your reply. CodeMirror seems to be very similar to ACE, so this is great.

> Which one do you prefer?

GitHub flavored, it has extra stuff: https://codemirror.net/mode/gfm/

Question: Is CodeMirror the currently implemented editor on the demo site? If so, how can we change the style to use a monospace font (like Courier) instead of a variable-width font?

Q2: If I wanted to implement ACE (or a customized side-by-side editor), where would I look in the code? Just looking for a pointer in the right direction, such as a filename. I'm hoping the editor uses some kind of plugin API based on the file extension.

Thanks again!

**Comment by servocoder** [comment]
A1: With the latest commit at the DEV branch I have set code highlight enabled by default for [.md] files, But the demo will we updated with a next release. The settings you need are located in the JSON configuration file: `viewer`.`editable`. Don't be shy to explore "[Configuration options](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options)" Wiki article. Change the font as easy as pie inmain css file.

A2: I believe CodeMirror is able to meet your requirements and it's possible to integrate it with a side-by-side editor. If you want to implement this feature then I would gladly accept your pull request.

Indeed, CodeMirror integration is based on the file extension. Look through the function: https://github.com/servocoder/RichFilemanager/blob/master/scripts/filemanager.js#L3274
