### ISSUE TITLE
Filter throws js exceptions

### ISSUE THREAD

**Issue by LukasCore** [servocoder/RichFilemanager#89]
We are using the filemanager to show s3 files. When doing this the "search filter" on the bottom left doesn't work and throws the following exception:

> Uncaught TypeError: Cannot read property 'name' of undefined
    at Object.<anonymous> (filemanager.min.js:formatted:479)
    at Function.each (jquery-1.11.3.min.js:2)
    at filemanager.min.js:formatted:478

The minimized line looks like this:

>  var c = b.rdo.attributes.name;

If you need more information i can try it with a non minimized source.

**Comment by servocoder** [comment]
Sure, please try on non-minified file.

**Comment by servocoder** [comment]
Fix included in v2.2.0
