### ISSUE TITLE
icons for docx is wrong in list mode

### ISSUE THREAD

**Issue by billzt** [servocoder/RichFilemanager#9]
In List View mode, the icon for filetype "docx" is blank, but for "doc" is OK. In Grid View mode, both are OK.

![default](https://cloud.githubusercontent.com/assets/1146090/16177129/1bf06546-3657-11e6-833a-4f874b9c3ddf.PNG)

**Comment by billzt** [comment]
Besides, my docx file is created by MS Office 2016. When I download it from the FileManager, my browser (Firefox) complains that it is a zip file. Although it is OK after download.

**Comment by simogeo** [comment]
I alos observd a probleme with mime types when downloadin PDF seen as txt file ....

**Comment by billzt** [comment]
@simogeo In the newest commit, the PDF download is OK. How about docx and xlsx in your environment?

**Comment by servocoder** [comment]
I'm ok with docx files created in MS Office 2016
Share your docx/xlsx files, please.

**Comment by servocoder** [comment]
I have added new associations of some icons with file types for filetree and listview (docx, xlsx, odt, ods, odp, etc...). Waiting for the files created in MS Office 2016 to test.

**Comment by billzt** [comment]
@servocoder This is my docx file created with MS Office 2016.
[blank.docx](https://github.com/servocoder/RichFilemanager/files/329024/blank.docx)

**Comment by servocoder** [comment]
I have tested your file (was renamed), nothing wrong in my FF:
![screenshot_1](https://cloud.githubusercontent.com/assets/1310273/16329689/9362900c-39ec-11e6-864e-01cb2e322c3e.png)

It seems like wrong files associations in your OS (or browser)
Anyway you are right, this is hardly applies to the filemanager directly.

**Comment by billzt** [comment]
Well, as the bug is not important, I close it.
