### ISSUE TITLE
config.php is under git control

### ISSUE THREAD

**Issue by dereks** [servocoder/RichFilemanager#90]
Initial setup requires copying two .js files:

1. filemanager.config.default.json -> filemanager.config.json
2. filemanager.init.js.example -> filemanager.init.js

(Optionally, the copied files can be edited to set custom options.)

The copied files show up as untracked files in git, which is a little annoying, but it is easy to ignore and it could be easily fixed by adding them to the .gitignore file. So, the .js config files are cool.

In contrast, if using PHP, the user must also edit this file:

3. connectors/php/config.php -> edited to change **fileRoot** from _false_ to a valid path on the system.

This is a problem because, in order to run this code during development, I must edit **config.php**. But now, every time I try to do a git commit or branch change, git notices that config.php has changed and it asks me to take action. This is especially annoying when changing branches, because the developer must "stash" the change to config.php, checkout the new branch, then "stash apply" the config change back.

I propose fixing this so that config.php (and other connector config files) are treated like the .js files. It should be controlled by git as filename **config.default.php**, and then the user copies it to **config.php** and edits it. Then config.php can even be added to the .gitignore file so it doesn't show up as a (mildly annoying) untracked file.

If @servocoder agrees with this approach I will submit a Pull Request to the dev branch. (There are other ways to address config files in git, but I think this is the easiest.) 

Unfortunately, the Wiki docs will need to be updated to reflect this additional file copy during setup. (I am happy to make the documentation edits but I don't have write access to the project Wiki.)

Thanks!

**Comment by servocoder** [comment]
PHP connector's config files are part of a separate package now, that is located at the https://github.com/servocoder/RichFilemanager-PHP repository. Config files are not supposed to be replaced, but the options could be extended upon application initiation at the entry point script: https://github.com/servocoder/RichFilemanager-PHP#entry-point-setup
