### ISSUE TITLE
Sorting in list view doesn't work

### ISSUE THREAD

**Issue by Iworb** [servocoder/RichFilemanager#97]
Even in your demo page when I switch to list view and try to click on header - nothing happens. 
Browser: last version of Opera (42.0.2393.517).

**Comment by servocoder** [comment]
Confirmed. Seems it was broken within one of the latest releases.
Thanks for reporting. Will be fixed in the coming days.

**Comment by servocoder** [comment]
Fixed on DEV branch. Let me know if it works for you, please.

**Comment by Iworb** [comment]
Yes, it works now, thanks.
